// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/connection.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"math/big"
	"unsafe"
)

type conn struct {
	duckdbCon  /*line :18:12*/_Ctype_duckdb_connection /*line :18:31*/
	closed    bool
	tx        bool
}

func (c *conn) CheckNamedValue(nv *driver.NamedValue) error {
	switch nv.Value.(type) {
	case *big.Int, Interval:
		return nil
	}
	return driver.ErrSkip
}

func (c *conn) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	prepared, err := c.prepareStmts(ctx, query)
	if err != nil {
		return nil, err
	}

	res, err := prepared.ExecContext(ctx, args)
	errClose := prepared.Close()
	if err != nil {
		if errClose != nil {
			return nil, errors.Join(err, errClose)
		}
		return nil, err
	}
	if errClose != nil {
		return nil, errClose
	}
	return res, nil
}

func (c *conn) QueryContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	prepared, err := c.prepareStmts(ctx, query)
	if err != nil {
		return nil, err
	}

	r, err := prepared.QueryContext(ctx, args)
	if err != nil {
		errClose := prepared.Close()
		if errClose != nil {
			return nil, errors.Join(err, errClose)
		}
		return nil, err
	}

	// We must close the prepared statement after closing the rows r.
	prepared.closeOnRowsClose = true
	return r, nil
}

func (c *conn) PrepareContext(ctx context.Context, query string) (driver.Stmt, error) {
	return c.prepareStmts(ctx, query)
}

func (c *conn) Prepare(query string) (driver.Stmt, error) {
	if c.closed {
		return nil, errors.Join(errPrepare, errClosedCon)
	}

	stmts, count, err := c.extractStmts(query)
	if err != nil {
		return nil, err
	}
	defer func() func() { _cgoBase0 := /*line :84:35*/&stmts; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :84:42*/_Cfunc_duckdb_destroy_extracted(_cgo0); }}()()

	if count != 1 {
		return nil, errors.Join(errPrepare, errMissingPrepareContext)
	}
	return c.prepareExtractedStmt(stmts, 0)
}

// Begin is deprecated: Use BeginTx instead.
func (c *conn) Begin() (driver.Tx, error) {
	return c.BeginTx(context.Background(), driver.TxOptions{})
}

func (c *conn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx, error) {
	if c.tx {
		return nil, errors.Join(errBeginTx, errMultipleTx)
	}

	if opts.ReadOnly {
		return nil, errors.Join(errBeginTx, errReadOnlyTxNotSupported)
	}

	switch sql.IsolationLevel(opts.Isolation) {
	case sql.LevelDefault:
	default:
		return nil, errors.Join(errBeginTx, errIsolationLevelNotSupported)
	}

	if _, err := c.ExecContext(ctx, `BEGIN TRANSACTION`, nil); err != nil {
		return nil, err
	}

	c.tx = true
	return &tx{c}, nil
}

func (c *conn) Close() error {
	if c.closed {
		return errClosedCon
	}
	c.closed = true
	func() { _cgoBase0 := /*line :125:22*/&c.duckdbCon; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :125:35*/_Cfunc_duckdb_disconnect(_cgo0); }()
	return nil
}

func (c *conn) extractStmts(query string) ( /*line :129:44*/_Ctype_duckdb_extracted_statements /*line :129:73*/,  /*line :129:75*/_Ctype_idx_t /*line :129:82*/, error) {
	cQuery := ( /*line :130:12*/_Cfunc_CString /*line :130:20*/)(query)
	defer func() func() { _cgo0 := /*line :131:22*/unsafe.Pointer(cQuery); return func() { _cgoCheckPointer(_cgo0, nil); /*line :131:45*/_Cfunc_duckdb_free(_cgo0); }}()()

	var stmts  /*line :133:12*/_Ctype_duckdb_extracted_statements /*line :133:41*/
	count := func() _Ctype_idx_t{ _cgo0 := /*line :134:39*/c.duckdbCon; var _cgo1 *_Ctype_char = /*line :134:52*/cQuery; _cgoBase2 := /*line :134:60*/&stmts; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :134:67*/_Cfunc_duckdb_extract_statements(_cgo0, _cgo1, _cgo2); }()

	if count == 0 {
		errMsg := ( /*line :137:13*/_Cfunc_GoString /*line :137:22*/)(func() *_Ctype_char{ _cgo0 := /*line :137:58*/stmts; _cgoCheckPointer(_cgo0, nil); return /*line :137:64*/_Cfunc_duckdb_extract_statements_error(_cgo0); }())
		func() { _cgoBase0 := /*line :138:30*/&stmts; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :138:37*/_Cfunc_duckdb_destroy_extracted(_cgo0); }()
		if errMsg != "" {
			return nil, 0, getDuckDBError(errMsg)
		}
		return nil, 0, errEmptyQuery
	}

	return stmts, count, nil
}

func (c *conn) prepareExtractedStmt(stmts  /*line :148:43*/_Ctype_duckdb_extracted_statements /*line :148:72*/, i  /*line :148:76*/_Ctype_idx_t /*line :148:83*/) (*stmt, error) {
	var s  /*line :149:8*/_Ctype_duckdb_prepared_statement /*line :149:35*/
	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :150:48*/c.duckdbCon; _cgo1 := /*line :150:61*/stmts; var _cgo2 _Ctype_idx_t = /*line :150:68*/i; _cgoBase3 := /*line :150:71*/&s; _cgo3 := _cgoBase3; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); _cgoCheckPointer(_cgoBase3, 0 == 0); return /*line :150:74*/_Cfunc_duckdb_prepare_extracted_statement(_cgo0, _cgo1, _cgo2, _cgo3); }()

	if state == ( /*line :152:14*/_Ciconst_DuckDBError /*line :152:26*/) {
		err := getDuckDBError(( /*line :153:25*/_Cfunc_GoString /*line :153:34*/)(func() *_Ctype_char{ _cgo0 := /*line :153:59*/s; _cgoCheckPointer(_cgo0, nil); return /*line :153:61*/_Cfunc_duckdb_prepare_error(_cgo0); }()))
		func() { _cgoBase0 := /*line :154:28*/&s; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :154:31*/_Cfunc_duckdb_destroy_prepare(_cgo0); }()
		return nil, err
	}

	return &stmt{c: c, stmt: &s}, nil
}

func (c *conn) prepareStmts(ctx context.Context, query string) (*stmt, error) {
	if c.closed {
		return nil, errClosedCon
	}

	stmts, count, errExtract := c.extractStmts(query)
	if errExtract != nil {
		return nil, errExtract
	}
	defer func() func() { _cgoBase0 := /*line :170:35*/&stmts; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :170:42*/_Cfunc_duckdb_destroy_extracted(_cgo0); }}()()

	for i :=  /*line :172:11*/_Ctype_idx_t /*line :172:18*/(0); i < count-1; i++ {
		prepared, err := c.prepareExtractedStmt(stmts, i)
		if err != nil {
			return nil, err
		}

		// Execute the statement without any arguments and ignore the result.
		if _, err = prepared.ExecContext(ctx, nil); err != nil {
			return nil, err
		}
		if err = prepared.Close(); err != nil {
			return nil, err
		}
	}
	return c.prepareExtractedStmt(stmts, count-1)
}
