// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/arrow.go:1:1
//go:build !no_duckdb_arrow

package duckdb

/*
#include <stdlib.h>
#include <duckdb.h>
#include <stdint.h>

#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  // Array type description
  const char* format;
  const char* name;
  const char* metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema** children;
  struct ArrowSchema* dictionary;

  // Release callback
  void (*release)(struct ArrowSchema*);
  // Opaque producer-specific data
  void* private_data;
};

struct ArrowArray {
  // Array data description
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void** buffers;
  struct ArrowArray** children;
  struct ArrowArray* dictionary;

  // Release callback
  void (*release)(struct ArrowArray*);
  // Opaque producer-specific data
  void* private_data;
};

struct ArrowArrayStream {
	void (*get_schema)(struct ArrowArrayStream*);
	void (*get_next)(struct ArrowArrayStream*);
	void (*get_last_error)(struct ArrowArrayStream*);
	void (*release)(struct ArrowArrayStream*);
	void* private_data;
};

#endif  // ARROW_C_DATA_INTERFACE
*/
import _ "unsafe"

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"unsafe"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/cdata"
)

// Arrow exposes DuckDB Apache Arrow interface.
// https://duckdb.org/docs/api/c/api#arrow-interface
type Arrow struct {
	c *conn
}

// NewArrowFromConn returns a new Arrow from a DuckDB driver connection.
func NewArrowFromConn(driverConn driver.Conn) (*Arrow, error) {
	dbConn, ok := driverConn.(*conn)
	if !ok {
		return nil, fmt.Errorf("not a duckdb driver connection")
	}

	if dbConn.closed {
		return nil, errClosedCon
	}

	return &Arrow{c: dbConn}, nil
}

// QueryContext prepares statements, executes them, returns Apache Arrow array.RecordReader as a result of the last
// executed statement. Arguments are bound to the last statement.
func (a *Arrow) QueryContext(ctx context.Context, query string, args ...any) (array.RecordReader, error) {
	if a.c.closed {
		return nil, errClosedCon
	}

	stmts, size, err := a.c.extractStmts(query)
	if err != nil {
		return nil, err
	}
	defer func() func() { _cgoBase0 := /*line :105:35*/&stmts; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :105:42*/_Cfunc_duckdb_destroy_extracted(_cgo0); }}()()

	// execute all statements without args, except the last one
	for i :=  /*line :108:11*/_Ctype_idx_t /*line :108:18*/(0); i < size-1; i++ {
		stmt, err := a.c.prepareExtractedStmt(stmts, i)
		if err != nil {
			return nil, err
		}
		// send nil args to execute statement and ignore result (using ExecContext since we're ignoring the result anyway)
		_, err = stmt.ExecContext(ctx, nil)
		stmt.Close()
		if err != nil {
			return nil, err
		}
	}

	// prepare and execute last statement with args and return result
	stmt, err := a.c.prepareExtractedStmt(stmts, size-1)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	res, err := a.execute(stmt, a.anyArgsToNamedArgs(args))
	if err != nil {
		return nil, err
	}
	defer func() func() { _cgo0 := /*line :132:31*/res; return func() { _cgoCheckPointer(_cgo0, nil); /*line :132:35*/_Cfunc_duckdb_destroy_arrow(_cgo0); }}()()

	sc, err := a.queryArrowSchema(res)
	if err != nil {
		return nil, err
	}

	var recs []arrow.Record
	defer func() {
		for _, r := range recs {
			r.Release()
		}
	}()

	rowCount := uint64(func() _Ctype_idx_t{ _cgo0 := /*line :146:46*/*res; _cgoCheckPointer(_cgo0, nil); return /*line :146:51*/_Cfunc_duckdb_arrow_row_count(_cgo0); }())

	var retrievedRows uint64

	for retrievedRows < rowCount {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
		}

		rec, err := a.queryArrowArray(res, sc)
		if err != nil {
			return nil, err
		}

		recs = append(recs, rec)

		retrievedRows += uint64(rec.NumRows())
	}

	return array.NewRecordReader(sc, recs)
}

// queryArrowSchema fetches the internal arrow schema from the arrow result.
func (a *Arrow) queryArrowSchema(res * /*line :171:39*/_Ctype_duckdb_arrow /*line :171:53*/) (*arrow.Schema, error) {
	schema := ( /*line :172:12*/_Cfunc_calloc /*line :172:19*/)(1, ( /*line :172:24*/_Ciconst_sizeof_struct_ArrowSchema /*line :172:50*/))
	defer func() {
		cdata.ReleaseCArrowSchema((*cdata.CArrowSchema)(schema))
		func() { _cgo0 := /*line :175:10*/schema; _cgoCheckPointer(_cgo0, nil); /*line :175:17*/_Cfunc_free(_cgo0); }()
	}()

	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :179:3*/*res; _cgoBase1 := /*line :180:43*/&schema; _cgo1 := /*line :180:3*/(*_Ctype_duckdb_arrow_schema /*line :180:26*/)(unsafe.Pointer(_cgoBase1)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :181:3*/_Cfunc_duckdb_query_arrow_schema(_cgo0, _cgo1); }(); state == ( /*line :181:14*/_Ciconst_DuckDBError /*line :181:26*/) {
		return nil, errors.New("duckdb_query_arrow_schema")
	}

	sc, err := cdata.ImportCArrowSchema((*cdata.CArrowSchema)(schema))
	if err != nil {
		return nil, fmt.Errorf("%w: ImportCArrowSchema", err)
	}

	return sc, nil
}

// queryArrowArray fetches an internal arrow array from the arrow result.
//
// This function can be called multiple time to get next chunks,
// which will free the previous out_array.
func (a *Arrow) queryArrowArray(res * /*line :197:38*/_Ctype_duckdb_arrow /*line :197:52*/, sc *arrow.Schema) (arrow.Record, error) {
	arr := ( /*line :198:9*/_Cfunc_calloc /*line :198:16*/)(1, ( /*line :198:21*/_Ciconst_sizeof_struct_ArrowArray /*line :198:46*/))
	defer func() {
		cdata.ReleaseCArrowArray((*cdata.CArrowArray)(arr))
		func() { _cgo0 := /*line :201:10*/arr; _cgoCheckPointer(_cgo0, nil); /*line :201:14*/_Cfunc_free(_cgo0); }()
	}()

	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :205:3*/*res; _cgoBase1 := /*line :206:42*/&arr; _cgo1 := /*line :206:3*/(*_Ctype_duckdb_arrow_array /*line :206:25*/)(unsafe.Pointer(_cgoBase1)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :207:3*/_Cfunc_duckdb_query_arrow_array(_cgo0, _cgo1); }(); state == ( /*line :207:14*/_Ciconst_DuckDBError /*line :207:26*/) {
		return nil, errors.New("duckdb_query_arrow_array")
	}

	rec, err := cdata.ImportCRecordBatchWithSchema((*cdata.CArrowArray)(arr), sc)
	if err != nil {
		return nil, fmt.Errorf("%w: ImportCRecordBatchWithSchema", err)
	}

	return rec, nil
}

func (a *Arrow) execute(s *stmt, args []driver.NamedValue) (* /*line :219:62*/_Ctype_duckdb_arrow /*line :219:76*/, error) {
	if s.closed {
		return nil, errClosedCon
	}

	if err := s.bind(args); err != nil {
		return nil, err
	}

	var res  /*line :228:10*/_Ctype_duckdb_arrow /*line :228:24*/
	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :229:46*/*s.stmt; _cgoBase1 := /*line :229:55*/&res; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :229:60*/_Cfunc_duckdb_execute_prepared_arrow(_cgo0, _cgo1); }(); state == ( /*line :229:71*/_Ciconst_DuckDBError /*line :229:83*/) {
		dbErr := ( /*line :230:12*/_Cfunc_GoString /*line :230:21*/)(func() *_Ctype_char{ _cgo0 := /*line :230:50*/res; _cgoCheckPointer(_cgo0, nil); return /*line :230:54*/_Cfunc_duckdb_query_arrow_error(_cgo0); }())
		func() { _cgoBase0 := /*line :231:26*/&res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :231:31*/_Cfunc_duckdb_destroy_arrow(_cgo0); }()
		return nil, fmt.Errorf("duckdb_execute_prepared_arrow: %v", dbErr)
	}

	return &res, nil
}

func (a *Arrow) anyArgsToNamedArgs(args []any) []driver.NamedValue {
	if len(args) == 0 {
		return nil
	}

	values := make([]driver.Value, len(args))
	for i, arg := range args {
		values[i] = arg
	}

	return argsToNamedArgs(values)
}

// RegisterView registers an Arrow record reader as a view with the given name in DuckDB.
// The returned release function must be called to release the memory once the view is no longer needed.
func (a *Arrow) RegisterView(reader array.RecordReader, name string) (release func(), err error) {
	if a.c.closed {
		return nil, errClosedCon
	}

	// duckdb_state duckdb_arrow_scan(duckdb_connection connection, const char *table_name, duckdb_arrow_stream arrow);

	stream := ( /*line :260:12*/_Cfunc_calloc /*line :260:19*/)(1, ( /*line :260:24*/_Ciconst_sizeof_struct_ArrowArrayStream /*line :260:55*/))
	release = func() {
		func() { _cgo0 := /*line :262:10*/stream; _cgoCheckPointer(_cgo0, nil); /*line :262:17*/_Cfunc_free(_cgo0); }()
	}
	cdata.ExportRecordReader(reader, (*cdata.CArrowArrayStream)(stream))

	cName := ( /*line :266:11*/_Cfunc_CString /*line :266:19*/)(name)
	defer func() func() { _cgo0 := /*line :267:15*/unsafe.Pointer(cName); return func() { _cgoCheckPointer(_cgo0, nil); /*line :267:37*/_Cfunc_free(_cgo0); }}()()

	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :270:3*/a.c.duckdbCon; var _cgo1 *_Ctype_char = /*line :271:3*/cName; _cgo2 := /*line :272:3*/(_Ctype_duckdb_arrow_stream /*line :272:25*/)(stream); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo2, nil); return /*line :273:3*/_Cfunc_duckdb_arrow_scan(_cgo0, _cgo1, _cgo2); }(); state == ( /*line :273:14*/_Ciconst_DuckDBError /*line :273:26*/) {
		release()
		return nil, errors.New("duckdb_arrow_scan")
	}

	return release, nil
}
