// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/profiling.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"database/sql"
	"unsafe"
)

// ProfilingInfo is a recursive type containing metrics for each node in DuckDB's query plan.
// There are two types of nodes: the QUERY_ROOT and OPERATOR nodes.
// The QUERY_ROOT refers exclusively to the top-level node; its metrics are measured over the entire query.
// The OPERATOR nodes refer to the individual operators in the query plan.
type ProfilingInfo struct {
	// Metrics contains all key-value pairs of the current node.
	// The key represents the name and corresponds to the measured value.
	Metrics map[string]string
	// Children contains all children of the node and their respective metrics.
	Children []ProfilingInfo
}

// GetProfilingInfo obtains all available metrics set by the current connection.
func GetProfilingInfo(c *sql.Conn) (ProfilingInfo, error) {
	info := ProfilingInfo{}
	err := c.Raw(func(driverConn any) error {
		con := driverConn.(*conn)
		duckdbInfo := func() _Ctype_duckdb_profiling_info{ _cgo0 := /*line :30:45*/con.duckdbCon; _cgoCheckPointer(_cgo0, nil); return /*line :30:59*/_Cfunc_duckdb_get_profiling_info(_cgo0); }()
		if duckdbInfo == nil {
			return getError(errProfilingInfoEmpty, nil)
		}

		// Recursive tree traversal.
		info.getMetrics(duckdbInfo)
		return nil
	})
	return info, err
}

func (info *ProfilingInfo) getMetrics(duckdbInfo  /*line :42:50*/_Ctype_duckdb_profiling_info /*line :42:73*/) {
	m := func() _Ctype_duckdb_value{ _cgo0 := /*line :43:43*/duckdbInfo; _cgoCheckPointer(_cgo0, nil); return /*line :43:54*/_Cfunc_duckdb_profiling_info_get_metrics(_cgo0); }()
	count := func() _Ctype_idx_t{ _cgo0 := /*line :44:33*/m; _cgoCheckPointer(_cgo0, nil); return /*line :44:35*/_Cfunc_duckdb_get_map_size(_cgo0); }()
	info.Metrics = make(map[string]string, count)

	for i :=  /*line :47:11*/_Ctype_idx_t /*line :47:18*/(0); i < count; i++ {
		key := func() _Ctype_duckdb_value{ _cgo0 := /*line :48:31*/m; var _cgo1 _Ctype_idx_t = /*line :48:34*/i; _cgoCheckPointer(_cgo0, nil); return /*line :48:36*/_Cfunc_duckdb_get_map_key(_cgo0, _cgo1); }()
		value := func() _Ctype_duckdb_value{ _cgo0 := /*line :49:35*/m; var _cgo1 _Ctype_idx_t = /*line :49:38*/i; _cgoCheckPointer(_cgo0, nil); return /*line :49:40*/_Cfunc_duckdb_get_map_value(_cgo0, _cgo1); }()

		cKey := func() *_Ctype_char{ _cgo0 := /*line :51:32*/key; _cgoCheckPointer(_cgo0, nil); return /*line :51:36*/_Cfunc_duckdb_get_varchar(_cgo0); }()
		cValue := func() *_Ctype_char{ _cgo0 := /*line :52:34*/value; _cgoCheckPointer(_cgo0, nil); return /*line :52:40*/_Cfunc_duckdb_get_varchar(_cgo0); }()
		keyStr := ( /*line :53:13*/_Cfunc_GoString /*line :53:22*/)(cKey)
		valueStr := ( /*line :54:15*/_Cfunc_GoString /*line :54:24*/)(cValue)

		info.Metrics[keyStr] = valueStr

		func() { _cgoBase0 := /*line :58:26*/&key; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :58:31*/_Cfunc_duckdb_destroy_value(_cgo0); }()
		func() { _cgoBase0 := /*line :59:26*/&value; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :59:33*/_Cfunc_duckdb_destroy_value(_cgo0); }()
		func() { _cgo0 := /*line :60:17*/unsafe.Pointer(cKey); _cgoCheckPointer(_cgo0, nil); /*line :60:38*/_Cfunc_duckdb_free(_cgo0); }()
		func() { _cgo0 := /*line :61:17*/unsafe.Pointer(cValue); _cgoCheckPointer(_cgo0, nil); /*line :61:40*/_Cfunc_duckdb_free(_cgo0); }()
	}
	func() { _cgoBase0 := /*line :63:25*/&m; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :63:28*/_Cfunc_duckdb_destroy_value(_cgo0); }()

	childCount := func() _Ctype_idx_t{ _cgo0 := /*line :65:56*/duckdbInfo; _cgoCheckPointer(_cgo0, nil); return /*line :65:67*/_Cfunc_duckdb_profiling_info_get_child_count(_cgo0); }()
	for i :=  /*line :66:11*/_Ctype_idx_t /*line :66:18*/(0); i < childCount; i++ {
		duckdbChildInfo := func() _Ctype_duckdb_profiling_info{ _cgo0 := /*line :67:56*/duckdbInfo; var _cgo1 _Ctype_idx_t = /*line :67:68*/i; _cgoCheckPointer(_cgo0, nil); return /*line :67:70*/_Cfunc_duckdb_profiling_info_get_child(_cgo0, _cgo1); }()
		childInfo := ProfilingInfo{}
		childInfo.getMetrics(duckdbChildInfo)
		info.Children = append(info.Children, childInfo)
	}
}
