// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/statement.go:1:1
package duckdb; import _cgo_unsafe "unsafe"

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math/big"
	"time"
	"unsafe"
)

type stmt struct {
	c                *conn
	stmt             * /*line :20:20*/_Ctype_duckdb_prepared_statement /*line :20:47*/
	closeOnRowsClose bool
	closed           bool
	rows             bool
}

func (s *stmt) Close() error {
	if s.rows {
		panic("database/sql/driver: misuse of duckdb driver: Close with active Rows")
	}
	if s.closed {
		panic("database/sql/driver: misuse of duckdb driver: double Close of Stmt")
	}

	s.closed = true
	func() { _cgo0 := /*line :35:27*/s.stmt; _cgoCheckPointer(_cgo0, nil); /*line :35:34*/_Cfunc_duckdb_destroy_prepare(_cgo0); }()
	return nil
}

func (s *stmt) NumInput() int {
	if s.closed {
		panic("database/sql/driver: misuse of duckdb driver: NumInput after Close")
	}
	paramCount := func() _Ctype_idx_t{ _cgo0 := /*line :43:33*/*s.stmt; _cgoCheckPointer(_cgo0, nil); return /*line :43:41*/_Cfunc_duckdb_nparams(_cgo0); }()
	return int(paramCount)
}

func (s *stmt) bind(args []driver.NamedValue) error {
	if s.NumInput() > len(args) {
		return fmt.Errorf("incorrect argument count for command: have %d want %d", len(args), s.NumInput())
	}

	// FIXME (feature): we can't pass nested types as parameters (bind_value) yet

	// relaxed length check allow for unused parameters.
	for i := 0; i < s.NumInput(); i++ {
		name := func() *_Ctype_char{ _cgo0 := /*line :56:35*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :56:51*/(i + 1); _cgoCheckPointer(_cgo0, nil); return /*line :56:57*/_Cfunc_duckdb_parameter_name(_cgo0, _cgo1); }()
		paramName := ( /*line :57:16*/_Cfunc_GoString /*line :57:25*/)(name)
		func() { _cgo0 := /*line :58:17*/unsafe.Pointer(name); _cgoCheckPointer(_cgo0, nil); /*line :58:38*/_Cfunc_duckdb_free(_cgo0); }()

		// fallback on index position
		arg := args[i]

		// override with ordinal if set
		for _, v := range args {
			if v.Ordinal == i+1 {
				arg = v
			}
		}

		// override with name if set
		for _, v := range args {
			if v.Name == paramName {
				arg = v
			}
		}

		switch v := arg.Value.(type) {
		case bool:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :79:35*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :79:51*/(i + 1); var _cgo2 _Ctype__Bool = _Ctype_bool /*line :79:64*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :79:68*/_Cfunc_duckdb_bind_boolean(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :79:76*/_Ciconst_DuckDBError /*line :79:88*/) {
				return errCouldNotBind
			}
		case int8:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :83:32*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :83:48*/(i + 1); var _cgo2 _Ctype_int8_t = _Ctype_int8_t /*line :83:63*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :83:67*/_Cfunc_duckdb_bind_int8(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :83:75*/_Ciconst_DuckDBError /*line :83:87*/) {
				return errCouldNotBind
			}
		case int16:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :87:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :87:49*/(i + 1); var _cgo2 _Ctype_int16_t = _Ctype_int16_t /*line :87:65*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :87:69*/_Cfunc_duckdb_bind_int16(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :87:77*/_Ciconst_DuckDBError /*line :87:89*/) {
				return errCouldNotBind
			}
		case int32:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :91:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :91:49*/(i + 1); var _cgo2 _Ctype_int32_t = _Ctype_int32_t /*line :91:65*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :91:69*/_Cfunc_duckdb_bind_int32(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :91:77*/_Ciconst_DuckDBError /*line :91:89*/) {
				return errCouldNotBind
			}
		case int64:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :95:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :95:49*/(i + 1); var _cgo2 _Ctype_int64_t = _Ctype_int64_t /*line :95:65*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :95:69*/_Cfunc_duckdb_bind_int64(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :95:77*/_Ciconst_DuckDBError /*line :95:89*/) {
				return errCouldNotBind
			}
		case int:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :99:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :99:49*/(i + 1); var _cgo2 _Ctype_int64_t = _Ctype_int64_t /*line :99:65*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :99:69*/_Cfunc_duckdb_bind_int64(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :99:77*/_Ciconst_DuckDBError /*line :99:89*/) {
				return errCouldNotBind
			}
		case *big.Int:
			val, err := hugeIntFromNative(v)
			if err != nil {
				return err
			}
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :107:35*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :107:51*/(i + 1); var _cgo2 _Ctype_struct___2 = /*line :107:58*/val; _cgoCheckPointer(_cgo0, nil); return /*line :107:62*/_Cfunc_duckdb_bind_hugeint(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :107:70*/_Ciconst_DuckDBError /*line :107:82*/) {
				return errCouldNotBind
			}
		case uint8:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :111:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :111:49*/(i + 1); var _cgo2 _Ctype_uint8_t = _Ctype_uchar /*line :111:63*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :111:67*/_Cfunc_duckdb_bind_uint8(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :111:75*/_Ciconst_DuckDBError /*line :111:87*/) {
				return errCouldNotBind
			}
		case uint16:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :115:34*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :115:50*/(i + 1); var _cgo2 _Ctype_uint16_t = _Ctype_uint16_t /*line :115:67*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :115:71*/_Cfunc_duckdb_bind_uint16(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :115:79*/_Ciconst_DuckDBError /*line :115:91*/) {
				return errCouldNotBind
			}
		case uint32:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :119:34*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :119:50*/(i + 1); var _cgo2 _Ctype_uint32_t = _Ctype_uint32_t /*line :119:67*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :119:71*/_Cfunc_duckdb_bind_uint32(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :119:79*/_Ciconst_DuckDBError /*line :119:91*/) {
				return errCouldNotBind
			}
		case uint64:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :123:34*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :123:50*/(i + 1); var _cgo2 _Ctype_uint64_t = _Ctype_uint64_t /*line :123:67*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :123:71*/_Cfunc_duckdb_bind_uint64(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :123:79*/_Ciconst_DuckDBError /*line :123:91*/) {
				return errCouldNotBind
			}
		case float32:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :127:33*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :127:49*/(i + 1); var _cgo2 _Ctype_float = _Ctype_float /*line :127:63*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :127:67*/_Cfunc_duckdb_bind_float(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :127:75*/_Ciconst_DuckDBError /*line :127:87*/) {
				return errCouldNotBind
			}
		case float64:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :131:34*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :131:50*/(i + 1); var _cgo2 _Ctype_double = _Ctype_double /*line :131:65*/(v); _cgoCheckPointer(_cgo0, nil); return /*line :131:69*/_Cfunc_duckdb_bind_double(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :131:77*/_Ciconst_DuckDBError /*line :131:89*/) {
				return errCouldNotBind
			}
		case string:
			val := ( /*line :135:11*/_Cfunc_CString /*line :135:19*/)(v)
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :136:35*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :136:51*/(i + 1); var _cgo2 *_Ctype_char = /*line :136:58*/val; _cgoCheckPointer(_cgo0, nil); return /*line :136:62*/_Cfunc_duckdb_bind_varchar(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :136:70*/_Ciconst_DuckDBError /*line :136:82*/) {
				func() { _cgo0 := /*line :137:19*/unsafe.Pointer(val); _cgoCheckPointer(_cgo0, nil); /*line :137:39*/_Cfunc_duckdb_free(_cgo0); }()
				return errCouldNotBind
			}
			func() { _cgo0 := /*line :140:18*/unsafe.Pointer(val); _cgoCheckPointer(_cgo0, nil); /*line :140:38*/_Cfunc_duckdb_free(_cgo0); }()
		case []byte:
			val := func() _cgo_unsafe.Pointer{ _cgo0 := /*line :142:20*/v; _cgoCheckPointer(_cgo0, nil); return /*line :142:22*/_Cfunc_CBytes(_cgo0); }()
			l := len(v)
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :144:32*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :144:48*/(i + 1); _cgo2 := /*line :144:55*/val; var _cgo3 _Ctype_idx_t = _Ctype_uint64_t /*line :144:70*/(l); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo2, nil); return /*line :144:74*/_Cfunc_duckdb_bind_blob(_cgo0, _cgo1, _cgo2, _cgo3); }(); rv == ( /*line :144:82*/_Ciconst_DuckDBError /*line :144:94*/) {
				func() { _cgo0 := /*line :145:19*/unsafe.Pointer(val); _cgoCheckPointer(_cgo0, nil); /*line :145:39*/_Cfunc_duckdb_free(_cgo0); }()
				return errCouldNotBind
			}
			func() { _cgo0 := /*line :148:18*/unsafe.Pointer(val); _cgoCheckPointer(_cgo0, nil); /*line :148:38*/_Cfunc_duckdb_free(_cgo0); }()
		case time.Time:
			val :=  /*line :150:11*/_Ctype_duckdb_timestamp /*line :150:29*/{
				micros:  /*line :151:13*/_Ctype_int64_t /*line :151:22*/(v.UTC().UnixMicro()),
			}
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :153:37*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :153:53*/(i + 1); var _cgo2 _Ctype_struct___4 = /*line :153:60*/val; _cgoCheckPointer(_cgo0, nil); return /*line :153:64*/_Cfunc_duckdb_bind_timestamp(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :153:72*/_Ciconst_DuckDBError /*line :153:84*/) {
				return errCouldNotBind
			}
		case Interval:
			val :=  /*line :157:11*/_Ctype_duckdb_interval /*line :157:28*/{
				months:  /*line :158:13*/_Ctype_int32_t /*line :158:22*/(v.Months),
				days:    /*line :159:13*/_Ctype_int32_t /*line :159:22*/(v.Days),
				micros:  /*line :160:13*/_Ctype_int64_t /*line :160:22*/(v.Micros),
			}
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :162:36*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :162:52*/(i + 1); var _cgo2 _Ctype_struct___3 = /*line :162:59*/val; _cgoCheckPointer(_cgo0, nil); return /*line :162:63*/_Cfunc_duckdb_bind_interval(_cgo0, _cgo1, _cgo2); }(); rv == ( /*line :162:71*/_Ciconst_DuckDBError /*line :162:83*/) {
				return errCouldNotBind
			}
		case nil:
			if rv := func() _Ctype_duckdb_state{ _cgo0 := /*line :166:32*/*s.stmt; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :166:48*/(i + 1); _cgoCheckPointer(_cgo0, nil); return /*line :166:54*/_Cfunc_duckdb_bind_null(_cgo0, _cgo1); }(); rv == ( /*line :166:62*/_Ciconst_DuckDBError /*line :166:74*/) {
				return errCouldNotBind
			}
		default:
			return driver.ErrSkip
		}
	}

	return nil
}

// Deprecated: Use ExecContext instead.
func (s *stmt) Exec(args []driver.Value) (driver.Result, error) {
	return s.ExecContext(context.Background(), argsToNamedArgs(args))
}

func (s *stmt) ExecContext(ctx context.Context, nargs []driver.NamedValue) (driver.Result, error) {
	res, err := s.execute(ctx, nargs)
	if err != nil {
		return nil, err
	}
	defer func() func() { _cgo0 := /*line :187:32*/res; return func() { _cgoCheckPointer(_cgo0, nil); /*line :187:36*/_Cfunc_duckdb_destroy_result(_cgo0); }}()()

	ra := int64(func() _Ctype_int64_t{ _cgo0 := /*line :189:35*/res; var _cgo1 _Ctype_idx_t = /*line :189:40*/0; var _cgo2 _Ctype_idx_t = /*line :189:43*/0; _cgoCheckPointer(_cgo0, nil); return /*line :189:45*/_Cfunc_duckdb_value_int64(_cgo0, _cgo1, _cgo2); }())
	return &result{ra}, nil
}

// Deprecated: Use QueryContext instead.
func (s *stmt) Query(args []driver.Value) (driver.Rows, error) {
	return s.QueryContext(context.Background(), argsToNamedArgs(args))
}

func (s *stmt) QueryContext(ctx context.Context, nargs []driver.NamedValue) (driver.Rows, error) {
	res, err := s.execute(ctx, nargs)
	if err != nil {
		return nil, err
	}
	s.rows = true
	return newRowsWithStmt(*res, s), nil
}

// This method executes the query in steps and checks if context is cancelled before executing each step.
// It uses Pending Result Interface C APIs to achieve this. Reference - https://duckdb.org/docs/api/c/api#pending-result-interface
func (s *stmt) execute(ctx context.Context, args []driver.NamedValue) (* /*line :209:73*/_Ctype_duckdb_result /*line :209:88*/, error) {
	if s.closed {
		panic("database/sql/driver: misuse of duckdb driver: ExecContext or QueryContext after Close")
	}
	if s.rows {
		panic("database/sql/driver: misuse of duckdb driver: ExecContext or QueryContext with active Rows")
	}

	if err := s.bind(args); err != nil {
		return nil, err
	}

	var pendingRes  /*line :221:17*/_Ctype_duckdb_pending_result /*line :221:40*/
	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :222:40*/*s.stmt; _cgoBase1 := /*line :222:49*/&pendingRes; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :222:61*/_Cfunc_duckdb_pending_prepared(_cgo0, _cgo1); }(); state == ( /*line :222:72*/_Ciconst_DuckDBError /*line :222:84*/) {
		dbErr := getDuckDBError(( /*line :223:27*/_Cfunc_GoString /*line :223:36*/)(func() *_Ctype_char{ _cgo0 := /*line :223:61*/pendingRes; _cgoCheckPointer(_cgo0, nil); return /*line :223:72*/_Cfunc_duckdb_pending_error(_cgo0); }()))
		func() { _cgoBase0 := /*line :224:28*/&pendingRes; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :224:40*/_Cfunc_duckdb_destroy_pending(_cgo0); }()
		return nil, dbErr
	}
	defer func() func() { _cgoBase0 := /*line :227:33*/&pendingRes; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :227:45*/_Cfunc_duckdb_destroy_pending(_cgo0); }}()()

	mainDoneCh := make(chan struct{})
	bgDoneCh := make(chan struct{})
	go func() {
		select {
		case <-ctx.Done():
			func() { _cgo0 := /*line :234:23*/s.c.duckdbCon; _cgoCheckPointer(_cgo0, nil); /*line :234:37*/_Cfunc_duckdb_interrupt(_cgo0); }()
			close(bgDoneCh)
			return
		case <-mainDoneCh:
			close(bgDoneCh)
			return
		}
	}()

	var res  /*line :243:10*/_Ctype_duckdb_result /*line :243:25*/
	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :244:36*/pendingRes; _cgoBase1 := /*line :244:48*/&res; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :244:53*/_Cfunc_duckdb_execute_pending(_cgo0, _cgo1); }()
	close(mainDoneCh)
	// also wait for background goroutine to finish
	// sometimes the bg goroutine is not scheduled immediately and by that time if another query is running on this connection
	// it can cancel that query so need to wait for it to finish as well
	<-bgDoneCh
	if state == ( /*line :250:14*/_Ciconst_DuckDBError /*line :250:26*/) {
		if ctx.Err() != nil {
			func() { _cgoBase0 := /*line :252:28*/&res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :252:33*/_Cfunc_duckdb_destroy_result(_cgo0); }()
			return nil, ctx.Err()
		}

		err := getDuckDBError(( /*line :256:25*/_Cfunc_GoString /*line :256:34*/)(func() *_Ctype_char{ _cgoBase0 := /*line :256:58*/&res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :256:63*/_Cfunc_duckdb_result_error(_cgo0); }()))
		func() { _cgoBase0 := /*line :257:27*/&res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :257:32*/_Cfunc_duckdb_destroy_result(_cgo0); }()
		return nil, err
	}

	return &res, nil
}

func argsToNamedArgs(values []driver.Value) []driver.NamedValue {
	args := make([]driver.NamedValue, len(values))
	for n, param := range values {
		args[n].Value = param
		args[n].Ordinal = n + 1
	}
	return args
}

var errCouldNotBind = errors.New("could not bind parameter")
