// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/vector_getters.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"math/big"
	"time"
	"unsafe"
)

// fnGetVectorValue is the getter callback function for any (nested) vector.
type fnGetVectorValue func(vec *vector, rowIdx  /*line :15:48*/_Ctype_idx_t /*line :15:55*/) any

func (vec *vector) getNull(rowIdx  /*line :17:35*/_Ctype_idx_t /*line :17:42*/) bool {
	mask := unsafe.Pointer(vec.mask)
	if mask == nil {
		return false
	}

	entryIdx := rowIdx / 64
	idxInEntry := rowIdx % 64
	maskPtr := (*[1 << 31] /*line :25:24*/_Ctype_uint64_t /*line :25:34*/)(mask)
	isValid := maskPtr[entryIdx] & ( /*line :26:34*/_Ctype_uint64_t /*line :26:44*/(1) << idxInEntry)
	return uint64(isValid) == 0
}

func getPrimitive[T any](vec *vector, rowIdx  /*line :30:46*/_Ctype_idx_t /*line :30:53*/) T {
	xs := (*[1 << 31]T)(vec.ptr)
	return xs[rowIdx]
}

func (vec *vector) getTS(t Type, rowIdx  /*line :35:41*/_Ctype_idx_t /*line :35:48*/) time.Time {
	val := getPrimitive[ /*line :36:22*/_Ctype_duckdb_timestamp /*line :36:40*/](vec, rowIdx)
	return getTS(t, val)
}

func getTS(t Type, ts  /*line :40:23*/_Ctype_duckdb_timestamp /*line :40:41*/) time.Time {
	switch t {
	case TYPE_TIMESTAMP:
		return time.UnixMicro(int64(ts.micros)).UTC()
	case TYPE_TIMESTAMP_S:
		return time.Unix(int64(ts.micros), 0).UTC()
	case TYPE_TIMESTAMP_MS:
		return time.UnixMilli(int64(ts.micros)).UTC()
	case TYPE_TIMESTAMP_NS:
		return time.Unix(0, int64(ts.micros)).UTC()
	case TYPE_TIMESTAMP_TZ:
		return time.UnixMicro(int64(ts.micros)).UTC()
	}
	return time.Time{}
}

func (vec *vector) getDate(rowIdx  /*line :56:35*/_Ctype_idx_t /*line :56:42*/) time.Time {
	date := getPrimitive[ /*line :57:23*/_Ctype_duckdb_date /*line :57:36*/](vec, rowIdx)
	return getDate(date)
}

func getDate(date  /*line :61:19*/_Ctype_duckdb_date /*line :61:32*/) time.Time {
	d := ( /*line :62:7*/_Cfunc_duckdb_from_date /*line :62:24*/)(date)
	return time.Date(int(d.year), time.Month(d.month), int(d.day), 0, 0, 0, 0, time.UTC)
}

func (vec *vector) getTime(rowIdx  /*line :66:35*/_Ctype_idx_t /*line :66:42*/) time.Time {
	switch vec.Type {
	case TYPE_TIME:
		val := getPrimitive[ /*line :69:23*/_Ctype_duckdb_time /*line :69:36*/](vec, rowIdx)
		return getTime(val)
	case TYPE_TIME_TZ:
		ti := getPrimitive[ /*line :72:22*/_Ctype_duckdb_time_tz /*line :72:38*/](vec, rowIdx)
		return getTimeTZ(ti)
	}
	return time.Time{}
}

func getTime(ti  /*line :78:17*/_Ctype_duckdb_time /*line :78:30*/) time.Time {
	unix := time.UnixMicro(int64(ti.micros)).UTC()
	return time.Date(1, time.January, 1, unix.Hour(), unix.Minute(), unix.Second(), unix.Nanosecond(), time.UTC)
}

func getTimeTZ(ti  /*line :83:19*/_Ctype_duckdb_time_tz /*line :83:35*/) time.Time {
	timeTZ := ( /*line :84:12*/_Cfunc_duckdb_from_time_tz /*line :84:32*/)(ti)
	hour := int(timeTZ.time.hour)
	minute := int(timeTZ.time.min)
	sec := int(timeTZ.time.sec)
	// TIMETZ has microsecond precision.
	nanos := int(timeTZ.time.micros) * 1000
	loc := time.FixedZone("", int(timeTZ.offset))
	return time.Date(1, time.January, 1, hour, minute, sec, nanos, loc).UTC()
}

func (vec *vector) getInterval(rowIdx  /*line :94:39*/_Ctype_idx_t /*line :94:46*/) Interval {
	interval := getPrimitive[ /*line :95:27*/_Ctype_duckdb_interval /*line :95:44*/](vec, rowIdx)
	return getInterval(interval)
}

func getInterval(interval  /*line :99:27*/_Ctype_duckdb_interval /*line :99:44*/) Interval {
	return Interval{
		Days:   int32(interval.days),
		Months: int32(interval.months),
		Micros: int64(interval.micros),
	}
}

func (vec *vector) getHugeint(rowIdx  /*line :107:38*/_Ctype_idx_t /*line :107:45*/) *big.Int {
	hugeInt := getPrimitive[ /*line :108:26*/_Ctype_duckdb_hugeint /*line :108:42*/](vec, rowIdx)
	return hugeIntToNative(hugeInt)
}

func (vec *vector) getCString(rowIdx  /*line :112:38*/_Ctype_idx_t /*line :112:45*/) any {
	cStr := getPrimitive[duckdb_string_t](vec, rowIdx)

	var blob []byte
	if cStr.length <= stringInlineLength {
		// Inlined data is stored from byte 4 to stringInlineLength + 4.
		blob = func() []byte{ _cgoBase0 := /*line :118:35*/&cStr.prefix; _cgo0 := /*line :118:20*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = _Ctype_int /*line :118:55*/(cStr.length); _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :118:69*/_Cfunc_GoBytes(_cgo0, _cgo1); }()
	} else {
		// Any strings exceeding stringInlineLength are stored as a pointer in `ptr`.
		blob = func() []byte{ _cgo0 := /*line :121:20*/unsafe.Pointer(cStr.ptr); var _cgo1 _Ctype_int = _Ctype_int /*line :121:51*/(cStr.length); _cgoCheckPointer(_cgo0, nil); return /*line :121:65*/_Cfunc_GoBytes(_cgo0, _cgo1); }()
	}

	if vec.Type == TYPE_VARCHAR {
		return string(blob)
	}
	return blob
}

func (vec *vector) getDecimal(rowIdx  /*line :130:38*/_Ctype_idx_t /*line :130:45*/) Decimal {
	var val *big.Int
	switch vec.internalType {
	case TYPE_SMALLINT:
		v := getPrimitive[int16](vec, rowIdx)
		val = big.NewInt(int64(v))
	case TYPE_INTEGER:
		v := getPrimitive[int32](vec, rowIdx)
		val = big.NewInt(int64(v))
	case TYPE_BIGINT:
		v := getPrimitive[int64](vec, rowIdx)
		val = big.NewInt(v)
	case TYPE_HUGEINT:
		v := getPrimitive[ /*line :143:21*/_Ctype_duckdb_hugeint /*line :143:37*/](vec, rowIdx)
		val = hugeIntToNative( /*line :144:25*/_Ctype_duckdb_hugeint /*line :144:41*/{
			lower: v.lower,
			upper: v.upper,
		})
	}

	return Decimal{Width: vec.decimalWidth, Scale: vec.decimalScale, Value: val}
}

func (vec *vector) getEnum(rowIdx  /*line :153:35*/_Ctype_idx_t /*line :153:42*/) string {
	var idx uint64
	switch vec.internalType {
	case TYPE_UTINYINT:
		idx = uint64(getPrimitive[uint8](vec, rowIdx))
	case TYPE_USMALLINT:
		idx = uint64(getPrimitive[uint16](vec, rowIdx))
	case TYPE_UINTEGER:
		idx = uint64(getPrimitive[uint32](vec, rowIdx))
	case TYPE_UBIGINT:
		idx = getPrimitive[uint64](vec, rowIdx)
	}

	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :166:49*/vec.duckdbVector; _cgoCheckPointer(_cgo0, nil); return /*line :166:66*/_Cfunc_duckdb_vector_get_column_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :167:38*/&logicalType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :167:51*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	val := func() *_Ctype_char{ _cgo0 := /*line :169:40*/logicalType; var _cgo1 _Ctype_idx_t = /*line :169:53*/(_Ctype_idx_t /*line :169:61*/)(idx); _cgoCheckPointer(_cgo0, nil); return /*line :169:68*/_Cfunc_duckdb_enum_dictionary_value(_cgo0, _cgo1); }()
	defer func() func() { _cgo0 := /*line :170:22*/unsafe.Pointer(val); return func() { _cgoCheckPointer(_cgo0, nil); /*line :170:42*/_Cfunc_duckdb_free(_cgo0); }}()()
	return ( /*line :171:9*/_Cfunc_GoString /*line :171:18*/)(val)
}

func (vec *vector) getList(rowIdx  /*line :174:35*/_Ctype_idx_t /*line :174:42*/) []any {
	entry := getPrimitive[duckdb_list_entry_t](vec, rowIdx)
	slice := make([]any, 0, entry.length)
	child := &vec.childVectors[0]

	// Fill the slice with all child values.
	for i :=  /*line :180:11*/_Ctype_idx_t /*line :180:18*/(0); i < entry.length; i++ {
		val := child.getFn(child, i+entry.offset)
		slice = append(slice, val)
	}
	return slice
}

func (vec *vector) getStruct(rowIdx  /*line :187:37*/_Ctype_idx_t /*line :187:44*/) map[string]any {
	m := map[string]any{}
	for i := 0; i < len(vec.childVectors); i++ {
		child := &vec.childVectors[i]
		val := child.getFn(child, rowIdx)
		m[vec.structEntries[i].Name()] = val
	}
	return m
}

func (vec *vector) getMap(rowIdx  /*line :197:34*/_Ctype_idx_t /*line :197:41*/) Map {
	list := vec.getList(rowIdx)

	m := Map{}
	for i := 0; i < len(list); i++ {
		mapItem := list[i].(map[string]any)
		key := mapItem[mapKeysField()]
		val := mapItem[mapValuesField()]
		m[key] = val
	}
	return m
}
