// Slice-1 AWS connector wizard, hardcoded client-side.
//
// This is the TypeScript mirror of internal/discovery/wizard.AWSWizard().
// Both definitions exist because the React shell can render the wizard
// without a round-trip to the server, and the Go layer keeps a
// canonical definition so future provider integrations (GCP, Azure)
// and server-side rendering can grow from the same source.
//
// Known trade-off: keeping two definitions risks drift. The Go-side
// tests assert step count + required fields; the TypeScript-side
// tests in ConnectorWizard.test.tsx assert the same shape against
// this constant. A future slice should add a /api/v1/discovery/wizard
// endpoint and switch the shell to fetch the wizard, removing this
// file. Documented as a known trade-off in the Stream 2D agent
// report.

import type { ConnectorWizard } from "@/api/discovery";

// Trust-policy JSON template. The wizard substitutes
// <PRINCIPAL-PLACEHOLDER> with the principal that will assume the
// SquadronDiscovery role (defaults to arn:aws:iam::<account>:root —
// the AWS-recommended bootstrap shape for self-hosted Squadron) and
// <UUID-PLACEHOLDER> with the per-deployment ExternalId (generated by
// crypto.randomUUID(), or resumed from an operator-supplied value).
//
// The template lives in this file rather than the component so a
// future drift check can compare it against the Go-side template
// without parsing JSX. See renderTrustPolicy() in
// ConnectorWizard.tsx for the substitution logic.
//
// History: pre-v0.87.1 this template hard-coded a placeholder
// principal of arn:aws:iam::SQUADRON_ACCOUNT_ID:role/SquadronDiscovery
// — both a literal that nothing substituted and a circular reference
// (the role can't trust itself). Fixed by #574.
export const AWS_TRUST_POLICY_TEMPLATE = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "<PRINCIPAL-PLACEHOLDER>"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "<UUID-PLACEHOLDER>"
        }
      }
    }
  ]
}`;

// Permissions-policy JSON template. Verbatim from the
// "Permissions policy (slice 1 + slice 2 + slice 3a + slice 3b)"
// section of docs/universal-discovery-design.md. Slice 1 covered
// EC2 + Lambda; slice 2 (v0.87) added RDS; slice 3a (v0.88.0)
// added S3 (5 actions) + ELBv2 / ALB / NLB (3 actions); slice 3b
// (v0.89.0) adds EKS (5 actions) — bringing the total to 22
// read-only actions. No write actions; the principle of least
// privilege is enforced at the policy level so even a fully
// compromised Squadron cannot escalate.
//
// Added by #575 when a real bring-up surfaced that operators were
// reading the design doc to discover this set — the wizard's
// validate step would pass sts:AssumeRole but every probe would
// fail with AccessDenied because no permissions policy was attached.
export const AWS_PERMISSIONS_POLICY_TEMPLATE = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeInstances",
        "ec2:DescribeInstanceStatus",
        "ec2:DescribeRegions",
        "ec2:DescribeTags",
        "lambda:ListFunctions",
        "lambda:GetFunction",
        "lambda:GetFunctionConfiguration",
        "lambda:ListTags",
        "rds:DescribeDBInstances",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "s3:GetBucketLogging",
        "s3:GetBucketTagging",
        "s3:GetBucketRequestPayment",
        "elasticloadbalancing:DescribeLoadBalancers",
        "elasticloadbalancing:DescribeLoadBalancerAttributes",
        "elasticloadbalancing:DescribeTags",
        "eks:ListClusters",
        "eks:DescribeCluster",
        "eks:ListAddons",
        "eks:DescribeAddon",
        "eks:ListNodegroups",
        "eks:ListFargateProfiles"
      ],
      "Resource": "*"
    }
  ]
}`;

// AWS IAM role creation deep-link. Lands the operator on the role
// creation flow itself rather than the IAM home — principle 4 in the
// design doc's eleven-principles section.
export const AWS_IAM_ROLE_CREATE_URL =
  "https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=crossAccount";

export const awsWizard: ConnectorWizard = {
  provider: "aws",
  title: "Connect an AWS account",
  steps: [
    {
      id: "account-id",
      title: "Enter your AWS account ID",
      description:
        "The 12-digit account ID for the AWS account you want Squadron to scan. You can find this in the AWS Console under Account or in any role ARN.",
      action: {
        kind: "fill_field",
        payload: {
          field: "account_id",
          placeholder: "123456789012",
        },
      },
      validation: {
        kind: "regex",
        pattern: "^\\d{12}$",
        message: "Account ID must be exactly 12 digits.",
      },
      doc_link: "https://docs.squadron.example/discovery/aws#account-id",
      recovery_hint:
        "Verify the account ID in your AWS Console. Common typo: confusing the account ID (12 digits) with the access key ID (20 chars).",
    },
    {
      id: "trust-policy",
      title: "Create the IAM role with this trust policy",
      description:
        "Squadron generated a per-deployment ExternalId for you. By default this trust policy lets any IAM identity in your AWS account assume the SquadronDiscovery role, provided that identity has sts:AssumeRole permission and passes the ExternalId — the AWS-recommended bootstrap shape for self-hosted Squadron. Copy the trust policy below verbatim and paste it into the AWS IAM role creation flow. Use the Advanced section to scope to a single IAM identity, or to resume with an ExternalId you already pasted into AWS.",
      action: {
        kind: "copy_value",
        payload: {
          field: "trust_policy",
          language: "json",
        },
      },
      validation: { kind: "none" },
      doc_link: "https://docs.squadron.example/discovery/aws#trust-policy",
      recovery_hint:
        "Re-copy the trust policy from this step — don't edit the JSON. The ExternalId condition is required; removing it makes the role unsafe. If you previously pasted a different ExternalId into AWS, use the Advanced > Resume with existing ExternalId field to match it.",
    },
    {
      id: "permissions-policy",
      title: "Add this permissions policy to the role",
      description:
        "Squadron needs read-only access to EC2, Lambda, RDS, S3, ELBv2 (ALB / NLB), and EKS in your account to discover what's uninstrumented. Copy this policy verbatim and attach it to the SquadronDiscovery role you just created — either as an inline policy or a separate managed policy. Squadron never executes write/modify actions; only the actions in this list are granted.",
      action: {
        kind: "copy_value",
        payload: {
          field: "permissions_policy",
          language: "json",
        },
      },
      validation: { kind: "none" },
      doc_link: "https://docs.squadron.example/discovery/aws#permissions-policy",
      recovery_hint:
        "If the validate step's sts:AssumeRole succeeds but the EC2/Lambda/RDS/S3/ALB/EKS probes return AccessDenied, the permissions policy is missing or scoped wrong. Re-copy the policy from this step.",
    },
    {
      id: "role-arn",
      title: "Paste the role ARN AWS created",
      description:
        "After IAM creates the role, AWS shows you the ARN. Paste it here. Squadron uses this to call sts:AssumeRole against your account.",
      action: {
        kind: "fill_field",
        payload: {
          field: "role_arn",
          placeholder: "arn:aws:iam::123456789012:role/SquadronDiscovery",
        },
      },
      validation: {
        kind: "regex",
        pattern: "^arn:aws:iam::\\d{12}:role\\/[\\w+=,.@-]+$",
        message:
          "Role ARN must look like arn:aws:iam::123456789012:role/RoleName.",
      },
      doc_link: "https://docs.squadron.example/discovery/aws#role-arn",
      recovery_hint:
        "Confirm the ARN you pasted matches the role AWS created. The account ID embedded in the ARN must match the value from Step 1.",
    },
    {
      id: "validate",
      title: "Validate the connection",
      description:
        "Squadron will run sts:AssumeRole and tiny EC2 + Lambda + RDS + S3 + ALB + EKS probes to confirm the role works. No records are created until you click Save on the next step.",
      action: { kind: "test_connection" },
      validation: { kind: "none" },
      doc_link: "https://docs.squadron.example/discovery/aws#validate",
      recovery_hint:
        "If validation fails, the error message names the step to revisit. Re-validate after each fix; no records are created until Save.",
    },
    {
      id: "save",
      title: "Save the connection",
      description:
        "Squadron will encrypt and store the role ARN and ExternalId, run one final validation to catch last-second edits, and emit a discovery.aws.connection_created audit event. The ExternalId never appears in the audit payload.",
      action: { kind: "test_connection" },
      validation: { kind: "none" },
      doc_link: "https://docs.squadron.example/discovery/aws#save",
      recovery_hint:
        "If Save fails after Validate passed, the role was likely edited between steps. Return to the Validate step and re-run.",
    },
  ],
};
