// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/apache/arrow-go/v18@v18.0.0/arrow/cdata/cdata_allocate.go:1:1
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build go1.20 || tinygo

package cdata

// #include <stdlib.h>
// #include "arrow/c/abi.h"
import _ "unsafe"

import (
	"unsafe"
)

func allocateArrowSchemaArr(n int) (out []CArrowSchema) {
	return unsafe.Slice((*CArrowSchema)(( /*line :30:38*/_Cfunc_calloc /*line :30:45*/)( /*line :30:47*/_Ctype_size_t /*line :30:55*/(n),
		( /*line :31:3*/_Ciconst_sizeof_struct_ArrowSchema /*line :31:29*/))), n)
}

func allocateArrowSchemaPtrArr(n int) (out []*CArrowSchema) {
	return unsafe.Slice((**CArrowSchema)(( /*line :35:39*/_Cfunc_calloc /*line :35:46*/)( /*line :35:48*/_Ctype_size_t /*line :35:56*/(n),
		 /*line :36:3*/_Ctype_size_t /*line :36:11*/(unsafe.Sizeof((*CArrowSchema)(nil))))), n)
}

func allocateArrowArrayArr(n int) (out []CArrowArray) {
	return unsafe.Slice((*CArrowArray)(( /*line :40:37*/_Cfunc_calloc /*line :40:44*/)( /*line :40:46*/_Ctype_size_t /*line :40:54*/(n),
		( /*line :41:3*/_Ciconst_sizeof_struct_ArrowArray /*line :41:28*/))), n)
}

func allocateArrowArrayPtrArr(n int) (out []*CArrowArray) {
	return unsafe.Slice((**CArrowArray)(( /*line :45:38*/_Cfunc_calloc /*line :45:45*/)( /*line :45:47*/_Ctype_size_t /*line :45:55*/(n),
		 /*line :46:3*/_Ctype_size_t /*line :46:11*/(unsafe.Sizeof((*CArrowArray)(nil))))), n)
}

func allocateBufferPtrArr(n int) (out []* /*line :49:42*/_Ctype_void /*line :49:48*/) {
	return unsafe.Slice((** /*line :50:25*/_Ctype_void /*line :50:31*/)(( /*line :50:33*/_Cfunc_calloc /*line :50:40*/)( /*line :50:42*/_Ctype_size_t /*line :50:50*/(n),
		 /*line :51:3*/_Ctype_size_t /*line :51:11*/(unsafe.Sizeof((* /*line :51:28*/_Ctype_void /*line :51:34*/)(nil))))), n)
}

func allocateBufferSizeArr(n int) (out [] /*line :54:42*/_Ctype_int64_t /*line :54:51*/) {
	return unsafe.Slice((* /*line :55:24*/_Ctype_int64_t /*line :55:33*/)(( /*line :55:35*/_Cfunc_calloc /*line :55:42*/)( /*line :55:44*/_Ctype_size_t /*line :55:52*/(n),
		( /*line :56:3*/_Ciconst_sizeof_int64_t /*line :56:18*/))), n)
}
