// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/apache/arrow-go/v18@v18.0.0/arrow/cdata/exports.go:1:1
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cdata

import (
	"runtime/cgo"
	"unsafe"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
)

// #include <stdlib.h>
// #include "arrow/c/helpers.h"
//
// typedef const char cchar_t;
// extern int streamGetSchema(struct ArrowArrayStream*, struct ArrowSchema*);
// extern int streamGetNext(struct ArrowArrayStream*, struct ArrowArray*);
// extern const char* streamGetError(struct ArrowArrayStream*);
// extern void streamRelease(struct ArrowArrayStream*);
// // XXX(https://github.com/apache/arrow-adbc/issues/729)
// int streamGetSchemaTrampoline(struct ArrowArrayStream* stream, struct ArrowSchema* out);
// int streamGetNextTrampoline(struct ArrowArrayStream* stream, struct ArrowArray* out);
//
import _ "unsafe"

//export releaseExportedSchema
func releaseExportedSchema(schema *CArrowSchema) {
	if func() _Ctype_int{ _cgo0 := /*line :43:29*/schema; _cgoCheckPointer(_cgo0, nil); return /*line :43:36*/_Cfunc_ArrowSchemaIsReleased(_cgo0); }() == 1 {
		return
	}
	defer func() func() { _cgo0 := /*line :46:34*/schema; return func() { _cgoCheckPointer(_cgo0, nil); /*line :46:41*/_Cfunc_ArrowSchemaMarkReleased(_cgo0); }}()()

	func() { _cgo0 := /*line :48:9*/unsafe.Pointer(schema.name); _cgoCheckPointer(_cgo0, nil); /*line :48:37*/_Cfunc_free(_cgo0); }()
	func() { _cgo0 := /*line :49:9*/unsafe.Pointer(schema.format); _cgoCheckPointer(_cgo0, nil); /*line :49:39*/_Cfunc_free(_cgo0); }()
	func() { _cgo0 := /*line :50:9*/unsafe.Pointer(schema.metadata); _cgoCheckPointer(_cgo0, nil); /*line :50:41*/_Cfunc_free(_cgo0); }()

	if schema.n_children == 0 {
		return
	}

	if schema.dictionary != nil {
		func() { _cgo0 := /*line :57:24*/schema.dictionary; _cgoCheckPointer(_cgo0, nil); /*line :57:42*/_Cfunc_ArrowSchemaRelease(_cgo0); }()
		func() { _cgo0 := /*line :58:10*/unsafe.Pointer(schema.dictionary); _cgoCheckPointer(_cgo0, nil); /*line :58:44*/_Cfunc_free(_cgo0); }()
	}

	children := unsafe.Slice(schema.children, schema.n_children)
	for _, c := range children {
		func() { _cgo0 := /*line :63:24*/c; _cgoCheckPointer(_cgo0, nil); /*line :63:26*/_Cfunc_ArrowSchemaRelease(_cgo0); }()
	}

	func() { _cgo0 := /*line :66:9*/unsafe.Pointer(children[0]); _cgoCheckPointer(_cgo0, nil); /*line :66:37*/_Cfunc_free(_cgo0); }()
	func() { _cgo0 := /*line :67:9*/unsafe.Pointer(schema.children); _cgoCheckPointer(_cgo0, nil); /*line :67:41*/_Cfunc_free(_cgo0); }()
}

// apache/arrow#33864: allocate a new cgo.Handle and store its address
// in a heap-allocated uintptr_t.
func createHandle(hndl cgo.Handle) unsafe.Pointer {
	// uintptr_t* hptr = malloc(sizeof(uintptr_t));
	hptr := (* /*line :74:12*/_Ctype_uintptr_t /*line :74:23*/)(( /*line :74:25*/_Cfunc__CMalloc /*line :74:32*/)(( /*line :74:34*/_Ciconst_sizeof_uintptr_t /*line :74:51*/)))
	// *hptr = (uintptr)hndl;
	*hptr =  /*line :76:10*/_Ctype_uintptr_t /*line :76:21*/(uintptr(hndl))
	return unsafe.Pointer(hptr)
}

func getHandle(ptr unsafe.Pointer) cgo.Handle {
	// uintptr_t* hptr = (uintptr_t*)ptr;
	hptr := (* /*line :82:12*/_Ctype_uintptr_t /*line :82:23*/)(ptr)
	return cgo.Handle((uintptr)(*hptr))
}

//export releaseExportedArray
func releaseExportedArray(arr *CArrowArray) {
	if func() _Ctype_int{ _cgo0 := /*line :88:28*/arr; _cgoCheckPointer(_cgo0, nil); return /*line :88:32*/_Cfunc_ArrowArrayIsReleased(_cgo0); }() == 1 {
		return
	}
	defer func() func() { _cgo0 := /*line :91:33*/arr; return func() { _cgoCheckPointer(_cgo0, nil); /*line :91:37*/_Cfunc_ArrowArrayMarkReleased(_cgo0); }}()()

	if arr.n_buffers > 0 {
		func() { _cgo0 := /*line :94:10*/unsafe.Pointer(arr.buffers); _cgoCheckPointer(_cgo0, nil); /*line :94:38*/_Cfunc_free(_cgo0); }()
	}

	if arr.dictionary != nil {
		func() { _cgo0 := /*line :98:23*/arr.dictionary; _cgoCheckPointer(_cgo0, nil); /*line :98:38*/_Cfunc_ArrowArrayRelease(_cgo0); }()
		func() { _cgo0 := /*line :99:10*/unsafe.Pointer(arr.dictionary); _cgoCheckPointer(_cgo0, nil); /*line :99:41*/_Cfunc_free(_cgo0); }()
	}

	if arr.n_children > 0 {
		children := unsafe.Slice(arr.children, arr.n_children)

		for _, c := range children {
			func() { _cgo0 := /*line :106:24*/c; _cgoCheckPointer(_cgo0, nil); /*line :106:26*/_Cfunc_ArrowArrayRelease(_cgo0); }()
		}
		func() { _cgo0 := /*line :108:10*/unsafe.Pointer(children[0]); _cgoCheckPointer(_cgo0, nil); /*line :108:38*/_Cfunc_free(_cgo0); }()
		func() { _cgo0 := /*line :109:10*/unsafe.Pointer(arr.children); _cgoCheckPointer(_cgo0, nil); /*line :109:39*/_Cfunc_free(_cgo0); }()
	}

	h := getHandle(arr.private_data)
	h.Value().(arrow.ArrayData).Release()
	h.Delete()
	func() { _cgo0 := /*line :115:9*/unsafe.Pointer(arr.private_data); _cgoCheckPointer(_cgo0, nil); /*line :115:42*/_Cfunc_free(_cgo0); }()
}

//export streamGetSchema
func streamGetSchema(handle *CArrowArrayStream, out *CArrowSchema)  /*line :119:68*/_Ctype_int /*line :119:73*/ {
	h := getHandle(handle.private_data)
	rdr := h.Value().(cRecordReader)
	return  /*line :122:9*/_Ctype_int /*line :122:14*/(rdr.getSchema(out))
}

//export streamGetNext
func streamGetNext(handle *CArrowArrayStream, out *CArrowArray)  /*line :126:65*/_Ctype_int /*line :126:70*/ {
	h := getHandle(handle.private_data)
	rdr := h.Value().(cRecordReader)
	return  /*line :129:9*/_Ctype_int /*line :129:14*/(rdr.next(out))
}

//export streamGetError
func streamGetError(handle *CArrowArrayStream) * /*line :133:49*/_Ctype_cchar_t /*line :133:58*/ {
	h := getHandle(handle.private_data)
	rdr := h.Value().(cRecordReader)
	return rdr.getLastError()
}

//export streamRelease
func streamRelease(handle *CArrowArrayStream) {
	h := getHandle(handle.private_data)
	h.Value().(cRecordReader).release()
	h.Delete()
	func() { _cgo0 := /*line :144:9*/unsafe.Pointer(handle.private_data); _cgoCheckPointer(_cgo0, nil); /*line :144:45*/_Cfunc_free(_cgo0); }()
	handle.release = nil
	handle.private_data = nil
}

func exportStream(rdr array.RecordReader, out *CArrowArrayStream) {
	out.get_schema = (*[0]byte)(( /*line :150:30*/_Cgo_ptr(_Cfpvar_fp_streamGetSchemaTrampoline) /*line :150:56*/))
	out.get_next = (*[0]byte)(( /*line :151:28*/_Cgo_ptr(_Cfpvar_fp_streamGetNextTrampoline) /*line :151:52*/))
	out.get_last_error = (*[0]byte)(( /*line :152:34*/_Cgo_ptr(_Cfpvar_fp_streamGetError) /*line :152:49*/))
	out.release = (*[0]byte)(( /*line :153:27*/_Cgo_ptr(_Cfpvar_fp_streamRelease) /*line :153:41*/))
	rdr.Retain()
	h := cgo.NewHandle(cRecordReader{rdr: rdr, err: nil})
	out.private_data = createHandle(h)
}
