/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#pragma GCC diagnostic ignored "-Wunaligned-access"
extern void crosscall2(void (*fn)(void *), void *, int, size_t);
extern size_t _cgo_wait_runtime_init_done(void);
extern void _cgo_release_context(size_t);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_b59e10b900ff_replacement_scan_destroy_data(void *);

CGO_NO_SANITIZE_THREAD
void replacement_scan_destroy_data(void* data)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = data;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_replacement_scan_destroy_data, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_replacement_scan_cb(void *);

CGO_NO_SANITIZE_THREAD
void replacement_scan_cb(duckdb_replacement_scan_info info, cchar_t* table_name, void* data)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_replacement_scan_info p0;
		cchar_t* p1;
		void* p2;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_a.p1 = table_name;
	_cgo_a.p2 = data;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_replacement_scan_cb, &_cgo_a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_scalar_udf_callback(void *);

CGO_NO_SANITIZE_THREAD
void scalar_udf_callback(duckdb_function_info function_info, duckdb_data_chunk input, duckdb_vector output)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_function_info p0;
		duckdb_data_chunk p1;
		duckdb_vector p2;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = function_info;
	_cgo_a.p1 = input;
	_cgo_a.p2 = output;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_scalar_udf_callback, &_cgo_a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_bind_row(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_bind_row(duckdb_bind_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_bind_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_bind_row, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_bind_chunk(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_bind_chunk(duckdb_bind_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_bind_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_bind_chunk, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_bind_parallel_row(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_bind_parallel_row(duckdb_bind_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_bind_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_bind_parallel_row, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_bind_parallel_chunk(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_bind_parallel_chunk(duckdb_bind_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_bind_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_bind_parallel_chunk, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_init(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_init(duckdb_init_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_init_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_init, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_init_parallel(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_init_parallel(duckdb_init_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_init_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_init_parallel, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_local_init(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_local_init(duckdb_init_info info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_init_info p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_local_init, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_row_callback(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_row_callback(duckdb_function_info info, duckdb_data_chunk output)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_function_info p0;
		duckdb_data_chunk p1;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_a.p1 = output;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_row_callback, &_cgo_a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_table_udf_chunk_callback(void *);

CGO_NO_SANITIZE_THREAD
void table_udf_chunk_callback(duckdb_function_info info, duckdb_data_chunk output)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		duckdb_function_info p0;
		duckdb_data_chunk p1;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_a.p1 = output;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_table_udf_chunk_callback, &_cgo_a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_b59e10b900ff_udf_delete_callback(void *);

CGO_NO_SANITIZE_THREAD
void udf_delete_callback(void* info)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = info;
	_cgo_tsan_release();
	crosscall2(_cgoexp_b59e10b900ff_udf_delete_callback, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}

CGO_NO_SANITIZE_THREAD
void _cgo_b59e10b900ff_Cfunc__Cmalloc(void *v) {
	struct {
		unsigned long long p0;
		void *r1;
	} __attribute__((__packed__)) *a = v;
	void *ret;
	_cgo_tsan_acquire();
	ret = malloc(a->p0);
	if (ret == 0 && a->p0 == 0) {
		ret = malloc(1);
	}
	a->r1 = ret;
	_cgo_tsan_release();
}
