/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/marcboeker/go-duckdb */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "replacement_scan.go"

   	#include <duckdb.h>
   	void replacement_scan_cb(duckdb_replacement_scan_info info, const char *table_name, void *data);
   	typedef const char cchar_t;
	void replacement_scan_destroy_data(void *);

#line 1 "cgo-generated-wrapper"

#line 3 "scalarUDF.go"

#include <duckdb.h>

void scalar_udf_callback(duckdb_function_info, duckdb_data_chunk, duckdb_vector);
void udf_delete_callback(void *);

typedef void (*scalar_udf_callback_t)(duckdb_function_info, duckdb_data_chunk, duckdb_vector);

#line 1 "cgo-generated-wrapper"

#line 3 "tableUDF.go"

#include <duckdb.h>

void table_udf_bind_row(duckdb_bind_info info);
void table_udf_bind_chunk(duckdb_bind_info info);
void table_udf_bind_parallel_row(duckdb_bind_info info);
void table_udf_bind_parallel_chunk(duckdb_bind_info info);

void table_udf_init(duckdb_init_info info);
void table_udf_init_parallel(duckdb_init_info info);
void table_udf_local_init(duckdb_init_info info);

// See https://golang.org/issue/19837
void table_udf_row_callback(duckdb_function_info, duckdb_data_chunk);
void table_udf_chunk_callback(duckdb_function_info, duckdb_data_chunk);

// See https://golang.org/issue/19835.
typedef void (*init)(duckdb_function_info);
typedef void (*bind)(duckdb_function_info);
typedef void (*callback)(duckdb_function_info, duckdb_data_chunk);

void udf_delete_callback(void *);

#line 1 "cgo-generated-wrapper"

#line 3 "udf_utils.go"

#include <duckdb.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void replacement_scan_destroy_data(void* data);
extern void replacement_scan_cb(duckdb_replacement_scan_info info, cchar_t* table_name, void* data);
extern void scalar_udf_callback(duckdb_function_info function_info, duckdb_data_chunk input, duckdb_vector output);
extern void table_udf_bind_row(duckdb_bind_info info);
extern void table_udf_bind_chunk(duckdb_bind_info info);
extern void table_udf_bind_parallel_row(duckdb_bind_info info);
extern void table_udf_bind_parallel_chunk(duckdb_bind_info info);
extern void table_udf_init(duckdb_init_info info);
extern void table_udf_init_parallel(duckdb_init_info info);
extern void table_udf_local_init(duckdb_init_info info);
extern void table_udf_row_callback(duckdb_function_info info, duckdb_data_chunk output);
extern void table_udf_chunk_callback(duckdb_function_info info, duckdb_data_chunk output);
extern void udf_delete_callback(void* info);

#ifdef __cplusplus
}
#endif
