// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/abi.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

const (
	stringInlineLength = 12
	stringPrefixLength = 4
)

// refer to convert_vector_list in
// duckdb/tools/juliapkg/src/result.jl
type duckdb_list_entry_t struct {
	offset  /*line :16:9*/_Ctype_idx_t /*line :16:16*/
	length  /*line :17:9*/_Ctype_idx_t /*line :17:16*/
}

// Refer to
// struct string_t
// duckdb/src/include/duckdb/common/types/string_type.hpp
// duckdb/tools/juliapkg/src/ctypes.jl
// duckdb/tools/juliapkg/src/result.jl
type duckdb_string_t struct {
	length int32
	prefix [stringPrefixLength]byte
	ptr    * /*line :28:10*/_Ctype_char /*line :28:16*/
}
