// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/duckdb.go:1:1
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// Package duckdb implements a database/sql driver for the DuckDB database.
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"net/url"
	"strings"
	"unsafe"
)

func init() {
	sql.Register("duckdb", Driver{})
}

type Driver struct{}

func (d Driver) Open(dsn string) (driver.Conn, error) {
	c, err := d.OpenConnector(dsn)
	if err != nil {
		return nil, err
	}
	return c.Connect(context.Background())
}

func (Driver) OpenConnector(dsn string) (driver.Connector, error) {
	return NewConnector(dsn, func(execerContext driver.ExecerContext) error {
		return nil
	})
}

// NewConnector opens a new Connector for a DuckDB database.
// The user must close the Connector, if it is not passed to the sql.OpenDB function.
// Otherwise, sql.DB closes the Connector when calling sql.DB.Close().
func NewConnector(dsn string, connInitFn func(execer driver.ExecerContext) error) (*Connector, error) {
	var db  /*line :46:9*/_Ctype_duckdb_database /*line :46:26*/

	parsedDSN, err := url.Parse(dsn)
	if err != nil {
		return nil, getError(errParseDSN, err)
	}

	config, err := prepareConfig(parsedDSN)
	if err != nil {
		return nil, err
	}
	defer func() func() { _cgoBase0 := /*line :57:32*/&config; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :57:40*/_Cfunc_duckdb_destroy_config(_cgo0); }}()()

	connStr := ( /*line :59:13*/_Cfunc_CString /*line :59:21*/)(getConnString(dsn))
	defer func() func() { _cgo0 := /*line :60:22*/unsafe.Pointer(connStr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :60:46*/_Cfunc_duckdb_free(_cgo0); }}()()

	var outError * /*line :62:16*/_Ctype_char /*line :62:22*/
	defer func() func() { _cgo0 := /*line :63:22*/unsafe.Pointer(outError); return func() { _cgoCheckPointer(_cgo0, nil); /*line :63:47*/_Cfunc_duckdb_free(_cgo0); }}()()

	if state := func() _Ctype_duckdb_state{ var _cgo0 *_Ctype_char = /*line :65:32*/connStr; _cgoBase1 := /*line :65:41*/&db; _cgo1 := _cgoBase1; _cgo2 := /*line :65:46*/config; _cgoBase3 := /*line :65:54*/&outError; _cgo3 := _cgoBase3; _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgo2, nil); _cgoCheckPointer(_cgoBase3, 0 == 0); return /*line :65:64*/_Cfunc_duckdb_open_ext(_cgo0, _cgo1, _cgo2, _cgo3); }(); state == ( /*line :65:75*/_Ciconst_DuckDBError /*line :65:87*/) {
		return nil, getError(errConnect, duckdbError(outError))
	}

	return &Connector{
		db:         db,
		connInitFn: connInitFn,
	}, nil
}

type Connector struct {
	db          /*line :76:13*/_Ctype_duckdb_database /*line :76:30*/
	connInitFn func(execer driver.ExecerContext) error
}

func (*Connector) Driver() driver.Driver {
	return Driver{}
}

func (c *Connector) Connect(context.Context) (driver.Conn, error) {
	var duckdbCon  /*line :85:16*/_Ctype_duckdb_connection /*line :85:35*/
	if state := func() _Ctype_duckdb_state{ _cgo0 := /*line :86:31*/c.db; _cgoBase1 := /*line :86:37*/&duckdbCon; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :86:48*/_Cfunc_duckdb_connect(_cgo0, _cgo1); }(); state == ( /*line :86:59*/_Ciconst_DuckDBError /*line :86:71*/) {
		return nil, getError(errConnect, nil)
	}

	con := &conn{duckdbCon: duckdbCon}

	if c.connInitFn != nil {
		if err := c.connInitFn(con); err != nil {
			return nil, err
		}
	}

	return con, nil
}

func (c *Connector) Close() error {
	func() { _cgoBase0 := /*line :102:17*/&c.db; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :102:23*/_Cfunc_duckdb_close(_cgo0); }()
	c.db = nil
	return nil
}

func getConnString(dsn string) string {
	idx := strings.Index(dsn, "?")
	if idx < 0 {
		idx = len(dsn)
	}
	return dsn[0:idx]
}

func prepareConfig(parsedDSN *url.URL) ( /*line :115:41*/_Ctype_duckdb_config /*line :115:56*/, error) {
	var config  /*line :116:13*/_Ctype_duckdb_config /*line :116:28*/
	if state := func() _Ctype_duckdb_state{ _cgoBase0 := /*line :117:37*/&config; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :117:45*/_Cfunc_duckdb_create_config(_cgo0); }(); state == ( /*line :117:56*/_Ciconst_DuckDBError /*line :117:68*/) {
		func() { _cgoBase0 := /*line :118:27*/&config; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :118:35*/_Cfunc_duckdb_destroy_config(_cgo0); }()
		return nil, getError(errCreateConfig, nil)
	}

	if err := setConfigOption(config, "duckdb_api", "go"); err != nil {
		return nil, err
	}

	// Early-out, if the DSN does not contain configuration options.
	if len(parsedDSN.RawQuery) == 0 {
		return config, nil
	}

	for k, v := range parsedDSN.Query() {
		if len(v) == 0 {
			continue
		}
		if err := setConfigOption(config, k, v[0]); err != nil {
			return nil, err
		}
	}

	return config, nil
}

func setConfigOption(config  /*line :143:29*/_Ctype_duckdb_config /*line :143:44*/, name string, option string) error {
	cName := ( /*line :144:11*/_Cfunc_CString /*line :144:19*/)(name)
	defer func() func() { _cgo0 := /*line :145:22*/unsafe.Pointer(cName); return func() { _cgoCheckPointer(_cgo0, nil); /*line :145:44*/_Cfunc_duckdb_free(_cgo0); }}()()

	cOption := ( /*line :147:13*/_Cfunc_CString /*line :147:21*/)(option)
	defer func() func() { _cgo0 := /*line :148:22*/unsafe.Pointer(cOption); return func() { _cgoCheckPointer(_cgo0, nil); /*line :148:46*/_Cfunc_duckdb_free(_cgo0); }}()()

	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :150:31*/config; var _cgo1 *_Ctype_char = /*line :150:39*/cName; var _cgo2 *_Ctype_char = /*line :150:46*/cOption; _cgoCheckPointer(_cgo0, nil); return /*line :150:54*/_Cfunc_duckdb_set_config(_cgo0, _cgo1, _cgo2); }()
	if state == ( /*line :151:14*/_Ciconst_DuckDBError /*line :151:26*/) {
		func() { _cgoBase0 := /*line :152:27*/&config; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :152:35*/_Cfunc_duckdb_destroy_config(_cgo0); }()
		return getError(errSetConfig, fmt.Errorf("%s=%s", name, option))
	}

	return nil
}
