// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/udf_utils.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"runtime"
	"runtime/cgo"
	"unsafe"
)

// Helpers for passing values to C and back.

type pinnedValue[T any] struct {
	pinner *runtime.Pinner
	value  T
}

type unpinner interface {
	unpin()
}

func (v pinnedValue[T]) unpin() {
	v.pinner.Unpin()
}

func getPinned[T any](handle unsafe.Pointer) T {
	h := *(*cgo.Handle)(handle)
	return h.Value().(pinnedValue[T]).value
}

// Set error helpers.

func setBindError(info  /*line :36:24*/_Ctype_duckdb_bind_info /*line :36:42*/, msg string) {
	err := ( /*line :37:9*/_Cfunc_CString /*line :37:17*/)(msg)
	defer func() func() { _cgo0 := /*line :38:22*/unsafe.Pointer(err); return func() { _cgoCheckPointer(_cgo0, nil); /*line :38:42*/_Cfunc_duckdb_free(_cgo0); }}()()
	func() { _cgo0 := /*line :39:26*/info; var _cgo1 *_Ctype_char = /*line :39:32*/err; _cgoCheckPointer(_cgo0, nil); /*line :39:36*/_Cfunc_duckdb_bind_set_error(_cgo0, _cgo1); }()
}

func setFuncError(function_info  /*line :42:33*/_Ctype_duckdb_function_info /*line :42:55*/, msg string) {
	err := ( /*line :43:9*/_Cfunc_CString /*line :43:17*/)(msg)
	defer func() func() { _cgo0 := /*line :44:22*/unsafe.Pointer(err); return func() { _cgoCheckPointer(_cgo0, nil); /*line :44:42*/_Cfunc_duckdb_free(_cgo0); }}()()
	func() { _cgo0 := /*line :45:37*/function_info; var _cgo1 *_Ctype_char = /*line :45:52*/err; _cgoCheckPointer(_cgo0, nil); /*line :45:56*/_Cfunc_duckdb_scalar_function_set_error(_cgo0, _cgo1); }()
}

// Data deletion handlers.

//export udf_delete_callback
func udf_delete_callback(info unsafe.Pointer) {
	h := (*cgo.Handle)(info)
	h.Value().(unpinner).unpin()
	h.Delete()
}
