// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/vector.go:1:1
package duckdb; import _cgo_unsafe "unsafe"

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"reflect"
	"unsafe"
)

// vector storage of a DuckDB column.
type vector struct {
	// The underlying DuckDB vector.
	duckdbVector  /*line :16:15*/_Ctype_duckdb_vector /*line :16:30*/
	// The underlying data ptr.
	ptr unsafe.Pointer
	// The vector's validity mask.
	mask * /*line :20:8*/_Ctype_uint64_t /*line :20:18*/
	// A callback function to get a value from this vector.
	getFn fnGetVectorValue
	// A callback function to write to this vector.
	setFn fnSetVectorValue
	// The child vectors of nested data types.
	childVectors []vector

	// The vector's type information.
	vectorTypeInfo
}

func (*vector) canNil(val reflect.Value) bool {
	switch val.Kind() {
	case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer,
		reflect.UnsafePointer, reflect.Interface, reflect.Slice:
		return true
	default:
		return false
	}
}

func (vec *vector) init(logicalType  /*line :42:37*/_Ctype_duckdb_logical_type /*line :42:58*/, colIdx int) error {
	t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :43:33*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :43:45*/_Cfunc_duckdb_get_type_id(_cgo0); }())
	name, inMap := unsupportedTypeToStringMap[t]
	if inMap {
		return addIndexToError(unsupportedTypeError(name), colIdx)
	}

	switch t {
	case TYPE_BOOLEAN:
		initBool(vec)
	case TYPE_TINYINT:
		initNumeric[int8](vec, t)
	case TYPE_SMALLINT:
		initNumeric[int16](vec, t)
	case TYPE_INTEGER:
		initNumeric[int32](vec, t)
	case TYPE_BIGINT:
		initNumeric[int64](vec, t)
	case TYPE_UTINYINT:
		initNumeric[uint8](vec, t)
	case TYPE_USMALLINT:
		initNumeric[uint16](vec, t)
	case TYPE_UINTEGER:
		initNumeric[uint32](vec, t)
	case TYPE_UBIGINT:
		initNumeric[uint64](vec, t)
	case TYPE_FLOAT:
		initNumeric[float32](vec, t)
	case TYPE_DOUBLE:
		initNumeric[float64](vec, t)
	case TYPE_TIMESTAMP, TYPE_TIMESTAMP_S, TYPE_TIMESTAMP_MS, TYPE_TIMESTAMP_NS, TYPE_TIMESTAMP_TZ:
		vec.initTS(t)
	case TYPE_DATE:
		vec.initDate()
	case TYPE_TIME, TYPE_TIME_TZ:
		vec.initTime(t)
	case TYPE_INTERVAL:
		vec.initInterval()
	case TYPE_HUGEINT:
		vec.initHugeint()
	case TYPE_VARCHAR, TYPE_BLOB:
		vec.initBytes(t)
	case TYPE_DECIMAL:
		return vec.initDecimal(logicalType, colIdx)
	case TYPE_ENUM:
		return vec.initEnum(logicalType, colIdx)
	case TYPE_LIST:
		return vec.initList(logicalType, colIdx)
	case TYPE_STRUCT:
		return vec.initStruct(logicalType, colIdx)
	case TYPE_MAP:
		return vec.initMap(logicalType, colIdx)
	case TYPE_UUID:
		vec.initUUID()
	case TYPE_SQLNULL:
		vec.initSQLNull()
	default:
		return addIndexToError(unsupportedTypeError(unknownTypeErrMsg), colIdx)
	}
	return nil
}

func (vec *vector) resizeListVector(newLength  /*line :104:47*/_Ctype_idx_t /*line :104:54*/) {
	func() _Ctype_duckdb_state{ _cgo0 := /*line :105:31*/vec.duckdbVector; var _cgo1 _Ctype_idx_t = /*line :105:49*/newLength; _cgoCheckPointer(_cgo0, nil); return /*line :105:59*/_Cfunc_duckdb_list_vector_reserve(_cgo0, _cgo1); }()
	func() _Ctype_duckdb_state{ _cgo0 := /*line :106:32*/vec.duckdbVector; var _cgo1 _Ctype_idx_t = /*line :106:50*/newLength; _cgoCheckPointer(_cgo0, nil); return /*line :106:60*/_Cfunc_duckdb_list_vector_set_size(_cgo0, _cgo1); }()
	vec.resetChildData()
}

func (vec *vector) resetChildData() {
	for i := range vec.childVectors {
		vec.childVectors[i].ptr = func() _cgo_unsafe.Pointer{ _cgo0 := /*line :112:54*/vec.childVectors[i].duckdbVector; _cgoCheckPointer(_cgo0, nil); return /*line :112:87*/_Cfunc_duckdb_vector_get_data(_cgo0); }()
		vec.childVectors[i].resetChildData()
	}
}

func (vec *vector) initVectors(v  /*line :117:34*/_Ctype_duckdb_vector /*line :117:49*/, writable bool) {
	vec.duckdbVector = v
	vec.ptr = func() _cgo_unsafe.Pointer{ _cgo0 := /*line :119:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :119:39*/_Cfunc_duckdb_vector_get_data(_cgo0); }()
	if writable {
		func() { _cgo0 := /*line :121:44*/v; _cgoCheckPointer(_cgo0, nil); /*line :121:46*/_Cfunc_duckdb_vector_ensure_validity_writable(_cgo0); }()
	}
	vec.mask = func() *_Ctype_uint64_t{ _cgo0 := /*line :123:42*/v; _cgoCheckPointer(_cgo0, nil); return /*line :123:44*/_Cfunc_duckdb_vector_get_validity(_cgo0); }()
	vec.getChildVectors(v, writable)
}

func (vec *vector) getChildVectors(v  /*line :127:38*/_Ctype_duckdb_vector /*line :127:53*/, writable bool) {
	switch vec.Type {
	case TYPE_LIST, TYPE_MAP:
		child := func() _Ctype_duckdb_vector{ _cgo0 := /*line :130:43*/v; _cgoCheckPointer(_cgo0, nil); return /*line :130:45*/_Cfunc_duckdb_list_vector_get_child(_cgo0); }()
		vec.childVectors[0].initVectors(child, writable)
	case TYPE_STRUCT:
		for i := 0; i < len(vec.childVectors); i++ {
			child := func() _Ctype_duckdb_vector{ _cgo0 := /*line :134:46*/v; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :134:56*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :134:60*/_Cfunc_duckdb_struct_vector_get_child(_cgo0, _cgo1); }()
			vec.childVectors[i].initVectors(child, writable)
		}
	}
}

func initBool(vec *vector) {
	vec.getFn = func(vec *vector, rowIdx  /*line :141:39*/_Ctype_idx_t /*line :141:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return getPrimitive[bool](vec, rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :147:39*/_Ctype_idx_t /*line :147:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setBool(vec, rowIdx, val)
	}
	vec.Type = TYPE_BOOLEAN
}

func initNumeric[T numericType](vec *vector, t Type) {
	vec.getFn = func(vec *vector, rowIdx  /*line :158:39*/_Ctype_idx_t /*line :158:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return getPrimitive[T](vec, rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :164:39*/_Ctype_idx_t /*line :164:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setNumeric[any, T](vec, rowIdx, val)
	}
	vec.Type = t
}

func (vec *vector) initTS(t Type) {
	vec.getFn = func(vec *vector, rowIdx  /*line :175:39*/_Ctype_idx_t /*line :175:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getTS(t, rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :181:39*/_Ctype_idx_t /*line :181:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setTS(vec, rowIdx, val)
	}
	vec.Type = t
}

func (vec *vector) initDate() {
	vec.getFn = func(vec *vector, rowIdx  /*line :192:39*/_Ctype_idx_t /*line :192:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getDate(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :198:39*/_Ctype_idx_t /*line :198:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setDate(vec, rowIdx, val)
	}
	vec.Type = TYPE_DATE
}

func (vec *vector) initTime(t Type) {
	vec.getFn = func(vec *vector, rowIdx  /*line :209:39*/_Ctype_idx_t /*line :209:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getTime(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :215:39*/_Ctype_idx_t /*line :215:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setTime(vec, rowIdx, val)
	}
	vec.Type = t
}

func (vec *vector) initInterval() {
	vec.getFn = func(vec *vector, rowIdx  /*line :226:39*/_Ctype_idx_t /*line :226:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getInterval(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :232:39*/_Ctype_idx_t /*line :232:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setInterval(vec, rowIdx, val)
	}
	vec.Type = TYPE_INTERVAL
}

func (vec *vector) initHugeint() {
	vec.getFn = func(vec *vector, rowIdx  /*line :243:39*/_Ctype_idx_t /*line :243:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getHugeint(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :249:39*/_Ctype_idx_t /*line :249:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setHugeint(vec, rowIdx, val)
	}
	vec.Type = TYPE_HUGEINT
}

func (vec *vector) initBytes(t Type) {
	vec.getFn = func(vec *vector, rowIdx  /*line :260:39*/_Ctype_idx_t /*line :260:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getCString(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :266:39*/_Ctype_idx_t /*line :266:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setBytes(vec, rowIdx, val)
	}
	vec.Type = t
}

func (vec *vector) initDecimal(logicalType  /*line :276:44*/_Ctype_duckdb_logical_type /*line :276:65*/, colIdx int) error {
	vec.decimalWidth = uint8(func() _Ctype_uint8_t{ _cgo0 := /*line :277:50*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :277:62*/_Cfunc_duckdb_decimal_width(_cgo0); }())
	vec.decimalScale = uint8(func() _Ctype_uint8_t{ _cgo0 := /*line :278:50*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :278:62*/_Cfunc_duckdb_decimal_scale(_cgo0); }())

	t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :280:43*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :280:55*/_Cfunc_duckdb_decimal_internal_type(_cgo0); }())
	switch t {
	case TYPE_SMALLINT, TYPE_INTEGER, TYPE_BIGINT, TYPE_HUGEINT:
		vec.getFn = func(vec *vector, rowIdx  /*line :283:40*/_Ctype_idx_t /*line :283:47*/) any {
			if vec.getNull(rowIdx) {
				return nil
			}
			return vec.getDecimal(rowIdx)
		}
		vec.setFn = func(vec *vector, rowIdx  /*line :289:40*/_Ctype_idx_t /*line :289:47*/, val any) error {
			if val == nil {
				vec.setNull(rowIdx)
				return nil
			}
			return setDecimal(vec, rowIdx, val)
		}
	default:
		return addIndexToError(unsupportedTypeError(typeToStringMap[t]), colIdx)
	}

	vec.Type = TYPE_DECIMAL
	vec.internalType = t
	return nil
}

func (vec *vector) initEnum(logicalType  /*line :305:41*/_Ctype_duckdb_logical_type /*line :305:62*/, colIdx int) error {
	// Initialize the dictionary.
	dictSize := uint32(func() _Ctype_uint32_t{ _cgo0 := /*line :307:51*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :307:63*/_Cfunc_duckdb_enum_dictionary_size(_cgo0); }())
	vec.dict = make(map[string]uint32)
	for i := uint32(0); i < dictSize; i++ {
		cStr := func() *_Ctype_char{ _cgo0 := /*line :310:42*/logicalType; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :310:62*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :310:66*/_Cfunc_duckdb_enum_dictionary_value(_cgo0, _cgo1); }()
		str := ( /*line :311:10*/_Cfunc_GoString /*line :311:19*/)(cStr)
		vec.dict[str] = i
		func() { _cgo0 := /*line :313:17*/unsafe.Pointer(cStr); _cgoCheckPointer(_cgo0, nil); /*line :313:38*/_Cfunc_duckdb_free(_cgo0); }()
	}

	t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :316:40*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :316:52*/_Cfunc_duckdb_enum_internal_type(_cgo0); }())
	switch t {
	case TYPE_UTINYINT, TYPE_USMALLINT, TYPE_UINTEGER, TYPE_UBIGINT:
		vec.getFn = func(vec *vector, rowIdx  /*line :319:40*/_Ctype_idx_t /*line :319:47*/) any {
			if vec.getNull(rowIdx) {
				return nil
			}
			return vec.getEnum(rowIdx)
		}
		vec.setFn = func(vec *vector, rowIdx  /*line :325:40*/_Ctype_idx_t /*line :325:47*/, val any) error {
			if val == nil {
				vec.setNull(rowIdx)
				return nil
			}
			return setEnum(vec, rowIdx, val)
		}
	default:
		return addIndexToError(unsupportedTypeError(typeToStringMap[t]), colIdx)
	}

	vec.Type = TYPE_ENUM
	vec.internalType = t
	return nil
}

func (vec *vector) initList(logicalType  /*line :341:41*/_Ctype_duckdb_logical_type /*line :341:62*/, colIdx int) error {
	// Get the child vector type.
	childType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :343:45*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :343:57*/_Cfunc_duckdb_list_type_child_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :344:38*/&childType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :344:49*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	// Recurse into the child.
	vec.childVectors = make([]vector, 1)
	err := vec.childVectors[0].init(childType, colIdx)
	if err != nil {
		return err
	}

	vec.getFn = func(vec *vector, rowIdx  /*line :353:39*/_Ctype_idx_t /*line :353:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getList(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :359:39*/_Ctype_idx_t /*line :359:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setList(vec, rowIdx, val)
	}
	vec.Type = TYPE_LIST
	return nil
}

func (vec *vector) initStruct(logicalType  /*line :370:43*/_Ctype_duckdb_logical_type /*line :370:64*/, colIdx int) error {
	childCount := int(func() _Ctype_idx_t{ _cgo0 := /*line :371:53*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :371:65*/_Cfunc_duckdb_struct_type_child_count(_cgo0); }())
	var structEntries []StructEntry
	for i := 0; i < childCount; i++ {
		name := func() *_Ctype_char{ _cgo0 := /*line :374:43*/logicalType; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :374:63*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :374:67*/_Cfunc_duckdb_struct_type_child_name(_cgo0, _cgo1); }()
		entry, err := NewStructEntry(nil, ( /*line :375:37*/_Cfunc_GoString /*line :375:46*/)(name))
		structEntries = append(structEntries, entry)
		func() { _cgo0 := /*line :377:17*/unsafe.Pointer(name); _cgoCheckPointer(_cgo0, nil); /*line :377:38*/_Cfunc_duckdb_free(_cgo0); }()
		if err != nil {
			return err
		}
	}

	vec.childVectors = make([]vector, childCount)
	vec.structEntries = structEntries

	// Recurse into the children.
	for i := 0; i < childCount; i++ {
		childType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :388:48*/logicalType; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :388:68*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :388:72*/_Cfunc_duckdb_struct_type_child_type(_cgo0, _cgo1); }()
		err := vec.childVectors[i].init(childType, colIdx)
		func() { _cgoBase0 := /*line :390:33*/&childType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :390:44*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()

		if err != nil {
			return err
		}
	}

	vec.getFn = func(vec *vector, rowIdx  /*line :397:39*/_Ctype_idx_t /*line :397:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getStruct(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :403:39*/_Ctype_idx_t /*line :403:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setStruct(vec, rowIdx, val)
	}
	vec.Type = TYPE_STRUCT
	return nil
}

func (vec *vector) initMap(logicalType  /*line :414:40*/_Ctype_duckdb_logical_type /*line :414:61*/, colIdx int) error {
	// A MAP is a LIST of STRUCT values. Each STRUCT holds two children: a key and a value.

	// Get the child vector type.
	childType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :418:45*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :418:57*/_Cfunc_duckdb_list_type_child_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :419:38*/&childType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :419:49*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	// Recurse into the child.
	vec.childVectors = make([]vector, 1)
	err := vec.childVectors[0].init(childType, colIdx)
	if err != nil {
		return err
	}

	// DuckDB supports more MAP key types than Go, which only supports comparable types.
	// We ensure that the key type itself is comparable.
	keyType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :430:40*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :430:52*/_Cfunc_duckdb_map_type_key_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :431:38*/&keyType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :431:47*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :433:33*/keyType; _cgoCheckPointer(_cgo0, nil); return /*line :433:41*/_Cfunc_duckdb_get_type_id(_cgo0); }())
	switch t {
	case TYPE_LIST, TYPE_STRUCT, TYPE_MAP, TYPE_ARRAY:
		return addIndexToError(errUnsupportedMapKeyType, colIdx)
	}

	vec.getFn = func(vec *vector, rowIdx  /*line :439:39*/_Ctype_idx_t /*line :439:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		return vec.getMap(rowIdx)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :445:39*/_Ctype_idx_t /*line :445:46*/, val any) error {
		if val == nil {
			vec.setNull(rowIdx)
			return nil
		}
		return setMap(vec, rowIdx, val)
	}
	vec.Type = TYPE_MAP
	return nil
}

func (vec *vector) initUUID() {
	vec.getFn = func(vec *vector, rowIdx  /*line :457:39*/_Ctype_idx_t /*line :457:46*/) any {
		if vec.getNull(rowIdx) {
			return nil
		}
		hugeInt := getPrimitive[ /*line :461:27*/_Ctype_duckdb_hugeint /*line :461:43*/](vec, rowIdx)
		return hugeIntToUUID(hugeInt)
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :464:39*/_Ctype_idx_t /*line :464:46*/, val any) error {
		if val == nil || val == (*UUID)(nil) {
			vec.setNull(rowIdx)
			return nil
		}
		return setUUID(vec, rowIdx, val)
	}
	vec.Type = TYPE_UUID
}

func (vec *vector) initSQLNull() {
	vec.getFn = func(vec *vector, rowIdx  /*line :475:39*/_Ctype_idx_t /*line :475:46*/) any {
		return nil
	}
	vec.setFn = func(vec *vector, rowIdx  /*line :478:39*/_Ctype_idx_t /*line :478:46*/, val any) error {
		return errSetSQLNULLValue
	}
	vec.Type = TYPE_SQLNULL
}
