// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/replacement_scan.go:1:1
package duckdb

/*
   	#include <duckdb.h>
   	void replacement_scan_cb(duckdb_replacement_scan_info info, const char *table_name, void *data);
   	typedef const char cchar_t;
	void replacement_scan_destroy_data(void *);
*/
import _ "unsafe"

import (
	"runtime/cgo"
	"unsafe"
)

type ReplacementScanCallback func(tableName string) (string, []any, error)

func RegisterReplacementScan(connector *Connector, cb ReplacementScanCallback) {
	handle := cgo.NewHandle(cb)
	func() { _cgo0 := /*line :20:32*/connector.db; var _cgo1 *[0]byte = _Ctype_duckdb_replacement_callback_t /*line :20:77*/(_Cgo_ptr(_Cfpvar_fp_replacement_scan_cb /*line :20:99*/)); _cgoBase2 := /*line :20:117*/&handle; _cgo2 := /*line :20:102*/unsafe.Pointer(_cgoBase2); var _cgo3 *[0]byte = _Ctype_duckdb_delete_callback_t /*line :20:153*/(_Cgo_ptr(_Cfpvar_fp_replacement_scan_destroy_data /*line :20:185*/)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase2, 0 == 0); /*line :20:187*/_Cfunc_duckdb_add_replacement_scan(_cgo0, _cgo1, _cgo2, _cgo3); }()
}

//export replacement_scan_destroy_data
func replacement_scan_destroy_data(data unsafe.Pointer) {
	h := *(*cgo.Handle)(data)
	h.Delete()
}

//export replacement_scan_cb
func replacement_scan_cb(info  /*line :30:31*/_Ctype_duckdb_replacement_scan_info /*line :30:61*/, table_name * /*line :30:75*/_Ctype_cchar_t /*line :30:84*/, data * /*line :30:92*/_Ctype_void /*line :30:98*/) {
	h := *(*cgo.Handle)(unsafe.Pointer(data))
	scanner := h.Value().(ReplacementScanCallback)
	tFunc, params, err := scanner(( /*line :33:32*/_Cfunc_GoString /*line :33:41*/)(table_name))
	if err != nil {
		errStr := ( /*line :35:13*/_Cfunc_CString /*line :35:21*/)(err.Error())
		defer func() func() { _cgo0 := /*line :36:23*/unsafe.Pointer(errStr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :36:46*/_Cfunc_duckdb_free(_cgo0); }}()()
		func() { _cgo0 := /*line :37:39*/info; var _cgo1 *_Ctype_char = /*line :37:45*/errStr; _cgoCheckPointer(_cgo0, nil); /*line :37:52*/_Cfunc_duckdb_replacement_scan_set_error(_cgo0, _cgo1); }()
		return
	}

	fNameStr := ( /*line :41:14*/_Cfunc_CString /*line :41:22*/)(tFunc)
	func() { _cgo0 := /*line :42:46*/info; var _cgo1 *_Ctype_char = /*line :42:52*/fNameStr; _cgoCheckPointer(_cgo0, nil); /*line :42:61*/_Cfunc_duckdb_replacement_scan_set_function_name(_cgo0, _cgo1); }()
	defer func() func() { _cgo0 := /*line :43:22*/unsafe.Pointer(fNameStr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :43:47*/_Cfunc_duckdb_free(_cgo0); }}()()

	for _, v := range params {
		switch x := v.(type) {
		case string:
			str := ( /*line :48:11*/_Cfunc_CString /*line :48:19*/)(x)
			val := ( /*line :49:11*/_Cfunc_duckdb_create_varchar /*line :49:33*/)(str)
			func() { _cgo0 := /*line :50:44*/info; _cgo1 := /*line :50:50*/val; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :50:54*/_Cfunc_duckdb_replacement_scan_add_parameter(_cgo0, _cgo1); }()
			func() { _cgo0 := /*line :51:18*/unsafe.Pointer(str); _cgoCheckPointer(_cgo0, nil); /*line :51:38*/_Cfunc_duckdb_free(_cgo0); }()
			func() { _cgoBase0 := /*line :52:27*/&val; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :52:32*/_Cfunc_duckdb_destroy_value(_cgo0); }()
		case int64:
			val := ( /*line :54:11*/_Cfunc_duckdb_create_int64 /*line :54:31*/)( /*line :54:33*/_Ctype_int64_t /*line :54:42*/(x))
			func() { _cgo0 := /*line :55:44*/info; _cgo1 := /*line :55:50*/val; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :55:54*/_Cfunc_duckdb_replacement_scan_add_parameter(_cgo0, _cgo1); }()
			func() { _cgoBase0 := /*line :56:27*/&val; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :56:32*/_Cfunc_duckdb_destroy_value(_cgo0); }()
		default:
			errStr := ( /*line :58:14*/_Cfunc_CString /*line :58:22*/)("invalid type")
			func() { _cgo0 := /*line :59:40*/info; var _cgo1 *_Ctype_char = /*line :59:46*/errStr; _cgoCheckPointer(_cgo0, nil); /*line :59:53*/_Cfunc_duckdb_replacement_scan_set_error(_cgo0, _cgo1); }()
			func() { _cgo0 := /*line :60:18*/unsafe.Pointer(errStr); _cgoCheckPointer(_cgo0, nil); /*line :60:41*/_Cfunc_duckdb_free(_cgo0); }()
			return
		}
	}
}
