// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/rows.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"database/sql/driver"
	"fmt"
	"io"
	"math/big"
	"reflect"
	"strings"
	"time"
	"unsafe"
)

// rows is a helper struct for scanning a duckdb result.
type rows struct {
	// stmt is a pointer to the stmt of which we are scanning the result.
	stmt *stmt
	// res is the result of stmt.
	res  /*line :24:6*/_Ctype_duckdb_result /*line :24:21*/
	// chunk holds the currently active data chunk.
	chunk DataChunk
	// chunkCount is the number of chunks in the result.
	chunkCount  /*line :28:13*/_Ctype_idx_t /*line :28:20*/
	// chunkIdx is the chunk index in the result.
	chunkIdx  /*line :30:11*/_Ctype_idx_t /*line :30:18*/
	// rowCount is the number of scanned rows.
	rowCount int
}

func newRowsWithStmt(res  /*line :35:26*/_Ctype_duckdb_result /*line :35:41*/, stmt *stmt) *rows {
	columnCount := func() _Ctype_idx_t{ _cgoBase0 := /*line :36:39*/&res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :36:44*/_Cfunc_duckdb_column_count(_cgo0); }()
	r := rows{
		res:        res,
		stmt:       stmt,
		chunk:      DataChunk{},
		chunkCount: func() _Ctype_idx_t{ _cgo0 := /*line :41:43*/res; _cgoCheckPointer(_cgo0, nil); return /*line :41:47*/_Cfunc_duckdb_result_chunk_count(_cgo0); }(),
		chunkIdx:   0,
		rowCount:   0,
	}

	for i :=  /*line :46:11*/_Ctype_idx_t /*line :46:18*/(0); i < columnCount; i++ {
		columnName := ( /*line :47:17*/_Cfunc_GoString /*line :47:26*/)(func() *_Ctype_char{ _cgoBase0 := /*line :47:49*/&res; _cgo0 := _cgoBase0; var _cgo1 _Ctype_idx_t = /*line :47:55*/i; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :47:57*/_Cfunc_duckdb_column_name(_cgo0, _cgo1); }())
		r.chunk.columnNames = append(r.chunk.columnNames, columnName)
	}
	return &r
}

func (r *rows) Columns() []string {
	return r.chunk.columnNames
}

func (r *rows) Next(dst []driver.Value) error {
	for r.rowCount == r.chunk.size {
		r.chunk.close()
		if r.chunkIdx == r.chunkCount {
			return io.EOF
		}
		data := func() _Ctype_duckdb_data_chunk{ _cgo0 := /*line :63:37*/r.res; var _cgo1 _Ctype_idx_t = /*line :63:44*/r.chunkIdx; _cgoCheckPointer(_cgo0, nil); return /*line :63:55*/_Cfunc_duckdb_result_get_chunk(_cgo0, _cgo1); }()
		if err := r.chunk.initFromDuckDataChunk(data, false); err != nil {
			return getError(err, nil)
		}

		r.chunkIdx++
		r.rowCount = 0
	}

	columnCount := len(r.chunk.columns)
	for colIdx := 0; colIdx < columnCount; colIdx++ {
		var err error
		if dst[colIdx], err = r.chunk.GetValue(colIdx, r.rowCount); err != nil {
			return err
		}
	}

	r.rowCount++
	return nil
}

// ColumnTypeScanType implements driver.RowsColumnTypeScanType.
func (r *rows) ColumnTypeScanType(index int) reflect.Type {
	t := Type(func() _Ctype_duckdb_type{ _cgoBase0 := /*line :86:33*/&r.res; _cgo0 := _cgoBase0; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :86:48*/(index); _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :86:56*/_Cfunc_duckdb_column_type(_cgo0, _cgo1); }())
	switch t {
	case TYPE_INVALID:
		return nil
	case TYPE_BOOLEAN:
		return reflect.TypeOf(true)
	case TYPE_TINYINT:
		return reflect.TypeOf(int8(0))
	case TYPE_SMALLINT:
		return reflect.TypeOf(int16(0))
	case TYPE_INTEGER:
		return reflect.TypeOf(int32(0))
	case TYPE_BIGINT:
		return reflect.TypeOf(int64(0))
	case TYPE_UTINYINT:
		return reflect.TypeOf(uint8(0))
	case TYPE_USMALLINT:
		return reflect.TypeOf(uint16(0))
	case TYPE_UINTEGER:
		return reflect.TypeOf(uint32(0))
	case TYPE_UBIGINT:
		return reflect.TypeOf(uint64(0))
	case TYPE_FLOAT:
		return reflect.TypeOf(float32(0))
	case TYPE_DOUBLE:
		return reflect.TypeOf(float64(0))
	case TYPE_TIMESTAMP, TYPE_TIMESTAMP_S, TYPE_TIMESTAMP_MS, TYPE_TIMESTAMP_NS, TYPE_DATE, TYPE_TIME, TYPE_TIME_TZ, TYPE_TIMESTAMP_TZ:
		return reflect.TypeOf(time.Time{})
	case TYPE_INTERVAL:
		return reflect.TypeOf(Interval{})
	case TYPE_HUGEINT:
		return reflect.TypeOf(big.NewInt(0))
	case TYPE_VARCHAR, TYPE_ENUM:
		return reflect.TypeOf("")
	case TYPE_BLOB:
		return reflect.TypeOf([]byte{})
	case TYPE_DECIMAL:
		return reflect.TypeOf(Decimal{})
	case TYPE_LIST:
		return reflect.TypeOf([]any{})
	case TYPE_STRUCT:
		return reflect.TypeOf(map[string]any{})
	case TYPE_MAP:
		return reflect.TypeOf(Map{})
	case TYPE_UUID:
		return reflect.TypeOf([]byte{})
	default:
		return nil
	}
}

// ColumnTypeDatabaseTypeName implements driver.RowsColumnTypeScanType.
func (r *rows) ColumnTypeDatabaseTypeName(index int) string {
	t := Type(func() _Ctype_duckdb_type{ _cgoBase0 := /*line :139:33*/&r.res; _cgo0 := _cgoBase0; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :139:48*/(index); _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :139:56*/_Cfunc_duckdb_column_type(_cgo0, _cgo1); }())
	switch t {
	case TYPE_DECIMAL, TYPE_ENUM, TYPE_LIST, TYPE_STRUCT, TYPE_MAP:
		// Only allocate the logical type if necessary.
		logicalType := func() _Ctype_duckdb_logical_type{ _cgoBase0 := /*line :143:47*/&r.res; _cgo0 := _cgoBase0; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :143:62*/(index); _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :143:70*/_Cfunc_duckdb_column_logical_type(_cgo0, _cgo1); }()
		defer func() func() { _cgoBase0 := /*line :144:39*/&logicalType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :144:52*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()
		return logicalTypeName(logicalType)
	default:
		return typeToStringMap[t]
	}
}

func (r *rows) Close() error {
	r.chunk.close()
	func() { _cgoBase0 := /*line :153:26*/&r.res; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :153:33*/_Cfunc_duckdb_destroy_result(_cgo0); }()

	var err error
	if r.stmt != nil {
		r.stmt.rows = false
		if r.stmt.closeOnRowsClose {
			err = r.stmt.Close()
		}
		r.stmt = nil
	}
	return err
}

func logicalTypeName(logicalType  /*line :166:34*/_Ctype_duckdb_logical_type /*line :166:55*/) string {
	t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :167:33*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :167:45*/_Cfunc_duckdb_get_type_id(_cgo0); }())
	switch t {
	case TYPE_DECIMAL:
		width := func() _Ctype_uint8_t{ _cgo0 := /*line :170:35*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :170:47*/_Cfunc_duckdb_decimal_width(_cgo0); }()
		scale := func() _Ctype_uint8_t{ _cgo0 := /*line :171:35*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :171:47*/_Cfunc_duckdb_decimal_scale(_cgo0); }()
		return fmt.Sprintf("DECIMAL(%d,%d)", width, scale)
	case TYPE_ENUM:
		// The C API does not expose ENUM names.
		return "ENUM"
	case TYPE_LIST:
		childType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :177:46*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :177:58*/_Cfunc_duckdb_list_type_child_type(_cgo0); }()
		defer func() func() { _cgoBase0 := /*line :178:39*/&childType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :178:50*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()
		return logicalTypeName(childType) + "[]"
	case TYPE_STRUCT:
		return logicalTypeNameStruct(logicalType)
	case TYPE_MAP:
		return logicalTypeNameMap(logicalType)
	default:
		return typeToStringMap[t]
	}
}

func logicalTypeNameStruct(logicalType  /*line :189:40*/_Ctype_duckdb_logical_type /*line :189:61*/) string {
	count := int(func() _Ctype_idx_t{ _cgo0 := /*line :190:48*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :190:60*/_Cfunc_duckdb_struct_type_child_count(_cgo0); }())
	name := "STRUCT("

	for i := 0; i < count; i++ {
		ptrToChildName := func() *_Ctype_char{ _cgo0 := /*line :194:53*/logicalType; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :194:73*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :194:77*/_Cfunc_duckdb_struct_type_child_name(_cgo0, _cgo1); }()
		childName := ( /*line :195:16*/_Cfunc_GoString /*line :195:25*/)(ptrToChildName)
		childType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :196:48*/logicalType; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :196:68*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :196:72*/_Cfunc_duckdb_struct_type_child_type(_cgo0, _cgo1); }()

		// Add comma if not at the end of the list.
		name += escapeStructFieldName(childName) + " " + logicalTypeName(childType)
		if i != count-1 {
			name += ", "
		}

		func() { _cgo0 := /*line :204:17*/unsafe.Pointer(ptrToChildName); _cgoCheckPointer(_cgo0, nil); /*line :204:48*/_Cfunc_duckdb_free(_cgo0); }()
		func() { _cgoBase0 := /*line :205:33*/&childType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :205:44*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	}
	return name + ")"
}

func logicalTypeNameMap(logicalType  /*line :210:37*/_Ctype_duckdb_logical_type /*line :210:58*/) string {
	keyType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :211:40*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :211:52*/_Cfunc_duckdb_map_type_key_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :212:38*/&keyType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :212:47*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	valueType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :214:44*/logicalType; _cgoCheckPointer(_cgo0, nil); return /*line :214:56*/_Cfunc_duckdb_map_type_value_type(_cgo0); }()
	defer func() func() { _cgoBase0 := /*line :215:38*/&valueType; _cgo0 := _cgoBase0; return func() { _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :215:49*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }}()()

	return fmt.Sprintf("MAP(%s, %s)", logicalTypeName(keyType), logicalTypeName(valueType))
}

func escapeStructFieldName(s string) string {
	// DuckDB escapes STRUCT field names by doubling double quotes, then wrapping in double quotes.
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}
