// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/tableUDF.go:1:1
package duckdb; import _cgo_unsafe "unsafe"

/*
#include <duckdb.h>

void table_udf_bind_row(duckdb_bind_info info);
void table_udf_bind_chunk(duckdb_bind_info info);
void table_udf_bind_parallel_row(duckdb_bind_info info);
void table_udf_bind_parallel_chunk(duckdb_bind_info info);

void table_udf_init(duckdb_init_info info);
void table_udf_init_parallel(duckdb_init_info info);
void table_udf_local_init(duckdb_init_info info);

// See https://golang.org/issue/19837
void table_udf_row_callback(duckdb_function_info, duckdb_data_chunk);
void table_udf_chunk_callback(duckdb_function_info, duckdb_data_chunk);

// See https://golang.org/issue/19835.
typedef void (*init)(duckdb_function_info);
typedef void (*bind)(duckdb_function_info);
typedef void (*callback)(duckdb_function_info, duckdb_data_chunk);

void udf_delete_callback(void *);
*/
import _ "unsafe"

import (
	"database/sql"
	"runtime"
	"runtime/cgo"
	"unsafe"
)

type (
	// ColumnInfo contains the metadata of a column.
	ColumnInfo struct {
		// The column Name.
		Name string
		// The column type T.
		T TypeInfo
	}

	// CardinalityInfo contains the cardinality of a (table) function.
	// If it is impossible or difficult to determine the exact cardinality, an approximate cardinality may be used.
	CardinalityInfo struct {
		// The absolute Cardinality.
		Cardinality uint
		// IsExact indicates whether the cardinality is exact.
		Exact bool
	}

	// ParallelTableSourceInfo contains information for initializing a parallelism-aware table source.
	ParallelTableSourceInfo struct {
		// MaxThreads is the maximum number of threads on which to run the table source function.
		// If set to 0, it uses DuckDB's default thread configuration.
		MaxThreads int
	}

	tableFunctionData struct {
		fun        any
		projection []int
	}

	tableSource interface {
		// ColumnInfos returns column information for each column of the table function.
		ColumnInfos() []ColumnInfo
		// Cardinality returns the cardinality information of the table function.
		// Optionally, if no cardinality exists, it may return nil.
		Cardinality() *CardinalityInfo
	}

	parallelTableSource interface {
		tableSource
		// Init the table source.
		// Additionally, it returns information for the parallelism-aware table source.
		Init() ParallelTableSourceInfo
		// NewLocalState returns a thread-local execution state.
		// It must return a pointer or a reference type for correct state updates.
		// go-duckdb does not prevent non-reference values.
		NewLocalState() any
	}

	sequentialTableSource interface {
		tableSource
		// Init the table source.
		Init()
	}

	// A RowTableSource represents anything that produces rows in a non-vectorised way.
	// The cardinality is requested before function initialization.
	// After initializing the RowTableSource, go-duckdb requests the rows.
	// It sequentially calls the FillRow method with a single thread.
	RowTableSource interface {
		sequentialTableSource
		// FillRow takes a Row and fills it with values.
		// It returns true, if there are more rows to fill.
		FillRow(Row) (bool, error)
	}

	// A ParallelRowTableSource represents anything that produces rows in a non-vectorised way.
	// The cardinality is requested before function initialization.
	// After initializing the ParallelRowTableSource, go-duckdb requests the rows.
	// It simultaneously calls the FillRow method with multiple threads.
	// If ParallelTableSourceInfo.MaxThreads is greater than one, FillRow must use synchronisation
	// primitives to avoid race conditions.
	ParallelRowTableSource interface {
		parallelTableSource
		// FillRow takes a Row and fills it with values.
		// It returns true, if there are more rows to fill.
		FillRow(any, Row) (bool, error)
	}

	// A ChunkTableSource represents anything that produces rows in a vectorised way.
	// The cardinality is requested before function initialization.
	// After initializing the ChunkTableSource, go-duckdb requests the rows.
	// It sequentially calls the FillChunk method with a single thread.
	ChunkTableSource interface {
		sequentialTableSource
		// FillChunk takes a Chunk and fills it with values.
		// It returns true, if there are more chunks to fill.
		FillChunk(DataChunk) error
	}

	// A ParallelChunkTableSource represents anything that produces rows in a vectorised way.
	// The cardinality is requested before function initialization.
	// After initializing the ParallelChunkTableSource, go-duckdb requests the rows.
	// It simultaneously calls the FillChunk method with multiple threads.
	// If ParallelTableSourceInfo.MaxThreads is greater than one, FillChunk must use synchronization
	// primitives to avoid race conditions.
	ParallelChunkTableSource interface {
		parallelTableSource
		// FillChunk takes a Chunk and fills it with values.
		// It returns true, if there are more chunks to fill.
		FillChunk(any, DataChunk) error
	}

	// TableFunctionConfig contains any information passed to DuckDB when registering the table function.
	TableFunctionConfig struct {
		// The Arguments of the table function.
		Arguments []TypeInfo
		// The NamedArguments of the table function.
		NamedArguments map[string]TypeInfo
	}

	// TableFunction implements different table function types:
	// RowTableFunction, ParallelRowTableFunction, ChunkTableFunction, and ParallelChunkTableFunction.
	TableFunction interface {
		RowTableFunction | ParallelRowTableFunction | ChunkTableFunction | ParallelChunkTableFunction
	}

	// A RowTableFunction is a type which can be bound to return a RowTableSource.
	RowTableFunction = tableFunction[RowTableSource]
	// A ParallelRowTableFunction is a type which can be bound to return a ParallelRowTableSource.
	ParallelRowTableFunction = tableFunction[ParallelRowTableSource]
	// A ChunkTableFunction is a type which can be bound to return a ChunkTableSource.
	ChunkTableFunction = tableFunction[ChunkTableSource]
	// A ParallelChunkTableFunction is a type which can be bound to return a ParallelChunkTableSource.
	ParallelChunkTableFunction = tableFunction[ParallelChunkTableSource]

	tableFunction[T any] struct {
		// Config returns the table function configuration, including the function arguments.
		Config TableFunctionConfig
		// BindArguments binds the arguments and returns a TableSource.
		BindArguments func(named map[string]any, args ...any) (T, error)
	}
)

func (tfd *tableFunctionData) setColumnCount(info  /*line :169:51*/_Ctype_duckdb_init_info /*line :169:69*/) {
	count := func() _Ctype_idx_t{ _cgo0 := /*line :170:42*/info; _cgoCheckPointer(_cgo0, nil); return /*line :170:47*/_Cfunc_duckdb_init_get_column_count(_cgo0); }()
	for i := 0; i < int(count); i++ {
		srcPos := func() _Ctype_idx_t{ _cgo0 := /*line :172:44*/info; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :172:57*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :172:61*/_Cfunc_duckdb_init_get_column_index(_cgo0, _cgo1); }()
		tfd.projection[int(srcPos)] = i
	}
}

//export table_udf_bind_row
func table_udf_bind_row(info  /*line :178:30*/_Ctype_duckdb_bind_info /*line :178:48*/) {
	udfBindTyped[RowTableSource](info)
}

//export table_udf_bind_chunk
func table_udf_bind_chunk(info  /*line :183:32*/_Ctype_duckdb_bind_info /*line :183:50*/) {
	udfBindTyped[ChunkTableSource](info)
}

//export table_udf_bind_parallel_row
func table_udf_bind_parallel_row(info  /*line :188:39*/_Ctype_duckdb_bind_info /*line :188:57*/) {
	udfBindTyped[ParallelRowTableSource](info)
}

//export table_udf_bind_parallel_chunk
func table_udf_bind_parallel_chunk(info  /*line :193:41*/_Ctype_duckdb_bind_info /*line :193:59*/) {
	udfBindTyped[ParallelChunkTableSource](info)
}

func udfBindTyped[T tableSource](info  /*line :197:39*/_Ctype_duckdb_bind_info /*line :197:57*/) {
	f := getPinned[tableFunction[T]](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :198:64*/info; _cgoCheckPointer(_cgo0, nil); return /*line :198:69*/_Cfunc_duckdb_bind_get_extra_info(_cgo0); }())
	config := f.Config

	argCount := len(config.Arguments)
	args := make([]any, argCount)
	namedArgs := make(map[string]any)

	for i, t := range config.Arguments {
		value := func() _Ctype_duckdb_value{ _cgo0 := /*line :206:40*/info; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :206:53*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :206:57*/_Cfunc_duckdb_bind_get_parameter(_cgo0, _cgo1); }()
		var err error
		args[i], err = getValue(t, value)
		func() { _cgoBase0 := /*line :209:26*/&value; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :209:33*/_Cfunc_duckdb_destroy_value(_cgo0); }()

		if err != nil {
			setBindError(info, err.Error())
			return
		}
	}

	for name, t := range config.NamedArguments {
		argName := ( /*line :218:14*/_Cfunc_CString /*line :218:22*/)(name)
		value := func() _Ctype_duckdb_value{ _cgo0 := /*line :219:46*/info; var _cgo1 *_Ctype_char = /*line :219:52*/argName; _cgoCheckPointer(_cgo0, nil); return /*line :219:60*/_Cfunc_duckdb_bind_get_named_parameter(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :220:17*/unsafe.Pointer(argName); _cgoCheckPointer(_cgo0, nil); /*line :220:41*/_Cfunc_duckdb_free(_cgo0); }()

		var err error
		namedArgs[name], err = getValue(t, value)
		func() { _cgoBase0 := /*line :224:26*/&value; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :224:33*/_Cfunc_duckdb_destroy_value(_cgo0); }()

		if err != nil {
			setBindError(info, err.Error())
			return
		}
	}

	instance, err := f.BindArguments(namedArgs, args...)
	if err != nil {
		setBindError(info, err.Error())
		return
	}

	columnInfos := instance.ColumnInfos()
	instanceData := tableFunctionData{
		fun:        instance,
		projection: make([]int, len(columnInfos)),
	}

	for i, v := range columnInfos {
		if v.T == nil {
			setBindError(info, errTableUDFColumnTypeIsNil.Error())
			return
		}

		logicalType := v.T.logicalType()
		name := ( /*line :251:11*/_Cfunc_CString /*line :251:19*/)(v.Name)
		func() { _cgo0 := /*line :252:35*/info; var _cgo1 *_Ctype_char = /*line :252:41*/name; _cgo2 := /*line :252:47*/logicalType; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo2, nil); /*line :252:59*/_Cfunc_duckdb_bind_add_result_column(_cgo0, _cgo1, _cgo2); }()
		func() { _cgoBase0 := /*line :253:33*/&logicalType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :253:46*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
		func() { _cgo0 := /*line :254:17*/unsafe.Pointer(name); _cgoCheckPointer(_cgo0, nil); /*line :254:38*/_Cfunc_duckdb_free(_cgo0); }()

		instanceData.projection[i] = -1
	}

	cardinality := instance.Cardinality()
	if cardinality != nil {
		func() { _cgo0 := /*line :261:33*/info; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :261:46*/(cardinality.Cardinality); var _cgo2 _Ctype__Bool = _Ctype_bool /*line :261:79*/(cardinality.Exact); _cgoCheckPointer(_cgo0, nil); /*line :261:99*/_Cfunc_duckdb_bind_set_cardinality(_cgo0, _cgo1, _cgo2); }()
	}

	pinnedInstanceData := pinnedValue[tableFunctionData]{
		pinner: &runtime.Pinner{},
		value:  instanceData,
	}

	h := cgo.NewHandle(pinnedInstanceData)
	pinnedInstanceData.pinner.Pin(&h)
	func() { _cgo0 := /*line :271:30*/info; _cgoBase1 := /*line :271:51*/&h; _cgo1 := /*line :271:36*/unsafe.Pointer(_cgoBase1); var _cgo2 *[0]byte = _Ctype_duckdb_delete_callback_t /*line :271:82*/(_Cgo_ptr(_Cfpvar_fp_udf_delete_callback /*line :271:104*/)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); /*line :271:106*/_Cfunc_duckdb_bind_set_bind_data(_cgo0, _cgo1, _cgo2); }()
}

//export table_udf_init
func table_udf_init(info  /*line :275:26*/_Ctype_duckdb_init_info /*line :275:44*/) {
	instance := getPinned[tableFunctionData](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :276:71*/info; _cgoCheckPointer(_cgo0, nil); return /*line :276:76*/_Cfunc_duckdb_init_get_bind_data(_cgo0); }())
	instance.setColumnCount(info)
	instance.fun.(sequentialTableSource).Init()
}

//export table_udf_init_parallel
func table_udf_init_parallel(info  /*line :282:35*/_Ctype_duckdb_init_info /*line :282:53*/) {
	instance := getPinned[tableFunctionData](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :283:71*/info; _cgoCheckPointer(_cgo0, nil); return /*line :283:76*/_Cfunc_duckdb_init_get_bind_data(_cgo0); }())
	instance.setColumnCount(info)
	initData := instance.fun.(parallelTableSource).Init()
	maxThreads :=  /*line :286:16*/_Ctype_idx_t /*line :286:23*/(initData.MaxThreads)
	func() { _cgo0 := /*line :287:32*/info; var _cgo1 _Ctype_idx_t = /*line :287:38*/maxThreads; _cgoCheckPointer(_cgo0, nil); /*line :287:49*/_Cfunc_duckdb_init_set_max_threads(_cgo0, _cgo1); }()
}

//export table_udf_local_init
func table_udf_local_init(info  /*line :291:32*/_Ctype_duckdb_init_info /*line :291:50*/) {
	instance := getPinned[tableFunctionData](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :292:71*/info; _cgoCheckPointer(_cgo0, nil); return /*line :292:76*/_Cfunc_duckdb_init_get_bind_data(_cgo0); }())
	localState := pinnedValue[any]{
		pinner: &runtime.Pinner{},
		value:  instance.fun.(parallelTableSource).NewLocalState(),
	}
	h := cgo.NewHandle(localState)
	localState.pinner.Pin(&h)
	func() { _cgo0 := /*line :299:30*/info; _cgoBase1 := /*line :299:51*/&h; _cgo1 := /*line :299:36*/unsafe.Pointer(_cgoBase1); var _cgo2 *[0]byte = _Ctype_duckdb_delete_callback_t /*line :299:82*/(_Cgo_ptr(_Cfpvar_fp_udf_delete_callback /*line :299:104*/)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); /*line :299:106*/_Cfunc_duckdb_init_set_init_data(_cgo0, _cgo1, _cgo2); }()
}

//export table_udf_row_callback
func table_udf_row_callback(info  /*line :303:34*/_Ctype_duckdb_function_info /*line :303:56*/, output  /*line :303:65*/_Ctype_duckdb_data_chunk /*line :303:84*/) {
	instance := getPinned[tableFunctionData](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :304:75*/info; _cgoCheckPointer(_cgo0, nil); return /*line :304:80*/_Cfunc_duckdb_function_get_bind_data(_cgo0); }())

	var chunk DataChunk
	err := chunk.initFromDuckDataChunk(output, true)
	if err != nil {
		setFuncError(info, err.Error())
		return
	}

	row := Row{
		chunk:      &chunk,
		projection: instance.projection,
	}
	maxSize := ( /*line :317:13*/_Cfunc_duckdb_vector_size /*line :317:32*/)()

	switch fun := instance.fun.(type) {
	case RowTableSource:
		// At the end of the loop row.r must be the index of the last row.
		for row.r = 0; row.r < maxSize; row.r++ {
			next, errRow := fun.FillRow(row)
			if errRow != nil {
				setFuncError(info, errRow.Error())
				break
			}
			if !next {
				break
			}
		}
	case ParallelRowTableSource:
		// At the end of the loop row.r must be the index of the last row.
		localState := getPinned[any](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :334:70*/info; _cgoCheckPointer(_cgo0, nil); return /*line :334:75*/_Cfunc_duckdb_function_get_local_init_data(_cgo0); }())
		for row.r = 0; row.r < maxSize; row.r++ {
			next, errRow := fun.FillRow(localState, row)
			if errRow != nil {
				setFuncError(info, errRow.Error())
				break
			}
			if !next {
				break
			}
		}
	}
	func() { _cgo0 := /*line :346:31*/output; var _cgo1 _Ctype_idx_t = /*line :346:39*/row.r; _cgoCheckPointer(_cgo0, nil); /*line :346:45*/_Cfunc_duckdb_data_chunk_set_size(_cgo0, _cgo1); }()
}

//export table_udf_chunk_callback
func table_udf_chunk_callback(info  /*line :350:36*/_Ctype_duckdb_function_info /*line :350:58*/, output  /*line :350:67*/_Ctype_duckdb_data_chunk /*line :350:86*/) {
	instance := getPinned[tableFunctionData](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :351:75*/info; _cgoCheckPointer(_cgo0, nil); return /*line :351:80*/_Cfunc_duckdb_function_get_bind_data(_cgo0); }())

	var chunk DataChunk
	err := chunk.initFromDuckDataChunk(output, true)
	if err != nil {
		setFuncError(info, err.Error())
		return
	}

	switch fun := instance.fun.(type) {
	case ChunkTableSource:
		err = fun.FillChunk(chunk)
	case ParallelChunkTableSource:
		localState := getPinned[*any](func() _cgo_unsafe.Pointer{ _cgo0 := /*line :364:71*/info; _cgoCheckPointer(_cgo0, nil); return /*line :364:76*/_Cfunc_duckdb_function_get_local_init_data(_cgo0); }())
		err = fun.FillChunk(localState, chunk)
	}
	if err != nil {
		setFuncError(info, err.Error())
	}
}

// RegisterTableUDF registers a user-defined table function.
// Projection pushdown is enabled by default.
func RegisterTableUDF[TFT TableFunction](c *sql.Conn, name string, f TFT) error {
	if name == "" {
		return getError(errAPI, errTableUDFNoName)
	}
	function := ( /*line :378:14*/_Cfunc_duckdb_create_table_function /*line :378:43*/)()

	// Set the name.
	cName := ( /*line :381:11*/_Cfunc_CString /*line :381:19*/)(name)
	defer func() func() { _cgo0 := /*line :382:22*/unsafe.Pointer(cName); return func() { _cgoCheckPointer(_cgo0, nil); /*line :382:44*/_Cfunc_duckdb_free(_cgo0); }}()()
	func() { _cgo0 := /*line :383:35*/function; var _cgo1 *_Ctype_char = /*line :383:45*/cName; _cgoCheckPointer(_cgo0, nil); /*line :383:51*/_Cfunc_duckdb_table_function_set_name(_cgo0, _cgo1); }()

	var config TableFunctionConfig

	// Pin the table function f.
	value := pinnedValue[TFT]{
		pinner: &runtime.Pinner{},
		value:  f,
	}
	h := cgo.NewHandle(value)
	value.pinner.Pin(&h)

	// Set the execution data, which is the table function f.
	func() { _cgo0 := /*line :397:3*/function; _cgoBase1 := /*line :398:18*/&h; _cgo1 := /*line :398:3*/unsafe.Pointer(_cgoBase1); var _cgo2 *[0]byte = _Ctype_duckdb_delete_callback_t /*line :399:29*/(_Cgo_ptr(_Cfpvar_fp_udf_delete_callback /*line :399:51*/)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); /*line :399:53*/_Cfunc_duckdb_table_function_set_extra_info(_cgo0, _cgo1, _cgo2); }()
	func() { _cgo0 := /*line :400:55*/function; var _cgo1 _Ctype__Bool = _Ctype_bool /*line :400:71*/(true); _cgoCheckPointer(_cgo0, nil); /*line :400:78*/_Cfunc_duckdb_table_function_supports_projection_pushdown(_cgo0, _cgo1); }()

	// Set the config.
	var x any = f
	switch tableFunc := x.(type) {
	case RowTableFunction:
		func() { _cgo0 := /*line :406:36*/function; var _cgo1 *[0]byte = _Ctype_init /*line :406:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_init /*line :406:69*/)); _cgoCheckPointer(_cgo0, nil); /*line :406:71*/_Cfunc_duckdb_table_function_set_init(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :407:36*/function; var _cgo1 *[0]byte = _Ctype_bind /*line :407:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_bind_row /*line :407:73*/)); _cgoCheckPointer(_cgo0, nil); /*line :407:75*/_Cfunc_duckdb_table_function_set_bind(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :408:40*/function; var _cgo1 *[0]byte = _Ctype_callback /*line :408:60*/(_Cgo_ptr(_Cfpvar_fp_table_udf_row_callback /*line :408:85*/)); _cgoCheckPointer(_cgo0, nil); /*line :408:87*/_Cfunc_duckdb_table_function_set_function(_cgo0, _cgo1); }()

		config = tableFunc.Config
		if tableFunc.BindArguments == nil {
			return getError(errAPI, errTableUDFMissingBindArgs)
		}

	case ChunkTableFunction:
		func() { _cgo0 := /*line :416:36*/function; var _cgo1 *[0]byte = _Ctype_init /*line :416:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_init /*line :416:69*/)); _cgoCheckPointer(_cgo0, nil); /*line :416:71*/_Cfunc_duckdb_table_function_set_init(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :417:36*/function; var _cgo1 *[0]byte = _Ctype_bind /*line :417:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_bind_chunk /*line :417:75*/)); _cgoCheckPointer(_cgo0, nil); /*line :417:77*/_Cfunc_duckdb_table_function_set_bind(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :418:40*/function; var _cgo1 *[0]byte = _Ctype_callback /*line :418:60*/(_Cgo_ptr(_Cfpvar_fp_table_udf_chunk_callback /*line :418:87*/)); _cgoCheckPointer(_cgo0, nil); /*line :418:89*/_Cfunc_duckdb_table_function_set_function(_cgo0, _cgo1); }()

		config = tableFunc.Config
		if tableFunc.BindArguments == nil {
			return getError(errAPI, errTableUDFMissingBindArgs)
		}

	case ParallelRowTableFunction:
		func() { _cgo0 := /*line :426:36*/function; var _cgo1 *[0]byte = _Ctype_init /*line :426:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_init_parallel /*line :426:78*/)); _cgoCheckPointer(_cgo0, nil); /*line :426:80*/_Cfunc_duckdb_table_function_set_init(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :427:36*/function; var _cgo1 *[0]byte = _Ctype_bind /*line :427:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_bind_parallel_row /*line :427:82*/)); _cgoCheckPointer(_cgo0, nil); /*line :427:84*/_Cfunc_duckdb_table_function_set_bind(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :428:40*/function; var _cgo1 *[0]byte = _Ctype_callback /*line :428:60*/(_Cgo_ptr(_Cfpvar_fp_table_udf_row_callback /*line :428:85*/)); _cgoCheckPointer(_cgo0, nil); /*line :428:87*/_Cfunc_duckdb_table_function_set_function(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :429:42*/function; var _cgo1 *[0]byte = _Ctype_init /*line :429:58*/(_Cgo_ptr(_Cfpvar_fp_table_udf_local_init /*line :429:81*/)); _cgoCheckPointer(_cgo0, nil); /*line :429:83*/_Cfunc_duckdb_table_function_set_local_init(_cgo0, _cgo1); }()

		config = tableFunc.Config
		if tableFunc.BindArguments == nil {
			return getError(errAPI, errTableUDFMissingBindArgs)
		}

	case ParallelChunkTableFunction:
		func() { _cgo0 := /*line :437:36*/function; var _cgo1 *[0]byte = _Ctype_init /*line :437:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_init_parallel /*line :437:78*/)); _cgoCheckPointer(_cgo0, nil); /*line :437:80*/_Cfunc_duckdb_table_function_set_init(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :438:36*/function; var _cgo1 *[0]byte = _Ctype_bind /*line :438:52*/(_Cgo_ptr(_Cfpvar_fp_table_udf_bind_parallel_chunk /*line :438:84*/)); _cgoCheckPointer(_cgo0, nil); /*line :438:86*/_Cfunc_duckdb_table_function_set_bind(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :439:40*/function; var _cgo1 *[0]byte = _Ctype_callback /*line :439:60*/(_Cgo_ptr(_Cfpvar_fp_table_udf_chunk_callback /*line :439:87*/)); _cgoCheckPointer(_cgo0, nil); /*line :439:89*/_Cfunc_duckdb_table_function_set_function(_cgo0, _cgo1); }()
		func() { _cgo0 := /*line :440:42*/function; var _cgo1 *[0]byte = _Ctype_init /*line :440:58*/(_Cgo_ptr(_Cfpvar_fp_table_udf_local_init /*line :440:81*/)); _cgoCheckPointer(_cgo0, nil); /*line :440:83*/_Cfunc_duckdb_table_function_set_local_init(_cgo0, _cgo1); }()

		config = tableFunc.Config
		if tableFunc.BindArguments == nil {
			return getError(errAPI, errTableUDFMissingBindArgs)
		}

	default:
		return getError(errInternal, nil)
	}

	// Set the arguments.
	for _, t := range config.Arguments {
		if t == nil {
			return getError(errAPI, errTableUDFArgumentIsNil)
		}
		logicalType := t.logicalType()
		func() { _cgo0 := /*line :457:41*/function; _cgo1 := /*line :457:51*/logicalType; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :457:63*/_Cfunc_duckdb_table_function_add_parameter(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :458:33*/&logicalType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :458:46*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	}

	// Set the named arguments.
	for arg, t := range config.NamedArguments {
		if t == nil {
			return getError(errAPI, errTableUDFArgumentIsNil)
		}
		logicalType := t.logicalType()
		cArg := ( /*line :467:11*/_Cfunc_CString /*line :467:19*/)(arg)
		func() { _cgo0 := /*line :468:47*/function; var _cgo1 *_Ctype_char = /*line :468:57*/cArg; _cgo2 := /*line :468:63*/logicalType; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo2, nil); /*line :468:75*/_Cfunc_duckdb_table_function_add_named_parameter(_cgo0, _cgo1, _cgo2); }()
		func() { _cgoBase0 := /*line :469:33*/&logicalType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :469:46*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
		func() { _cgo0 := /*line :470:17*/unsafe.Pointer(cArg); _cgoCheckPointer(_cgo0, nil); /*line :470:38*/_Cfunc_duckdb_free(_cgo0); }()
	}

	// Register the function on the underlying driver connection exposed by c.Raw.
	err := c.Raw(func(driverConn any) error {
		con := driverConn.(*conn)
		state := func() _Ctype_duckdb_state{ _cgo0 := /*line :476:45*/con.duckdbCon; _cgo1 := /*line :476:60*/function; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :476:69*/_Cfunc_duckdb_register_table_function(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :477:35*/&function; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :477:45*/_Cfunc_duckdb_destroy_table_function(_cgo0); }()
		if state == ( /*line :478:15*/_Ciconst_DuckDBError /*line :478:27*/) {
			return getError(errAPI, errTableUDFCreate)
		}
		return nil
	})
	return err
}
