// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/type_info.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"reflect"
	"runtime"
	"unsafe"
)

type structEntry struct {
	TypeInfo
	name string
}

// StructEntry is an interface to provide STRUCT entry information.
type StructEntry interface {
	// Info returns a STRUCT entry's type information.
	Info() TypeInfo
	// Name returns a STRUCT entry's name.
	Name() string
}

// NewStructEntry returns a STRUCT entry.
// info contains information about the entry's type, and name holds the entry's name.
func NewStructEntry(info TypeInfo, name string) (StructEntry, error) {
	if name == "" {
		return nil, getError(errAPI, errEmptyName)
	}

	return &structEntry{
		TypeInfo: info,
		name:     name,
	}, nil
}

// Info returns a STRUCT entry's type information.
func (entry *structEntry) Info() TypeInfo {
	return entry.TypeInfo
}

// Name returns a STRUCT entry's name.
func (entry *structEntry) Name() string {
	return entry.name
}

type baseTypeInfo struct {
	Type
	structEntries []StructEntry
	decimalWidth  uint8
	decimalScale  uint8
	// The internal type for ENUM and DECIMAL values.
	internalType Type
}

type vectorTypeInfo struct {
	baseTypeInfo
	dict map[string]uint32
}

type typeInfo struct {
	baseTypeInfo
	childTypes []TypeInfo
	enumNames  []string
}

// TypeInfo is an interface for a DuckDB type.
type TypeInfo interface {
	// InternalType returns the Type.
	InternalType() Type
	logicalType()  /*line :74:16*/_Ctype_duckdb_logical_type /*line :74:37*/
}

func (info *typeInfo) InternalType() Type {
	return info.Type
}

// NewTypeInfo returns type information for DuckDB's primitive types.
// It returns the TypeInfo, if the Type parameter is a valid primitive type.
// Else, it returns nil, and an error.
// Valid types are:
// TYPE_[BOOLEAN, TINYINT, SMALLINT, INTEGER, BIGINT, UTINYINT, USMALLINT, UINTEGER,
// UBIGINT, FLOAT, DOUBLE, TIMESTAMP, DATE, TIME, INTERVAL, HUGEINT, VARCHAR, BLOB,
// TIMESTAMP_S, TIMESTAMP_MS, TIMESTAMP_NS, UUID, TIMESTAMP_TZ, ANY].
func NewTypeInfo(t Type) (TypeInfo, error) {
	name, inMap := unsupportedTypeToStringMap[t]
	if inMap && t != TYPE_ANY {
		return nil, getError(errAPI, unsupportedTypeError(name))
	}

	switch t {
	case TYPE_DECIMAL:
		return nil, getError(errAPI, tryOtherFuncError(funcName(NewDecimalInfo)))
	case TYPE_ENUM:
		return nil, getError(errAPI, tryOtherFuncError(funcName(NewEnumInfo)))
	case TYPE_LIST:
		return nil, getError(errAPI, tryOtherFuncError(funcName(NewListInfo)))
	case TYPE_STRUCT:
		return nil, getError(errAPI, tryOtherFuncError(funcName(NewStructInfo)))
	case TYPE_MAP:
		return nil, getError(errAPI, tryOtherFuncError(funcName(NewMapInfo)))
	case TYPE_SQLNULL:
		return nil, getError(errAPI, unsupportedTypeError(typeToStringMap[t]))
	}

	return &typeInfo{
		baseTypeInfo: baseTypeInfo{Type: t},
	}, nil
}

// NewDecimalInfo returns DECIMAL type information.
// Its input parameters are the width and scale of the DECIMAL type.
func NewDecimalInfo(width uint8, scale uint8) (TypeInfo, error) {
	if width < 1 || width > max_decimal_width {
		return nil, getError(errAPI, errInvalidDecimalWidth)
	}
	if scale > width {
		return nil, getError(errAPI, errInvalidDecimalScale)
	}

	return &typeInfo{
		baseTypeInfo: baseTypeInfo{
			Type:         TYPE_DECIMAL,
			decimalWidth: width,
			decimalScale: scale,
		},
	}, nil
}

// NewEnumInfo returns ENUM type information.
// Its input parameters are the dictionary values.
func NewEnumInfo(first string, others ...string) (TypeInfo, error) {
	// Check for duplicate names.
	m := map[string]bool{}
	m[first] = true
	for _, name := range others {
		_, inMap := m[name]
		if inMap {
			return nil, getError(errAPI, duplicateNameError(name))
		}
		m[name] = true
	}

	info := &typeInfo{
		baseTypeInfo: baseTypeInfo{
			Type: TYPE_ENUM,
		},
		enumNames: make([]string, 0),
	}

	info.enumNames = append(info.enumNames, first)
	info.enumNames = append(info.enumNames, others...)
	return info, nil
}

// NewListInfo returns LIST type information.
// childInfo contains the type information of the LIST's elements.
func NewListInfo(childInfo TypeInfo) (TypeInfo, error) {
	if childInfo == nil {
		return nil, getError(errAPI, interfaceIsNilError("childInfo"))
	}

	info := &typeInfo{
		baseTypeInfo: baseTypeInfo{Type: TYPE_LIST},
		childTypes:   make([]TypeInfo, 1),
	}
	info.childTypes[0] = childInfo
	return info, nil
}

// NewStructInfo returns STRUCT type information.
// Its input parameters are the STRUCT entries.
func NewStructInfo(firstEntry StructEntry, others ...StructEntry) (TypeInfo, error) {
	if firstEntry == nil {
		return nil, getError(errAPI, interfaceIsNilError("firstEntry"))
	}
	if firstEntry.Info() == nil {
		return nil, getError(errAPI, interfaceIsNilError("firstEntry.Info()"))
	}
	for i, entry := range others {
		if entry == nil {
			return nil, getError(errAPI, addIndexToError(interfaceIsNilError("entry"), i))
		}
		if entry.Info() == nil {
			return nil, getError(errAPI, addIndexToError(interfaceIsNilError("entry.Info()"), i))
		}
	}

	// Check for duplicate names.
	m := map[string]bool{}
	m[firstEntry.Name()] = true
	for _, entry := range others {
		name := entry.Name()
		_, inMap := m[name]
		if inMap {
			return nil, getError(errAPI, duplicateNameError(name))
		}
		m[name] = true
	}

	info := &typeInfo{
		baseTypeInfo: baseTypeInfo{
			Type:          TYPE_STRUCT,
			structEntries: make([]StructEntry, 0),
		},
	}
	info.structEntries = append(info.structEntries, firstEntry)
	info.structEntries = append(info.structEntries, others...)
	return info, nil
}

// NewMapInfo returns MAP type information.
// keyInfo contains the type information of the MAP keys.
// valueInfo contains the type information of the MAP values.
func NewMapInfo(keyInfo TypeInfo, valueInfo TypeInfo) (TypeInfo, error) {
	if keyInfo == nil {
		return nil, getError(errAPI, interfaceIsNilError("keyInfo"))
	}
	if valueInfo == nil {
		return nil, getError(errAPI, interfaceIsNilError("valueInfo"))
	}

	info := &typeInfo{
		baseTypeInfo: baseTypeInfo{Type: TYPE_MAP},
		childTypes:   make([]TypeInfo, 2),
	}
	info.childTypes[0] = keyInfo
	info.childTypes[1] = valueInfo
	return info, nil
}

func (info *typeInfo) logicalType()  /*line :235:37*/_Ctype_duckdb_logical_type /*line :235:58*/ {
	switch info.Type {
	case TYPE_BOOLEAN, TYPE_TINYINT, TYPE_SMALLINT, TYPE_INTEGER, TYPE_BIGINT, TYPE_UTINYINT, TYPE_USMALLINT,
		TYPE_UINTEGER, TYPE_UBIGINT, TYPE_FLOAT, TYPE_DOUBLE, TYPE_TIMESTAMP, TYPE_TIMESTAMP_S, TYPE_TIMESTAMP_MS,
		TYPE_TIMESTAMP_NS, TYPE_TIMESTAMP_TZ, TYPE_DATE, TYPE_TIME, TYPE_TIME_TZ, TYPE_INTERVAL, TYPE_HUGEINT, TYPE_VARCHAR,
		TYPE_BLOB, TYPE_UUID, TYPE_ANY:
		return ( /*line :241:10*/_Cfunc_duckdb_create_logical_type /*line :241:37*/)( /*line :241:39*/_Ctype_duckdb_type /*line :241:52*/(info.Type))

	case TYPE_DECIMAL:
		return ( /*line :244:10*/_Cfunc_duckdb_create_decimal_type /*line :244:37*/)( /*line :244:39*/_Ctype_uint8_t /*line :244:48*/(info.decimalWidth),  /*line :244:69*/_Ctype_uint8_t /*line :244:78*/(info.decimalScale))
	case TYPE_ENUM:
		return info.logicalEnumType()
	case TYPE_LIST:
		return info.logicalListType()
	case TYPE_STRUCT:
		return info.logicalStructType()
	case TYPE_MAP:
		return info.logicalMapType()
	}
	return nil
}

func (info *typeInfo) logicalEnumType()  /*line :257:41*/_Ctype_duckdb_logical_type /*line :257:62*/ {
	count := len(info.enumNames)
	size :=  /*line :259:10*/_Ctype_size_t /*line :259:18*/(unsafe.Sizeof((* /*line :259:35*/_Ctype_char /*line :259:41*/)(nil)))
	names := (*[1 << 31]* /*line :260:23*/_Ctype_char /*line :260:29*/)(( /*line :260:31*/_Cfunc__CMalloc /*line :260:38*/)( /*line :260:40*/_Ctype_size_t /*line :260:48*/(count) * size))

	for i, name := range info.enumNames {
		(*names)[i] = ( /*line :263:17*/_Cfunc_CString /*line :263:25*/)(name)
	}
	cNames := (** /*line :265:15*/_Ctype_char /*line :265:21*/)(unsafe.Pointer(names))
	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :266:43*/cNames; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :266:58*/(count); _cgoCheckPointer(_cgo0, nil); return /*line :266:66*/_Cfunc_duckdb_create_enum_type(_cgo0, _cgo1); }()

	for i := 0; i < count; i++ {
		func() { _cgo0 := /*line :269:17*/unsafe.Pointer((*names)[i]); _cgoCheckPointer(_cgo0, nil); /*line :269:45*/_Cfunc_duckdb_free(_cgo0); }()
	}
	func() { _cgo0 := /*line :271:16*/unsafe.Pointer(names); _cgoCheckPointer(_cgo0, nil); /*line :271:38*/_Cfunc_duckdb_free(_cgo0); }()
	return logicalType
}

func (info *typeInfo) logicalListType()  /*line :275:41*/_Ctype_duckdb_logical_type /*line :275:62*/ {
	child := info.childTypes[0].logicalType()
	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :277:43*/child; _cgoCheckPointer(_cgo0, nil); return /*line :277:49*/_Cfunc_duckdb_create_list_type(_cgo0); }()
	func() { _cgoBase0 := /*line :278:32*/&child; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :278:39*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	return logicalType
}

func (info *typeInfo) logicalStructType()  /*line :282:43*/_Ctype_duckdb_logical_type /*line :282:64*/ {
	count := len(info.structEntries)
	size :=  /*line :284:10*/_Ctype_size_t /*line :284:18*/(unsafe.Sizeof( /*line :284:33*/_Ctype_duckdb_logical_type /*line :284:54*/(nil)))
	types := (*[1 << 31] /*line :285:22*/_Ctype_duckdb_logical_type /*line :285:43*/)(( /*line :285:45*/_Cfunc__CMalloc /*line :285:52*/)( /*line :285:54*/_Ctype_size_t /*line :285:62*/(count) * size))

	size =  /*line :287:9*/_Ctype_size_t /*line :287:17*/(unsafe.Sizeof((* /*line :287:34*/_Ctype_char /*line :287:40*/)(nil)))
	names := (*[1 << 31]* /*line :288:23*/_Ctype_char /*line :288:29*/)(( /*line :288:31*/_Cfunc__CMalloc /*line :288:38*/)( /*line :288:40*/_Ctype_size_t /*line :288:48*/(count) * size))

	for i, entry := range info.structEntries {
		(*types)[i] = entry.Info().logicalType()
		(*names)[i] = ( /*line :292:17*/_Cfunc_CString /*line :292:25*/)(entry.Name())
	}

	cTypes := (* /*line :295:14*/_Ctype_duckdb_logical_type /*line :295:35*/)(unsafe.Pointer(types))
	cNames := (** /*line :296:15*/_Ctype_char /*line :296:21*/)(unsafe.Pointer(names))
	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :297:45*/cTypes; _cgo1 := /*line :297:53*/cNames; var _cgo2 _Ctype_idx_t = _Ctype_idx_t /*line :297:68*/(count); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :297:76*/_Cfunc_duckdb_create_struct_type(_cgo0, _cgo1, _cgo2); }()

	for i := 0; i < count; i++ {
		func() { _cgoIndex0 := &/*line :300:34*/types; _cgo0 := /*line :300:33*/&(*_cgoIndex0)[i]; _cgoCheckPointer(_cgo0, *_cgoIndex0); /*line :300:43*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
		func() { _cgo0 := /*line :301:17*/unsafe.Pointer((*names)[i]); _cgoCheckPointer(_cgo0, nil); /*line :301:45*/_Cfunc_duckdb_free(_cgo0); }()
	}
	func() { _cgo0 := /*line :303:16*/unsafe.Pointer(types); _cgoCheckPointer(_cgo0, nil); /*line :303:38*/_Cfunc_duckdb_free(_cgo0); }()
	func() { _cgo0 := /*line :304:16*/unsafe.Pointer(names); _cgoCheckPointer(_cgo0, nil); /*line :304:38*/_Cfunc_duckdb_free(_cgo0); }()
	return logicalType
}

func (info *typeInfo) logicalMapType()  /*line :308:40*/_Ctype_duckdb_logical_type /*line :308:61*/ {
	key := info.childTypes[0].logicalType()
	value := info.childTypes[1].logicalType()
	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :311:42*/key; _cgo1 := /*line :311:47*/value; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :311:53*/_Cfunc_duckdb_create_map_type(_cgo0, _cgo1); }()

	func() { _cgoBase0 := /*line :313:32*/&key; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :313:37*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	func() { _cgoBase0 := /*line :314:32*/&value; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :314:39*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	return logicalType
}

func funcName(i interface{}) string {
	return runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()
}
