// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/types.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/mitchellh/mapstructure"
)

type numericType interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | float32 | float64
}

const uuid_length = 16

type UUID [uuid_length]byte

func (u *UUID) Scan(v any) error {
	if n := copy(u[:], v.([]byte)); n != uuid_length {
		return fmt.Errorf("invalid UUID length: %d", n)
	}
	return nil
}

// duckdb_hugeint is composed of (lower, upper) components.
// The value is computed as: upper * 2^64 + lower

func hugeIntToUUID(hi  /*line :34:23*/_Ctype_duckdb_hugeint /*line :34:39*/) []byte {
	var uuid [uuid_length]byte
	// We need to flip the sign bit of the signed hugeint to transform it to UUID bytes
	binary.BigEndian.PutUint64(uuid[:8], uint64(hi.upper)^1<<63)
	binary.BigEndian.PutUint64(uuid[8:], uint64(hi.lower))
	return uuid[:]
}

func uuidToHugeInt(uuid UUID)  /*line :42:31*/_Ctype_duckdb_hugeint /*line :42:47*/ {
	var dt  /*line :43:9*/_Ctype_duckdb_hugeint /*line :43:25*/
	upper := binary.BigEndian.Uint64(uuid[:8])
	// flip the sign bit
	upper = upper ^ (1 << 63)
	dt.upper =  /*line :47:13*/_Ctype_int64_t /*line :47:22*/(upper)
	dt.lower =  /*line :48:13*/_Ctype_uint64_t /*line :48:23*/(binary.BigEndian.Uint64(uuid[8:]))
	return dt
}

func hugeIntToNative(hi  /*line :52:25*/_Ctype_duckdb_hugeint /*line :52:41*/) *big.Int {
	i := big.NewInt(int64(hi.upper))
	i.Lsh(i, 64)
	i.Add(i, new(big.Int).SetUint64(uint64(hi.lower)))
	return i
}

func hugeIntFromNative(i *big.Int) ( /*line :59:37*/_Ctype_duckdb_hugeint /*line :59:53*/, error) {
	d := big.NewInt(1)
	d.Lsh(d, 64)

	q := new(big.Int)
	r := new(big.Int)
	q.DivMod(i, d, r)

	if !q.IsInt64() {
		return  /*line :68:10*/_Ctype_duckdb_hugeint /*line :68:26*/{}, fmt.Errorf("big.Int(%s) is too big for HUGEINT", i.String())
	}

	return  /*line :71:9*/_Ctype_duckdb_hugeint /*line :71:25*/{
		lower:  /*line :72:10*/_Ctype_uint64_t /*line :72:20*/(r.Uint64()),
		upper:  /*line :73:10*/_Ctype_int64_t /*line :73:19*/(q.Int64()),
	}, nil
}

type Map map[any]any

func (m *Map) Scan(v any) error {
	data, ok := v.(Map)
	if !ok {
		return fmt.Errorf("invalid type `%T` for scanning `Map`, expected `Map`", data)
	}

	*m = data
	return nil
}

func mapKeysField() string {
	return "key"
}

func mapValuesField() string {
	return "value"
}

type Interval struct {
	Days   int32 `json:"days"`
	Months int32 `json:"months"`
	Micros int64 `json:"micros"`
}

// Use as the `Scanner` type for any composite types (maps, lists, structs)
type Composite[T any] struct {
	t T
}

func (s Composite[T]) Get() T {
	return s.t
}

func (s *Composite[T]) Scan(v any) error {
	return mapstructure.Decode(v, &s.t)
}

const max_decimal_width = 38

type Decimal struct {
	Width uint8
	Scale uint8
	Value *big.Int
}

func (d *Decimal) Float64() float64 {
	scale := big.NewInt(int64(d.Scale))
	factor := new(big.Float).SetInt(new(big.Int).Exp(big.NewInt(10), scale, nil))
	value := new(big.Float).SetInt(d.Value)
	value.Quo(value, factor)
	f, _ := value.Float64()
	return f
}

func (d *Decimal) toString() string {
	return fmt.Sprintf("DECIMAL(%d,%d)", d.Width, d.Scale)
}
