// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/vector_setters.go:1:1
package duckdb; import _cgo_unsafe "unsafe"

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"math/big"
	"reflect"
	"time"
	"unsafe"
)

// secondsPerDay to calculate the days since 1970-01-01.
const secondsPerDay = 24 * 60 * 60

// fnSetVectorValue is the setter callback function for any (nested) vector.
type fnSetVectorValue func(vec *vector, rowIdx  /*line :19:48*/_Ctype_idx_t /*line :19:55*/, val any) error

func (vec *vector) setNull(rowIdx  /*line :21:35*/_Ctype_idx_t /*line :21:42*/) {
	( /*line :22:2*/_Cfunc_duckdb_validity_set_row_invalid /*line :22:34*/)(vec.mask, rowIdx)
	if vec.Type == TYPE_STRUCT {
		for i := 0; i < len(vec.childVectors); i++ {
			vec.childVectors[i].setNull(rowIdx)
		}
	}
}

func setPrimitive[T any](vec *vector, rowIdx  /*line :30:46*/_Ctype_idx_t /*line :30:53*/, v T) {
	xs := (*[1 << 31]T)(vec.ptr)
	xs[rowIdx] = v
}

func setNumeric[S any, T numericType](vec *vector, rowIdx  /*line :35:59*/_Ctype_idx_t /*line :35:66*/, val S) error {
	var fv T
	switch v := any(val).(type) {
	case uint8:
		fv = T(v)
	case int8:
		fv = T(v)
	case uint16:
		fv = T(v)
	case int16:
		fv = T(v)
	case uint32:
		fv = T(v)
	case int32:
		fv = T(v)
	case uint64:
		fv = T(v)
	case int64:
		fv = T(v)
	case uint:
		fv = T(v)
	case int:
		fv = T(v)
	case float32:
		fv = T(v)
	case float64:
		fv = T(v)
	case Decimal:
		if v.Value == nil {
			return castError(reflect.TypeOf(val).String(), reflect.TypeOf(fv).String())
		}
		if v.Value.IsUint64() {
			fv = T(v.Value.Uint64())
		} else {
			fv = T(v.Value.Int64())
		}
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(fv).String())
	}
	setPrimitive(vec, rowIdx, fv)
	return nil
}

func setBool[S any](vec *vector, rowIdx  /*line :78:41*/_Ctype_idx_t /*line :78:48*/, val S) error {
	var b bool
	switch v := any(val).(type) {
	case bool:
		b = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(b).String())
	}
	setPrimitive(vec, rowIdx, b)
	return nil
}

func setTS[S any](vec *vector, rowIdx  /*line :90:39*/_Ctype_idx_t /*line :90:46*/, val S) error {
	var ti time.Time
	switch v := any(val).(type) {
	case time.Time:
		ti = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(ti).String())
	}

	var ticks int64
	switch vec.Type {
	case TYPE_TIMESTAMP, TYPE_TIMESTAMP_TZ:
		year := ti.UTC().Year()
		if year < -290307 || year > 294246 {
			return conversionError(year, -290307, 294246)
		}
		ticks = ti.UTC().UnixMicro()
	case TYPE_TIMESTAMP_S:
		ticks = ti.UTC().Unix()
	case TYPE_TIMESTAMP_MS:
		ticks = ti.UTC().UnixMilli()
	case TYPE_TIMESTAMP_NS:
		year := ti.UTC().Year()
		if year < 1678 || year > 2262 {
			return conversionError(year, -290307, 294246)
		}
		ticks = ti.UTC().UnixNano()
	}
	var ts  /*line :118:9*/_Ctype_duckdb_timestamp /*line :118:27*/
	ts.micros =  /*line :119:14*/_Ctype_int64_t /*line :119:23*/(ticks)
	setPrimitive(vec, rowIdx, ts)
	return nil
}

func setDate[S any](vec *vector, rowIdx  /*line :124:41*/_Ctype_idx_t /*line :124:48*/, val S) error {
	var ti time.Time
	switch v := any(val).(type) {
	case time.Time:
		ti = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(ti).String())
	}

	days := int32(ti.UTC().Unix() / secondsPerDay)
	var date  /*line :134:11*/_Ctype_duckdb_date /*line :134:24*/
	date.days =  /*line :135:14*/_Ctype_int32_t /*line :135:23*/(days)
	setPrimitive(vec, rowIdx, date)
	return nil
}

func setTime[S any](vec *vector, rowIdx  /*line :140:41*/_Ctype_idx_t /*line :140:48*/, val S) error {
	var ti time.Time
	switch v := any(val).(type) {
	case time.Time:
		ti = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(ti).String())
	}

	// DuckDB stores time as microseconds since 00:00:00.
	ti = ti.UTC()
	base := time.Date(1970, time.January, 1, ti.Hour(), ti.Minute(), ti.Second(), ti.Nanosecond(), time.UTC)
	ticks := base.UnixMicro()

	switch vec.Type {
	case TYPE_TIME:
		var duckTime  /*line :156:16*/_Ctype_duckdb_time /*line :156:29*/
		duckTime.micros =  /*line :157:21*/_Ctype_int64_t /*line :157:30*/(ticks)
		setPrimitive(vec, rowIdx, duckTime)
	case TYPE_TIME_TZ:
		// The UTC offset is 0.
		duckTimeTZ := ( /*line :161:17*/_Cfunc_duckdb_create_time_tz /*line :161:39*/)( /*line :161:41*/_Ctype_int64_t /*line :161:50*/(ticks), 0)
		setPrimitive(vec, rowIdx, duckTimeTZ)
	}
	return nil
}

func setInterval[S any](vec *vector, rowIdx  /*line :167:45*/_Ctype_idx_t /*line :167:52*/, val S) error {
	var interval Interval
	switch v := any(val).(type) {
	case Interval:
		interval = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(interval).String())
	}
	var interval2  /*line :175:16*/_Ctype_duckdb_interval /*line :175:33*/
	interval2.days =  /*line :176:19*/_Ctype_int32_t /*line :176:28*/(interval.Days)
	interval2.months =  /*line :177:21*/_Ctype_int32_t /*line :177:30*/(interval.Months)
	interval2.micros =  /*line :178:21*/_Ctype_int64_t /*line :178:30*/(interval.Micros)
	setPrimitive(vec, rowIdx, interval2)
	return nil
}

func setHugeint[S any](vec *vector, rowIdx  /*line :183:44*/_Ctype_idx_t /*line :183:51*/, val S) error {
	var err error
	var fv  /*line :185:9*/_Ctype_duckdb_hugeint /*line :185:25*/
	switch v := any(val).(type) {
	case uint8:
		fv =  /*line :188:8*/_Ctype_duckdb_hugeint /*line :188:24*/{lower:  /*line :188:32*/_Ctype_uint64_t /*line :188:42*/(v)}
	case int8:
		fv =  /*line :190:8*/_Ctype_duckdb_hugeint /*line :190:24*/{lower:  /*line :190:32*/_Ctype_uint64_t /*line :190:42*/(v)}
	case uint16:
		fv =  /*line :192:8*/_Ctype_duckdb_hugeint /*line :192:24*/{lower:  /*line :192:32*/_Ctype_uint64_t /*line :192:42*/(v)}
	case int16:
		fv =  /*line :194:8*/_Ctype_duckdb_hugeint /*line :194:24*/{lower:  /*line :194:32*/_Ctype_uint64_t /*line :194:42*/(v)}
	case uint32:
		fv =  /*line :196:8*/_Ctype_duckdb_hugeint /*line :196:24*/{lower:  /*line :196:32*/_Ctype_uint64_t /*line :196:42*/(v)}
	case int32:
		fv =  /*line :198:8*/_Ctype_duckdb_hugeint /*line :198:24*/{lower:  /*line :198:32*/_Ctype_uint64_t /*line :198:42*/(v)}
	case uint64:
		fv =  /*line :200:8*/_Ctype_duckdb_hugeint /*line :200:24*/{lower:  /*line :200:32*/_Ctype_uint64_t /*line :200:42*/(v)}
	case int64:
		if fv, err = hugeIntFromNative(big.NewInt(v)); err != nil {
			return err
		}
	case uint:
		fv =  /*line :206:8*/_Ctype_duckdb_hugeint /*line :206:24*/{lower:  /*line :206:32*/_Ctype_uint64_t /*line :206:42*/(v)}
	case int:
		if fv, err = hugeIntFromNative(big.NewInt(int64(v))); err != nil {
			return err
		}
	case float32:
		if fv, err = hugeIntFromNative(big.NewInt(int64(v))); err != nil {
			return err
		}
	case float64:
		if fv, err = hugeIntFromNative(big.NewInt(int64(v))); err != nil {
			return err
		}
	case *big.Int:
		if v == nil {
			return castError(reflect.TypeOf(val).String(), reflect.TypeOf(fv).String())
		}
		if fv, err = hugeIntFromNative(v); err != nil {
			return err
		}
	case Decimal:
		if v.Value == nil {
			return castError(reflect.TypeOf(val).String(), reflect.TypeOf(fv).String())
		}
		if fv, err = hugeIntFromNative(v.Value); err != nil {
			return err
		}
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(fv).String())
	}
	setPrimitive(vec, rowIdx, fv)
	return nil
}

func setBytes[S any](vec *vector, rowIdx  /*line :240:42*/_Ctype_idx_t /*line :240:49*/, val S) error {
	var cStr * /*line :241:12*/_Ctype_char /*line :241:18*/
	var length int
	switch v := any(val).(type) {
	case string:
		cStr = ( /*line :245:10*/_Cfunc_CString /*line :245:18*/)(v)
		defer func() func() { _cgo0 := /*line :246:23*/unsafe.Pointer(cStr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :246:44*/_Cfunc_duckdb_free(_cgo0); }}()()
		length = len(v)
	case []byte:
		cStr = (* /*line :249:12*/_Ctype_char /*line :249:18*/)(func() _cgo_unsafe.Pointer{ _cgo0 := /*line :249:29*/v; _cgoCheckPointer(_cgo0, nil); return /*line :249:31*/_Cfunc_CBytes(_cgo0); }())
		defer func() func() { _cgo0 := /*line :250:23*/unsafe.Pointer(cStr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :250:44*/_Cfunc_duckdb_free(_cgo0); }}()()
		length = len(v)
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(cStr).String())
	}

	func() { _cgo0 := /*line :256:44*/vec.duckdbVector; var _cgo1 _Ctype_idx_t = /*line :256:62*/rowIdx; var _cgo2 *_Ctype_char = /*line :256:70*/cStr; var _cgo3 _Ctype_idx_t = _Ctype_idx_t /*line :256:83*/(length); _cgoCheckPointer(_cgo0, nil); /*line :256:92*/_Cfunc_duckdb_vector_assign_string_element_len(_cgo0, _cgo1, _cgo2, _cgo3); }()
	return nil
}

func setDecimal[S any](vec *vector, rowIdx  /*line :260:44*/_Ctype_idx_t /*line :260:51*/, val S) error {
	switch vec.internalType {
	case TYPE_SMALLINT:
		return setNumeric[S, int16](vec, rowIdx, val)
	case TYPE_INTEGER:
		return setNumeric[S, int32](vec, rowIdx, val)
	case TYPE_BIGINT:
		return setNumeric[S, int64](vec, rowIdx, val)
	case TYPE_HUGEINT:
		return setHugeint(vec, rowIdx, val)
	}
	return nil
}

func setEnum[S any](vec *vector, rowIdx  /*line :274:41*/_Ctype_idx_t /*line :274:48*/, val S) error {
	var str string
	switch v := any(val).(type) {
	case string:
		str = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(str).String())
	}

	if v, ok := vec.dict[str]; ok {
		switch vec.internalType {
		case TYPE_UTINYINT:
			return setNumeric[uint32, int8](vec, rowIdx, v)
		case TYPE_SMALLINT:
			return setNumeric[uint32, int16](vec, rowIdx, v)
		case TYPE_INTEGER:
			return setNumeric[uint32, int32](vec, rowIdx, v)
		case TYPE_BIGINT:
			return setNumeric[uint32, int64](vec, rowIdx, v)
		}
	} else {
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(str).String())
	}
	return nil
}

func setList[S any](vec *vector, rowIdx  /*line :300:41*/_Ctype_idx_t /*line :300:48*/, val S) error {
	var list []any
	switch v := any(val).(type) {
	case []any:
		list = v
	default:
		kind := reflect.TypeOf(val).Kind()
		if kind != reflect.Array && kind != reflect.Slice {
			return castError(reflect.TypeOf(val).String(), reflect.TypeOf(list).String())
		}
		// Insert the values into the child vector.
		rv := reflect.ValueOf(val)
		list = make([]any, rv.Len())

		for i := 0; i < rv.Len(); i++ {
			idx := rv.Index(i)
			if vec.canNil(idx) && idx.IsNil() {
				list[i] = nil
				continue
			}

			list[i] = idx.Interface()
		}
	}
	childVectorSize := func() _Ctype_idx_t{ _cgo0 := /*line :324:51*/vec.duckdbVector; _cgoCheckPointer(_cgo0, nil); return /*line :324:68*/_Cfunc_duckdb_list_vector_get_size(_cgo0); }()

	// Set the offset and length of the list vector using the current size of the child vector.
	listEntry :=  /*line :327:15*/_Ctype_duckdb_list_entry /*line :327:34*/{
		offset:  /*line :328:11*/_Ctype_idx_t /*line :328:18*/(childVectorSize),
		length:  /*line :329:11*/_Ctype_idx_t /*line :329:18*/(len(list)),
	}
	setPrimitive(vec, rowIdx, listEntry)

	newLength :=  /*line :333:15*/_Ctype_idx_t /*line :333:22*/(len(list)) + childVectorSize
	vec.resizeListVector(newLength)

	// Insert the values into the child vector.
	childVector := &vec.childVectors[0]
	for i, entry := range list {
		offset :=  /*line :339:13*/_Ctype_idx_t /*line :339:20*/(i) + childVectorSize
		err := childVector.setFn(childVector, offset, entry)
		if err != nil {
			return err
		}
	}
	return nil
}

func setStruct[S any](vec *vector, rowIdx  /*line :348:43*/_Ctype_idx_t /*line :348:50*/, val S) error {
	var m map[string]any
	switch v := any(val).(type) {
	case map[string]any:
		m = v
	default:
		// FIXME: Add support for all map types.

		// Catch mismatching types.
		goType := reflect.TypeOf(val)
		if reflect.TypeOf(val).Kind() != reflect.Struct {
			return castError(goType.String(), reflect.Struct.String())
		}

		m = make(map[string]any)
		rv := reflect.ValueOf(val)
		structType := rv.Type()

		for i := 0; i < structType.NumField(); i++ {
			if !rv.Field(i).CanInterface() {
				continue
			}
			fieldName := structType.Field(i).Name
			if name, ok := structType.Field(i).Tag.Lookup("db"); ok {
				fieldName = name
			}
			if _, ok := m[fieldName]; ok {
				return duplicateNameError(fieldName)
			}
			m[fieldName] = rv.Field(i).Interface()
		}
	}

	for i := 0; i < len(vec.childVectors); i++ {
		child := &vec.childVectors[i]
		name := vec.structEntries[i].Name()
		v, ok := m[name]
		if !ok {
			return structFieldError("missing field", name)
		}
		err := child.setFn(child, rowIdx, v)
		if err != nil {
			return err
		}
	}
	return nil
}

func setMap[S any](vec *vector, rowIdx  /*line :396:40*/_Ctype_idx_t /*line :396:47*/, val S) error {
	var m Map
	switch v := any(val).(type) {
	case Map:
		m = v
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(m).String())
	}

	// Create a LIST of STRUCT values.
	i := 0
	list := make([]any, len(m))
	for key, value := range m {
		list[i] = map[string]any{mapKeysField(): key, mapValuesField(): value}
		i++
	}

	return setList(vec, rowIdx, list)
}

func setUUID[S any](vec *vector, rowIdx  /*line :416:41*/_Ctype_idx_t /*line :416:48*/, val S) error {
	var uuid UUID
	switch v := any(val).(type) {
	case UUID:
		uuid = v
	case *UUID:
		uuid = *v
	case []uint8:
		if len(v) != uuid_length {
			return castError(reflect.TypeOf(val).String(), reflect.TypeOf(uuid).String())
		}
		for i := 0; i < uuid_length; i++ {
			uuid[i] = v[i]
		}
	default:
		return castError(reflect.TypeOf(val).String(), reflect.TypeOf(uuid).String())
	}
	hi := uuidToHugeInt(uuid)
	setPrimitive(vec, rowIdx, hi)
	return nil
}

func setVectorVal[S any](vec *vector, rowIdx  /*line :438:46*/_Ctype_idx_t /*line :438:53*/, val S) error {
	name, inMap := unsupportedTypeToStringMap[vec.Type]
	if inMap {
		return unsupportedTypeError(name)
	}

	switch vec.Type {
	case TYPE_BOOLEAN:
		return setBool[S](vec, rowIdx, val)
	case TYPE_TINYINT:
		return setNumeric[S, int8](vec, rowIdx, val)
	case TYPE_SMALLINT:
		return setNumeric[S, int16](vec, rowIdx, val)
	case TYPE_INTEGER:
		return setNumeric[S, int32](vec, rowIdx, val)
	case TYPE_BIGINT:
		return setNumeric[S, int64](vec, rowIdx, val)
	case TYPE_UTINYINT:
		return setNumeric[S, uint8](vec, rowIdx, val)
	case TYPE_USMALLINT:
		return setNumeric[S, uint16](vec, rowIdx, val)
	case TYPE_UINTEGER:
		return setNumeric[S, uint32](vec, rowIdx, val)
	case TYPE_UBIGINT:
		return setNumeric[S, uint64](vec, rowIdx, val)
	case TYPE_FLOAT:
		return setNumeric[S, float32](vec, rowIdx, val)
	case TYPE_DOUBLE:
		return setNumeric[S, float64](vec, rowIdx, val)
	case TYPE_TIMESTAMP, TYPE_TIMESTAMP_S, TYPE_TIMESTAMP_MS,
		TYPE_TIMESTAMP_NS, TYPE_TIMESTAMP_TZ:
		return setTS[S](vec, rowIdx, val)
	case TYPE_DATE:
		return setDate[S](vec, rowIdx, val)
	case TYPE_TIME, TYPE_TIME_TZ:
		return setTime[S](vec, rowIdx, val)
	case TYPE_INTERVAL:
		return setInterval[S](vec, rowIdx, val)
	case TYPE_HUGEINT:
		return setHugeint[S](vec, rowIdx, val)
	case TYPE_VARCHAR:
		return setBytes[S](vec, rowIdx, val)
	case TYPE_BLOB:
		return setBytes[S](vec, rowIdx, val)
	case TYPE_DECIMAL:
		return setDecimal[S](vec, rowIdx, val)
	case TYPE_ENUM:
		return setEnum[S](vec, rowIdx, val)
	case TYPE_LIST:
		return setList[S](vec, rowIdx, val)
	case TYPE_STRUCT:
		return setStruct[S](vec, rowIdx, val)
	case TYPE_UUID:
		return setUUID[S](vec, rowIdx, val)
	default:
		return unsupportedTypeError(unknownTypeErrMsg)
	}
}
