// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/row.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

// Row represents one row in duckdb. It references the internal vectors.
type Row struct {
	chunk      *DataChunk
	r           /*line :11:13*/_Ctype_idx_t /*line :11:20*/
	projection []int
}

// IsProjected returns whether the column is projected.
func (r Row) IsProjected(colIdx int) bool {
	return r.projection[colIdx] != -1
}

// SetRowValue sets the value at colIdx to val.
// Returns an error on failure, and nil for non-projected columns.
func SetRowValue[T any](row Row, colIdx int, val T) error {
	projectedIdx := row.projection[colIdx]
	if projectedIdx < 0 || projectedIdx >= len(row.chunk.columns) {
		return nil
	}
	vec := row.chunk.columns[projectedIdx]
	return setVectorVal(&vec, row.r, val)
}

// SetRowValue sets the value at colIdx to val. Returns an error on failure.
func (r Row) SetRowValue(colIdx int, val any) error {
	if !r.IsProjected(colIdx) {
		return nil
	}
	return r.chunk.SetValue(colIdx, int(r.r), val)
}
