/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#pragma GCC diagnostic ignored "-Wunaligned-access"
extern void crosscall2(void (*fn)(void *), void *, int, size_t);
extern size_t _cgo_wait_runtime_init_done(void);
extern void _cgo_release_context(size_t);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_95ddaae2a49e_releaseExportedSchema(void *);

CGO_NO_SANITIZE_THREAD
void releaseExportedSchema(struct ArrowSchema* schema)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowSchema* p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = schema;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_releaseExportedSchema, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_95ddaae2a49e_releaseExportedArray(void *);

CGO_NO_SANITIZE_THREAD
void releaseExportedArray(struct ArrowArray* arr)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowArray* p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = arr;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_releaseExportedArray, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_95ddaae2a49e_streamGetSchema(void *);

CGO_NO_SANITIZE_THREAD
int streamGetSchema(struct ArrowArrayStream* handle, struct ArrowSchema* out)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowArrayStream* p0;
		struct ArrowSchema* p1;
		int r0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_a.p1 = out;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_streamGetSchema, &_cgo_a, 20, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_95ddaae2a49e_streamGetNext(void *);

CGO_NO_SANITIZE_THREAD
int streamGetNext(struct ArrowArrayStream* handle, struct ArrowArray* out)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowArrayStream* p0;
		struct ArrowArray* p1;
		int r0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_a.p1 = out;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_streamGetNext, &_cgo_a, 20, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_95ddaae2a49e_streamGetError(void *);

CGO_NO_SANITIZE_THREAD
cchar_t* streamGetError(struct ArrowArrayStream* handle)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowArrayStream* p0;
		cchar_t* r0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_streamGetError, &_cgo_a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_95ddaae2a49e_streamRelease(void *);

CGO_NO_SANITIZE_THREAD
void streamRelease(struct ArrowArrayStream* handle)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		struct ArrowArrayStream* p0;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_tsan_release();
	crosscall2(_cgoexp_95ddaae2a49e_streamRelease, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}

CGO_NO_SANITIZE_THREAD
void _cgo_95ddaae2a49e_Cfunc__Cmalloc(void *v) {
	struct {
		unsigned long long p0;
		void *r1;
	} __attribute__((__packed__)) *a = v;
	void *ret;
	_cgo_tsan_acquire();
	ret = malloc(a->p0);
	if (ret == 0 && a->p0 == 0) {
		ret = malloc(1);
	}
	a->r1 = ret;
	_cgo_tsan_release();
}
