/**
 * ConfigAIAssist — v0.26 AI-assist surface inside the config
 * editor. Sits next to the Templates picker in the editor header
 * and offers two actions:
 *
 *  - "Explain this config" → calls /api/v1/ai/explain-config with
 *    the current editor contents and renders the result in a
 *    dialog (summary + per-pipeline notes).
 *  - "Merge in a snippet" → opens a dialog with a textarea for the
 *    snippet, then calls /api/v1/ai/merge. The result replaces the
 *    editor contents — the operator reviews the diff, runs lint,
 *    saves and rolls out via the existing flow. No auto-rollout,
 *    no auto-save.
 *
 * The component returns null when /api/v1/ai/status reports
 * disabled, so the operator sees nothing rather than a non-
 * functional button.
 */

import { Loader2Icon, SparklesIcon } from "lucide-react";
import { useEffect, useState } from "react";

import {
  explainConfig,
  mergeIntoConfig,
  useAICapabilities,
  type ExplainConfigResponse,
} from "@/api/ai";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Textarea } from "@/components/ui/textarea";

interface ConfigAIAssistProps {
  /** Current editor contents — passed to both Explain and Merge. */
  currentValue: string;
  /** Called when Merge produces a new YAML. */
  onApplyMerge: (mergedYAML: string, summary: string) => void;
}

export function ConfigAIAssist({
  currentValue,
  onApplyMerge,
}: ConfigAIAssistProps) {
  const { capabilities } = useAICapabilities();
  const [mode, setMode] = useState<"closed" | "explain" | "merge">("closed");

  if (!capabilities?.enabled) return null;

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 px-2 text-xs"
            disabled={!currentValue.trim()}
            title="Claude can explain this config or merge a snippet in"
          >
            <SparklesIcon className="mr-1 h-3 w-3" />
            AI Assist
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={() => setMode("explain")}>
            <SparklesIcon className="mr-2 h-3 w-3" />
            Explain this config
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setMode("merge")}>
            <SparklesIcon className="mr-2 h-3 w-3" />
            Merge in a snippet…
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {mode === "explain" && (
        <ExplainConfigDialog
          yaml={currentValue}
          model={capabilities.explain_model ?? ""}
          onClose={() => setMode("closed")}
        />
      )}
      {mode === "merge" && (
        <MergeSnippetDialog
          baseYAML={currentValue}
          model={capabilities.merge_model ?? ""}
          onApply={(merged, summary) => {
            onApplyMerge(merged, summary);
            setMode("closed");
          }}
          onClose={() => setMode("closed")}
        />
      )}
    </>
  );
}

// ----------------------------------------------------------------
// Explain dialog
// ----------------------------------------------------------------

function ExplainConfigDialog({
  yaml,
  model,
  onClose,
}: {
  yaml: string;
  model: string;
  onClose: () => void;
}) {
  const [result, setResult] = useState<ExplainConfigResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  // Kick off the call once on mount. No retry — operator can close
  // and re-open if they want to retry on a transient failure.
  useEffect(() => {
    let cancelled = false;
    explainConfig({ yaml })
      .then((r) => !cancelled && setResult(r))
      .catch((e) => {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "AI request failed.");
        }
      })
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
    // We deliberately don't re-fire when yaml changes mid-dialog;
    // operator closes + reopens to re-run.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>What this config does</DialogTitle>
          <DialogDescription>
            Summary generated by {model || "Claude"}. Read it as a starting
            point, not a substitute for reviewing the YAML.
          </DialogDescription>
        </DialogHeader>
        {loading ? (
          <div className="flex items-center gap-2 py-6 text-sm text-muted-foreground">
            <Loader2Icon className="h-4 w-4 animate-spin" />
            Reading the config…
          </div>
        ) : error ? (
          <div className="text-sm text-[var(--destructive)]">{error}</div>
        ) : result ? (
          <div className="space-y-4">
            <p className="text-sm">{result.summary}</p>
            {result.pipelines && Object.keys(result.pipelines).length > 0 && (
              <div>
                <div className="mb-1 text-[10px] uppercase tracking-wider text-muted-foreground">
                  Pipelines
                </div>
                <div className="space-y-1.5">
                  {Object.entries(result.pipelines).map(([name, desc]) => (
                    <div
                      key={name}
                      className="rounded-md border border-border p-2"
                    >
                      <div className="font-mono text-[11px] text-muted-foreground">
                        {name}
                      </div>
                      <div className="text-sm">{desc}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}
            <div className="font-tabular text-[10px] text-muted-foreground">
              {result.model} · {result.tokens_in + result.tokens_out} tokens
            </div>
          </div>
        ) : null}
        <DialogFooter>
          <Button variant="outline" size="sm" onClick={onClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ----------------------------------------------------------------
// Merge dialog
// ----------------------------------------------------------------

function MergeSnippetDialog({
  baseYAML,
  model,
  onApply,
  onClose,
}: {
  baseYAML: string;
  model: string;
  onApply: (mergedYAML: string, summary: string) => void;
  onClose: () => void;
}) {
  const [snippet, setSnippet] = useState("");
  const [goal, setGoal] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const canMerge = snippet.trim().length > 0 && !loading;

  const handleMerge = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await mergeIntoConfig({
        base_yaml: baseYAML,
        snippet_yaml: snippet,
        goal: goal || undefined,
      });
      onApply(res.merged_yaml, res.summary);
    } catch (e) {
      setError(e instanceof Error ? e.message : "AI merge failed.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Merge a snippet into this config</DialogTitle>
          <DialogDescription>
            {model ? `${model}` : "Claude"} will merge your snippet into the
            current YAML and replace the editor contents. Review the result, run
            lint, and roll out as usual — nothing changes server-side until you
            save.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <label className="block text-sm">
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Snippet
            </span>
            <Textarea
              value={snippet}
              onChange={(e) => setSnippet(e.target.value)}
              placeholder="processors:&#10;  attributes/drop_http_url:&#10;    actions:&#10;      - key: http.url&#10;        action: delete"
              rows={10}
              className="mt-1 font-mono text-[11px]"
              disabled={loading}
            />
          </label>
          <label className="block text-sm">
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Goal (optional)
            </span>
            <input
              type="text"
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="Drop http.url from metrics to save bytes"
              className="mt-1 w-full rounded-md border border-input bg-background px-3 py-1.5 text-sm"
              disabled={loading}
            />
          </label>
          {error && (
            <div className="text-sm text-[var(--destructive)]">{error}</div>
          )}
        </div>
        <DialogFooter>
          <Button variant="outline" size="sm" onClick={onClose}>
            Cancel
          </Button>
          <Button size="sm" onClick={handleMerge} disabled={!canMerge}>
            {loading ? (
              <>
                <Loader2Icon className="mr-1 h-3 w-3 animate-spin" />
                Merging…
              </>
            ) : (
              <>
                <SparklesIcon className="mr-1 h-3 w-3" />
                Merge into editor
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
