//go:cgo_ldflag "-O2"
//go:cgo_ldflag "-g"
// Code generated by cmd/cgo; DO NOT EDIT.

package cdata

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_keepalive runtime.cgoKeepAlive
//go:noescape
func _Cgo_keepalive(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype__GoBytes_ []byte

type _Ctype__GoString_ string

type _Ctype___int64_t = _Ctype_long

type _Ctype___uint8_t = _Ctype_uchar

type _Ctype_cchar_t = _Ctype_char

type _Ctype_char uint8

type _Ctype_int int32

type _Ctype_int64_t = _Ctype___int64_t

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_size_t = _Ctype_ulong

type _Ctype_struct_ArrowArray struct {
	length		_Ctype_int64_t
	null_count	_Ctype_int64_t
	offset		_Ctype_int64_t
	n_buffers	_Ctype_int64_t
	n_children	_Ctype_int64_t
	buffers		*unsafe.Pointer
	children	**_Ctype_struct_ArrowArray
	dictionary	*_Ctype_struct_ArrowArray
	release		*[0]byte
	private_data	unsafe.Pointer
}

type _Ctype_struct_ArrowArrayStream struct {
	get_schema	*[0]byte
	get_next	*[0]byte
	get_last_error	*[0]byte
	release		*[0]byte
	private_data	unsafe.Pointer
}

type _Ctype_struct_ArrowSchema struct {
	format		*_Ctype_char
	name		*_Ctype_char
	metadata	*_Ctype_char
	flags		_Ctype_int64_t
	n_children	_Ctype_int64_t
	children	**_Ctype_struct_ArrowSchema
	dictionary	*_Ctype_struct_ArrowSchema
	release		*[0]byte
	private_data	unsafe.Pointer
}

type _Ctype_uchar uint8

type _Ctype_uint8_t = _Ctype___uint8_t

type _Ctype_uintptr_t = _Ctype_ulong

type _Ctype_ulong uint64

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})
//go:linkname __cgo_goReleaseArray goReleaseArray
//go:cgo_import_static goReleaseArray
var __cgo_goReleaseArray byte
var _Cfpvar_fp_goReleaseArray unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_goReleaseArray))
//go:linkname __cgo_goReleaseSchema goReleaseSchema
//go:cgo_import_static goReleaseSchema
var __cgo_goReleaseSchema byte
var _Cfpvar_fp_goReleaseSchema unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_goReleaseSchema))
//go:linkname __cgo_streamGetError streamGetError
//go:cgo_import_static streamGetError
var __cgo_streamGetError byte
var _Cfpvar_fp_streamGetError unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_streamGetError))
//go:linkname __cgo_streamGetNextTrampoline streamGetNextTrampoline
//go:cgo_import_static streamGetNextTrampoline
var __cgo_streamGetNextTrampoline byte
var _Cfpvar_fp_streamGetNextTrampoline unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_streamGetNextTrampoline))
//go:linkname __cgo_streamGetSchemaTrampoline streamGetSchemaTrampoline
//go:cgo_import_static streamGetSchemaTrampoline
var __cgo_streamGetSchemaTrampoline byte
var _Cfpvar_fp_streamGetSchemaTrampoline unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_streamGetSchemaTrampoline))
//go:linkname __cgo_streamRelease streamRelease
//go:cgo_import_static streamRelease
var __cgo_streamRelease byte
var _Cfpvar_fp_streamRelease unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_streamRelease))
//go:linkname __cgo_kGoCdataZeroRegion kGoCdataZeroRegion
//go:cgo_import_static kGoCdataZeroRegion
var __cgo_kGoCdataZeroRegion byte
var _Cvar_kGoCdataZeroRegion *[8]_Ctype_uint8_t = (*[8]_Ctype_uint8_t)(unsafe.Pointer(&__cgo_kGoCdataZeroRegion))
const _Ciconst_ARROW_FLAG_DICTIONARY_ORDERED = 0x1
const _Ciconst_ARROW_FLAG_MAP_KEYS_SORTED = 0x4
const _Ciconst_ARROW_FLAG_NULLABLE = 0x2
const _Ciconst_EIO = 0x5
const _Ciconst_sizeof_int64_t = 0x8
const _Ciconst_sizeof_struct_ArrowArray = 0x50
const _Ciconst_sizeof_struct_ArrowSchema = 0x48
const _Ciconst_sizeof_uintptr_t = 0x8

//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased _cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayIsReleased(p0 *_Ctype_struct_ArrowArray) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayIsReleased, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased _cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayMarkReleased(p0 *_Ctype_struct_ArrowArray) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayMarkReleased, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayMove
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMove _cgo_95ddaae2a49e_Cfunc_ArrowArrayMove
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMove byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayMove = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayMove)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayMove(p0 *_Ctype_struct_ArrowArray, p1 *_Ctype_struct_ArrowArray) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayMove, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease _cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayRelease(p0 *_Ctype_struct_ArrowArray) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayRelease, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayStreamMove(p0 *_Ctype_struct_ArrowArrayStream, p1 *_Ctype_struct_ArrowArrayStream) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamMove, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease byte
var _cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease)

//go:cgo_unsafe_args
func _Cfunc_ArrowArrayStreamRelease(p0 *_Ctype_struct_ArrowArrayStream) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowArrayStreamRelease, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased _cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased byte
var _cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased)

//go:cgo_unsafe_args
func _Cfunc_ArrowSchemaIsReleased(p0 *_Ctype_struct_ArrowSchema) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowSchemaIsReleased, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased _cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased byte
var _cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased)

//go:cgo_unsafe_args
func _Cfunc_ArrowSchemaMarkReleased(p0 *_Ctype_struct_ArrowSchema) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowSchemaMarkReleased, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease _cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease
var __cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease byte
var _cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease)

//go:cgo_unsafe_args
func _Cfunc_ArrowSchemaRelease(p0 *_Ctype_struct_ArrowSchema) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_ArrowSchemaRelease, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}

// CBytes converts the Go []byte slice b to a C array.
//
// The C array is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CBytes(b []byte) unsafe.Pointer {
	p := _cgo_cmalloc(uint64(len(b)))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(b), len(b)}
	s := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(s, b)
	return p
}

// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}

func _Cfunc__CMalloc(n _Ctype_size_t) unsafe.Pointer {
	return _cgo_cmalloc(uint64(n))
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_calloc
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_calloc _cgo_95ddaae2a49e_Cfunc_calloc
var __cgofn__cgo_95ddaae2a49e_Cfunc_calloc byte
var _cgo_95ddaae2a49e_Cfunc_calloc = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_calloc)

//go:cgo_unsafe_args
func _Cfunc_calloc(p0 _Ctype_size_t, p1 _Ctype_size_t) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_calloc, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_free
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_free _cgo_95ddaae2a49e_Cfunc_free
var __cgofn__cgo_95ddaae2a49e_Cfunc_free byte
var _cgo_95ddaae2a49e_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_get_arr
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_get_arr _cgo_95ddaae2a49e_Cfunc_get_arr
var __cgofn__cgo_95ddaae2a49e_Cfunc_get_arr byte
var _cgo_95ddaae2a49e_Cfunc_get_arr = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_get_arr)

//go:cgo_unsafe_args
func _Cfunc_get_arr() (r1 *_Ctype_struct_ArrowArray) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_get_arr, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_get_stream
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_get_stream _cgo_95ddaae2a49e_Cfunc_get_stream
var __cgofn__cgo_95ddaae2a49e_Cfunc_get_stream byte
var _cgo_95ddaae2a49e_Cfunc_get_stream = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_get_stream)

//go:cgo_unsafe_args
func _Cfunc_get_stream() (r1 *_Ctype_struct_ArrowArrayStream) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_get_stream, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_stream_get_last_error
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_last_error _cgo_95ddaae2a49e_Cfunc_stream_get_last_error
var __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_last_error byte
var _cgo_95ddaae2a49e_Cfunc_stream_get_last_error = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_last_error)

//go:cgo_unsafe_args
func _Cfunc_stream_get_last_error(p0 *_Ctype_struct_ArrowArrayStream) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_stream_get_last_error, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_stream_get_next
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_next _cgo_95ddaae2a49e_Cfunc_stream_get_next
var __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_next byte
var _cgo_95ddaae2a49e_Cfunc_stream_get_next = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_next)

//go:cgo_unsafe_args
func _Cfunc_stream_get_next(p0 *_Ctype_struct_ArrowArrayStream, p1 *_Ctype_struct_ArrowArray) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_stream_get_next, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc_stream_get_schema
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_schema _cgo_95ddaae2a49e_Cfunc_stream_get_schema
var __cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_schema byte
var _cgo_95ddaae2a49e_Cfunc_stream_get_schema = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc_stream_get_schema)

//go:cgo_unsafe_args
func _Cfunc_stream_get_schema(p0 *_Ctype_struct_ArrowArrayStream, p1 *_Ctype_struct_ArrowSchema) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc_stream_get_schema, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_export_dynamic releaseExportedSchema
//go:linkname _cgoexp_95ddaae2a49e_releaseExportedSchema _cgoexp_95ddaae2a49e_releaseExportedSchema
//go:cgo_export_static _cgoexp_95ddaae2a49e_releaseExportedSchema
func _cgoexp_95ddaae2a49e_releaseExportedSchema(a *struct {
		p0 *CArrowSchema
	}) {
	releaseExportedSchema(a.p0)
}
//go:cgo_export_dynamic releaseExportedArray
//go:linkname _cgoexp_95ddaae2a49e_releaseExportedArray _cgoexp_95ddaae2a49e_releaseExportedArray
//go:cgo_export_static _cgoexp_95ddaae2a49e_releaseExportedArray
func _cgoexp_95ddaae2a49e_releaseExportedArray(a *struct {
		p0 *CArrowArray
	}) {
	releaseExportedArray(a.p0)
}
//go:cgo_export_dynamic streamGetSchema
//go:linkname _cgoexp_95ddaae2a49e_streamGetSchema _cgoexp_95ddaae2a49e_streamGetSchema
//go:cgo_export_static _cgoexp_95ddaae2a49e_streamGetSchema
func _cgoexp_95ddaae2a49e_streamGetSchema(a *struct {
		p0 *CArrowArrayStream
		p1 *CArrowSchema
		r0 _Ctype_int
	}) {
	a.r0 = streamGetSchema(a.p0, a.p1)
}
//go:cgo_export_dynamic streamGetNext
//go:linkname _cgoexp_95ddaae2a49e_streamGetNext _cgoexp_95ddaae2a49e_streamGetNext
//go:cgo_export_static _cgoexp_95ddaae2a49e_streamGetNext
func _cgoexp_95ddaae2a49e_streamGetNext(a *struct {
		p0 *CArrowArrayStream
		p1 *CArrowArray
		r0 _Ctype_int
	}) {
	a.r0 = streamGetNext(a.p0, a.p1)
}
//go:cgo_export_dynamic streamGetError
//go:linkname _cgoexp_95ddaae2a49e_streamGetError _cgoexp_95ddaae2a49e_streamGetError
//go:cgo_export_static _cgoexp_95ddaae2a49e_streamGetError
func _cgoexp_95ddaae2a49e_streamGetError(a *struct {
		p0 *CArrowArrayStream
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = streamGetError(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic streamRelease
//go:linkname _cgoexp_95ddaae2a49e_streamRelease _cgoexp_95ddaae2a49e_streamRelease
//go:cgo_export_static _cgoexp_95ddaae2a49e_streamRelease
func _cgoexp_95ddaae2a49e_streamRelease(a *struct {
		p0 *CArrowArrayStream
	}) {
	streamRelease(a.p0)
}

//go:cgo_import_static _cgo_95ddaae2a49e_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_95ddaae2a49e_Cfunc__Cmalloc _cgo_95ddaae2a49e_Cfunc__Cmalloc
var __cgofn__cgo_95ddaae2a49e_Cfunc__Cmalloc byte
var _cgo_95ddaae2a49e_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_95ddaae2a49e_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_95ddaae2a49e_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
