// generated by compile -asmhdr from package memory

#define const_alignment 64
#define Buffer__size 72
#define Buffer_refCount 0
#define Buffer_buf 8
#define Buffer_length 32
#define Buffer_mutable 40
#define Buffer_mem 48
#define Buffer_parent 64
#define CheckedAllocator__size 72
#define CheckedAllocator_mem 0
#define CheckedAllocator_sz 16
#define CheckedAllocator_allocs 24
#define const_defAllocFrames 4
#define const_defReallocFrames 3
#define const_defMaxRetainedFrames 0
#define dalloc__size 32
#define dalloc_pc 0
#define dalloc_line 8
#define dalloc_sz 16
#define dalloc_callersFrames 24
#define CheckedAllocatorScope__size 16
#define CheckedAllocatorScope_alloc 0
#define CheckedAllocatorScope_sz 8
#define GoAllocator__size 0
