// Copyright (c) 2024 Squadron Contributors
// SPDX-License-Identifier: Apache-2.0

package gcpconnstore

import (
	"context"
	"errors"
)

// ErrConnectionNotFound is returned by Get / Update / Delete when no
// row matches the supplied ID. Callers errors.Is against this
// sentinel to distinguish "no such connection" from infrastructure
// failures.
var ErrConnectionNotFound = errors.New("gcpconnstore: connection not found")

// Store is the GCP-connection substrate interface. Implementations
// persist GCPConnection rows with their SealedSA sealed by the
// credstore Key. The interface returns plain *GCPConnection values:
// the SealedSA field carries the on-disk sealed bytes, never
// plaintext. Decryption is the scanner's job (chunk 2 of #667), not
// the substrate's.
//
// All methods are safe for concurrent use; the SQLite-backed default
// serializes writes through the database pool, and the memory-backed
// implementation uses a sync.RWMutex.
//
// Slice 1 chunk 1 of #667 ships the bare CRUD surface. Chunks 2 / 3
// add the scanner and HTTP handlers; the Update path here is used
// by chunk 3's PATCH endpoint to flip the LearnFromAcceptedRecommendations
// flag and update display metadata. The substrate intentionally
// does NOT expose a "rotate the SA" path: operators rotate by Delete
// + Create, mirroring the iacconnstore credential-rotation posture
// (one extra wizard round-trip, no class of "did the rotation also
// touch X?" bugs).
type Store interface {
	// Create inserts a new connection row. The connection's ID is
	// generated by the substrate (callers leave it empty) and the
	// stamped value is written back to the passed-in struct's ID
	// field. CreatedAt and UpdatedAt are stamped to now.
	//
	// LearnFromAcceptedRecommendations defaults to true when the
	// caller leaves the zero value (false), mirroring iacconnstore's
	// v0.89.28 posture.
	Create(ctx context.Context, conn *GCPConnection) error

	// Get returns the connection row for the given ID. Returns
	// ErrConnectionNotFound (errors.Is-comparable) when no row
	// matches. SealedSA is populated with the sealed on-disk bytes
	// so the scanner can pass them to credstore.UnsealGCPServiceAccount.
	Get(ctx context.Context, id string) (*GCPConnection, error)

	// List returns every connection row, ordered by CreatedAt
	// ascending. Empty store returns an empty slice and no error.
	List(ctx context.Context) ([]*GCPConnection, error)

	// Update replaces the mutable fields on the row identified by
	// conn.ID — DisplayName, ProjectID, Region, SealedSA, and
	// LearnFromAcceptedRecommendations — and stamps UpdatedAt to
	// now. Pass a nil/empty SealedSA to keep the existing sealed
	// bytes in place; pass a fresh sealed blob to rotate the SA in
	// place (chunk 3 may or may not expose this path depending on
	// the wizard shape). Returns ErrConnectionNotFound when no row
	// matches.
	Update(ctx context.Context, conn *GCPConnection) error

	// Delete removes the row for the given ID. Idempotent: deleting
	// a non-existent row is not an error. This is the
	// credential-rotation path — operators delete and re-run the
	// connect wizard rather than mutating an in-place row.
	Delete(ctx context.Context, id string) error

	// Close releases the underlying database handle. Subsequent
	// calls to other methods return an error.
	Close() error
}
