
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/devopsmike2/squadron/cmd/all-in-one"


)

var tests = []testing.InternalTest{

	{"TestOSSEdition_IdentityProviders", _test.TestOSSEdition_IdentityProviders},

	{"TestOSSEdition_ScopedStoreIsPassthrough", _test.TestOSSEdition_ScopedStoreIsPassthrough},

	{"TestOSSEdition_BuildIdentity", _test.TestOSSEdition_BuildIdentity},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/devopsmike2/squadron/cmd/all-in-one"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

