package cdata
//go:cgo_import_dynamic __libc_start_main __libc_start_main#GLIBC_2.34 "libc.so.6"
//go:cgo_import_dynamic _ITM_deregisterTMCloneTable _ITM_deregisterTMCloneTable ""
//go:cgo_import_dynamic __cxa_finalize __cxa_finalize#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic malloc malloc#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic calloc calloc#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic __stack_chk_fail __stack_chk_fail#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic __gmon_start__ __gmon_start__ ""
//go:cgo_import_dynamic __stack_chk_guard __stack_chk_guard#GLIBC_2.17 "ld-linux-aarch64.so.1"
//go:cgo_import_dynamic abort abort#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic free free#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic _ITM_registerTMCloneTable _ITM_registerTMCloneTable ""
//go:cgo_import_dynamic __assert_fail __assert_fail#GLIBC_2.17 "libc.so.6"
//go:cgo_import_dynamic _ _ "libc.so.6"
//go:cgo_import_dynamic _ _ "ld-linux-aarch64.so.1"
