// generated by compile -asmhdr from package utils

#define bufferedReader__size 80
#define bufferedReader_bufferSz 0
#define bufferedReader_buf 8
#define bufferedReader_r 32
#define bufferedReader_w 40
#define bufferedReader_rd 48
#define bufferedReader_err 64
