// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/appender.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"database/sql/driver"
	"errors"
	"unsafe"
)

// Appender holds the DuckDB appender. It allows efficient bulk loading into a DuckDB database.
type Appender struct {
	con            *conn
	schema         string
	table          string
	duckdbAppender  /*line :19:17*/_Ctype_duckdb_appender /*line :19:34*/
	closed         bool

	// The appender storage before flushing any data.
	chunks []DataChunk
	// The column types of the table to append to.
	types [] /*line :25:10*/_Ctype_duckdb_logical_type /*line :25:31*/
	// A pointer to the allocated memory of the column types.
	ptr unsafe.Pointer
	// The number of appended rows.
	rowCount int
}

// NewAppenderFromConn returns a new Appender from a DuckDB driver connection.
func NewAppenderFromConn(driverConn driver.Conn, schema, table string) (*Appender, error) {
	con, ok := driverConn.(*conn)
	if !ok {
		return nil, getError(errInvalidCon, nil)
	}
	if con.closed {
		return nil, getError(errClosedCon, nil)
	}

	var cSchema * /*line :42:15*/_Ctype_char /*line :42:21*/
	if schema != "" {
		cSchema = ( /*line :44:13*/_Cfunc_CString /*line :44:21*/)(schema)
		defer func() func() { _cgo0 := /*line :45:23*/unsafe.Pointer(cSchema); return func() { _cgoCheckPointer(_cgo0, nil); /*line :45:47*/_Cfunc_duckdb_free(_cgo0); }}()()
	}

	cTable := ( /*line :48:12*/_Cfunc_CString /*line :48:20*/)(table)
	defer func() func() { _cgo0 := /*line :49:22*/unsafe.Pointer(cTable); return func() { _cgoCheckPointer(_cgo0, nil); /*line :49:45*/_Cfunc_duckdb_free(_cgo0); }}()()

	var duckdbAppender  /*line :51:21*/_Ctype_duckdb_appender /*line :51:38*/
	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :52:36*/con.duckdbCon; var _cgo1 *_Ctype_char = /*line :52:51*/cSchema; var _cgo2 *_Ctype_char = /*line :52:60*/cTable; _cgoBase3 := /*line :52:68*/&duckdbAppender; _cgo3 := _cgoBase3; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase3, 0 == 0); return /*line :52:84*/_Cfunc_duckdb_appender_create(_cgo0, _cgo1, _cgo2, _cgo3); }()

	if state == ( /*line :54:14*/_Ciconst_DuckDBError /*line :54:26*/) {
		// We destroy the error message when destroying the appender.
		err := duckdbError(func() *_Ctype_char{ _cgo0 := /*line :56:46*/duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :56:61*/_Cfunc_duckdb_appender_error(_cgo0); }())
		func() _Ctype_duckdb_state{ _cgoBase0 := /*line :57:29*/&duckdbAppender; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :57:45*/_Cfunc_duckdb_appender_destroy(_cgo0); }()
		return nil, getError(errAppenderCreation, err)
	}

	a := &Appender{
		con:            con,
		schema:         schema,
		table:          table,
		duckdbAppender: duckdbAppender,
		rowCount:       0,
	}

	// Get the column types.
	columnCount := int(func() _Ctype_idx_t{ _cgo0 := /*line :70:52*/duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :70:67*/_Cfunc_duckdb_appender_column_count(_cgo0); }())
	a.ptr, a.types = mallocTypeSlice(columnCount)
	for i := 0; i < columnCount; i++ {
		a.types[i] = func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :73:46*/duckdbAppender; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :73:69*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :73:73*/_Cfunc_duckdb_appender_column_type(_cgo0, _cgo1); }()

		// Ensure that we only create an appender for supported column types.
		t := Type(func() _Ctype_duckdb_type{ _cgo0 := /*line :76:34*/a.types[i]; _cgoCheckPointer(_cgo0, nil); return /*line :76:45*/_Cfunc_duckdb_get_type_id(_cgo0); }())
		name, found := unsupportedTypeToStringMap[t]
		if found {
			err := addIndexToError(unsupportedTypeError(name), i+1)
			destroyTypeSlice(a.ptr, a.types)
			func() _Ctype_duckdb_state{ _cgoBase0 := /*line :81:30*/&duckdbAppender; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :81:46*/_Cfunc_duckdb_appender_destroy(_cgo0); }()
			return nil, getError(errAppenderCreation, err)
		}
	}

	return a, nil
}

// Flush the data chunks to the underlying table and clear the internal cache.
// Does not close the appender, even if it returns an error. Unless you have a good reason to call this,
// call Close when you are done with the appender.
func (a *Appender) Flush() error {
	if err := a.appendDataChunks(); err != nil {
		return getError(errAppenderFlush, invalidatedAppenderError(err))
	}

	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :97:35*/a.duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :97:52*/_Cfunc_duckdb_appender_flush(_cgo0); }()
	if state == ( /*line :98:14*/_Ciconst_DuckDBError /*line :98:26*/) {
		err := duckdbError(func() *_Ctype_char{ _cgo0 := /*line :99:46*/a.duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :99:63*/_Cfunc_duckdb_appender_error(_cgo0); }())
		return getError(errAppenderFlush, invalidatedAppenderError(err))
	}
	return nil
}

// Close the appender. This will flush the appender to the underlying table.
// It is vital to call this when you are done with the appender to avoid leaking memory.
func (a *Appender) Close() error {
	if a.closed {
		return getError(errAppenderDoubleClose, nil)
	}
	a.closed = true

	// Append all remaining chunks.
	errAppend := a.appendDataChunks()

	// We flush before closing to get a meaningful error message.
	var errFlush error
	state := func() _Ctype_duckdb_state{ _cgo0 := /*line :118:35*/a.duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :118:52*/_Cfunc_duckdb_appender_flush(_cgo0); }()
	if state == ( /*line :119:14*/_Ciconst_DuckDBError /*line :119:26*/) {
		errFlush = duckdbError(func() *_Ctype_char{ _cgo0 := /*line :120:50*/a.duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :120:67*/_Cfunc_duckdb_appender_error(_cgo0); }())
	}

	// Destroy all appender data and the appender.
	destroyTypeSlice(a.ptr, a.types)
	var errClose error
	state = func() _Ctype_duckdb_state{ _cgoBase0 := /*line :126:36*/&a.duckdbAppender; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :126:54*/_Cfunc_duckdb_appender_destroy(_cgo0); }()
	if state == ( /*line :127:14*/_Ciconst_DuckDBError /*line :127:26*/) {
		errClose = errAppenderClose
	}

	err := errors.Join(errAppend, errFlush, errClose)
	if err != nil {
		return getError(invalidatedAppenderError(err), nil)
	}
	return nil
}

// AppendRow loads a row of values into the appender. The values are provided as separate arguments.
func (a *Appender) AppendRow(args ...driver.Value) error {
	if a.closed {
		return getError(errAppenderAppendAfterClose, nil)
	}

	err := a.appendRowSlice(args)
	if err != nil {
		return getError(errAppenderAppendRow, err)
	}
	return nil
}

func (a *Appender) addDataChunk() error {
	var chunk DataChunk
	if err := chunk.initFromTypes(a.ptr, a.types, true); err != nil {
		return err
	}
	a.chunks = append(a.chunks, chunk)
	return nil
}

func (a *Appender) appendRowSlice(args []driver.Value) error {
	// Early-out, if the number of args does not match the column count.
	if len(args) != len(a.types) {
		return columnCountError(len(args), len(a.types))
	}

	// Create a new data chunk if the current chunk is full.
	if a.rowCount == GetDataChunkCapacity() || len(a.chunks) == 0 {
		if err := a.addDataChunk(); err != nil {
			return err
		}
		a.rowCount = 0
	}

	// Set all values.
	for i, val := range args {
		chunk := &a.chunks[len(a.chunks)-1]
		err := chunk.SetValue(i, a.rowCount, val)
		if err != nil {
			return err
		}
	}

	a.rowCount++
	return nil
}

func (a *Appender) appendDataChunks() error {
	var state  /*line :188:12*/_Ctype_duckdb_state /*line :188:26*/
	var err error

	for i, chunk := range a.chunks {
		// All data chunks except the last are at maximum capacity.
		size := GetDataChunkCapacity()
		if i == len(a.chunks)-1 {
			size = a.rowCount
		}
		if err = chunk.SetSize(size); err != nil {
			break
		}

		state = func() _Ctype_duckdb_state{ _cgo0 := /*line :201:38*/a.duckdbAppender; _cgo1 := /*line :201:56*/chunk.data; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :201:67*/_Cfunc_duckdb_append_data_chunk(_cgo0, _cgo1); }()
		if state == ( /*line :202:15*/_Ciconst_DuckDBError /*line :202:27*/) {
			err = duckdbError(func() *_Ctype_char{ _cgo0 := /*line :203:46*/a.duckdbAppender; _cgoCheckPointer(_cgo0, nil); return /*line :203:63*/_Cfunc_duckdb_appender_error(_cgo0); }())
			break
		}
	}

	for _, chunk := range a.chunks {
		chunk.close()
	}

	a.chunks = a.chunks[:0]
	a.rowCount = 0
	return err
}

func mallocTypeSlice(count int) (unsafe.Pointer, [] /*line :217:52*/_Ctype_duckdb_logical_type /*line :217:73*/) {
	var dummy  /*line :218:12*/_Ctype_duckdb_logical_type /*line :218:33*/
	size :=  /*line :219:10*/_Ctype_size_t /*line :219:18*/(unsafe.Sizeof(dummy))

	ptr := unsafe.Pointer(( /*line :221:24*/_Cfunc__CMalloc /*line :221:31*/)( /*line :221:33*/_Ctype_size_t /*line :221:41*/(count) * size))
	slice := (*[1 << 30] /*line :222:22*/_Ctype_duckdb_logical_type /*line :222:43*/)(ptr)[:count:count]

	return ptr, slice
}

func destroyTypeSlice(ptr unsafe.Pointer, slice [] /*line :227:51*/_Ctype_duckdb_logical_type /*line :227:72*/) {
	for _, t := range slice {
		func() { _cgoBase0 := /*line :229:33*/&t; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :229:36*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	}
	func() { _cgo0 := /*line :231:16*/ptr; _cgoCheckPointer(_cgo0, nil); /*line :231:20*/_Cfunc_duckdb_free(_cgo0); }()
}
