// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/data_chunk.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"unsafe"
)

// DataChunk storage of a DuckDB table.
type DataChunk struct {
	// data holds the underlying duckdb data chunk.
	data  /*line :15:7*/_Ctype_duckdb_data_chunk /*line :15:26*/
	// columns is a helper slice providing direct access to all columns.
	columns []vector
	// columnNames holds the column names, if known.
	columnNames []string
	// size caches the size after initialization.
	size int
}

// GetDataChunkCapacity returns the capacity of a data chunk.
func GetDataChunkCapacity() int {
	return int(( /*line :26:13*/_Cfunc_duckdb_vector_size /*line :26:32*/)())
}

// GetSize returns the internal size of the data chunk.
func (chunk *DataChunk) GetSize() int {
	chunk.size = int(func() _Ctype_idx_t{ _cgo0 := /*line :31:48*/chunk.data; _cgoCheckPointer(_cgo0, nil); return /*line :31:59*/_Cfunc_duckdb_data_chunk_get_size(_cgo0); }())
	return chunk.size
}

// SetSize sets the internal size of the data chunk. Cannot exceed GetCapacity().
func (chunk *DataChunk) SetSize(size int) error {
	if size > GetDataChunkCapacity() {
		return getError(errAPI, errVectorSize)
	}
	func() { _cgo0 := /*line :40:31*/chunk.data; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :40:50*/(size); _cgoCheckPointer(_cgo0, nil); /*line :40:57*/_Cfunc_duckdb_data_chunk_set_size(_cgo0, _cgo1); }()
	return nil
}

// GetValue returns a single value of a column.
func (chunk *DataChunk) GetValue(colIdx int, rowIdx int) (any, error) {
	if colIdx >= len(chunk.columns) {
		return nil, getError(errAPI, columnCountError(colIdx, len(chunk.columns)))
	}

	column := &chunk.columns[colIdx]
	return column.getFn(column,  /*line :51:30*/_Ctype_idx_t /*line :51:37*/(rowIdx)), nil
}

// SetValue writes a single value to a column in a data chunk.
// Note that this requires casting the type for each invocation.
// NOTE: Custom ENUM types must be passed as string.
func (chunk *DataChunk) SetValue(colIdx int, rowIdx int, val any) error {
	if colIdx >= len(chunk.columns) {
		return getError(errAPI, columnCountError(colIdx, len(chunk.columns)))
	}

	column := &chunk.columns[colIdx]
	return column.setFn(column,  /*line :63:30*/_Ctype_idx_t /*line :63:37*/(rowIdx), val)
}

// SetChunkValue writes a single value to a column in a data chunk.
// The difference with `chunk.SetValue` is that `SetChunkValue` does not
// require casting the value to `any` (implicitly).
// NOTE: Custom ENUM types must be passed as string.
func SetChunkValue[T any](chunk DataChunk, colIdx int, rowIdx int, val T) error {
	if colIdx >= len(chunk.columns) {
		return getError(errAPI, columnCountError(colIdx, len(chunk.columns)))
	}
	return setVectorVal(&chunk.columns[colIdx],  /*line :74:46*/_Ctype_idx_t /*line :74:53*/(rowIdx), val)
}

func (chunk *DataChunk) initFromTypes(ptr unsafe.Pointer, types [] /*line :77:67*/_Ctype_duckdb_logical_type /*line :77:88*/, writable bool) error {
	// NOTE: initFromTypes does not initialize the column names.
	columnCount := len(types)

	// Initialize the callback functions to read and write values.
	chunk.columns = make([]vector, columnCount)
	var err error
	for i := 0; i < columnCount; i++ {
		if err = chunk.columns[i].init(types[i], i); err != nil {
			break
		}
	}
	if err != nil {
		return err
	}

	logicalTypesPtr := (* /*line :93:23*/_Ctype_duckdb_logical_type /*line :93:44*/)(ptr)
	chunk.data = func() _Ctype_duckdb_data_chunk{ _cgo0 := /*line :94:42*/logicalTypesPtr; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :94:66*/(columnCount); _cgoCheckPointer(_cgo0, nil); return /*line :94:80*/_Cfunc_duckdb_create_data_chunk(_cgo0, _cgo1); }()
	func() { _cgo0 := /*line :95:31*/chunk.data; var _cgo1 _Ctype_idx_t = _Cfunc_duckdb_vector_size /*line :95:63*/(); _cgoCheckPointer(_cgo0, nil); /*line :95:66*/_Cfunc_duckdb_data_chunk_set_size(_cgo0, _cgo1); }()

	// Initialize the vectors and their child vectors.
	for i := 0; i < columnCount; i++ {
		v := func() _Ctype_duckdb_vector{ _cgo0 := /*line :99:39*/chunk.data; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :99:58*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :99:62*/_Cfunc_duckdb_data_chunk_get_vector(_cgo0, _cgo1); }()
		chunk.columns[i].initVectors(v, writable)
	}
	return nil
}

func (chunk *DataChunk) initFromDuckDataChunk(data  /*line :105:52*/_Ctype_duckdb_data_chunk /*line :105:71*/, writable bool) error {
	columnCount := int(func() _Ctype_idx_t{ _cgo0 := /*line :106:58*/data; _cgoCheckPointer(_cgo0, nil); return /*line :106:63*/_Cfunc_duckdb_data_chunk_get_column_count(_cgo0); }())
	chunk.columns = make([]vector, columnCount)
	chunk.data = data

	var err error
	for i := 0; i < columnCount; i++ {
		duckdbVector := func() _Ctype_duckdb_vector{ _cgo0 := /*line :112:50*/data; var _cgo1 _Ctype_idx_t = _Ctype_idx_t /*line :112:63*/(i); _cgoCheckPointer(_cgo0, nil); return /*line :112:67*/_Cfunc_duckdb_data_chunk_get_vector(_cgo0, _cgo1); }()

		// Initialize the callback functions to read and write values.
		logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :115:50*/duckdbVector; _cgoCheckPointer(_cgo0, nil); return /*line :115:63*/_Cfunc_duckdb_vector_get_column_type(_cgo0); }()
		err = chunk.columns[i].init(logicalType, i)
		func() { _cgoBase0 := /*line :117:33*/&logicalType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :117:46*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
		if err != nil {
			break
		}

		// Initialize the vector and its child vectors.
		chunk.columns[i].initVectors(duckdbVector, writable)
	}

	chunk.GetSize()
	return err
}

func (chunk *DataChunk) initFromDuckVector(duckdbVector  /*line :130:57*/_Ctype_duckdb_vector /*line :130:72*/, writable bool) error {
	columnCount := 1
	chunk.columns = make([]vector, columnCount)

	// Initialize the callback functions to read and write values.
	logicalType := func() _Ctype_duckdb_logical_type{ _cgo0 := /*line :135:49*/duckdbVector; _cgoCheckPointer(_cgo0, nil); return /*line :135:62*/_Cfunc_duckdb_vector_get_column_type(_cgo0); }()
	err := chunk.columns[0].init(logicalType, 0)
	func() { _cgoBase0 := /*line :137:32*/&logicalType; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :137:45*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	if err != nil {
		return err
	}

	// Initialize the vector and its child vectors.
	chunk.columns[0].initVectors(duckdbVector, writable)
	return nil
}

func (chunk *DataChunk) close() {
	func() { _cgoBase0 := /*line :148:30*/&chunk.data; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :148:42*/_Cfunc_duckdb_destroy_data_chunk(_cgo0); }()
}
