// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/scalarUDF.go:1:1
package duckdb; import _cgo_unsafe "unsafe"

/*
#include <duckdb.h>

void scalar_udf_callback(duckdb_function_info, duckdb_data_chunk, duckdb_vector);
void udf_delete_callback(void *);

typedef void (*scalar_udf_callback_t)(duckdb_function_info, duckdb_data_chunk, duckdb_vector);
*/
import _ "unsafe"

import (
	"database/sql"
	"database/sql/driver"
	"runtime"
	"runtime/cgo"
	"unsafe"
)

// ScalarFuncConfig contains the fields to configure a user-defined scalar function.
type ScalarFuncConfig struct {
	// InputTypeInfos contains Type information for each input parameter of the scalar function.
	InputTypeInfos []TypeInfo
	// ResultTypeInfo holds the Type information of the scalar function's result type.
	ResultTypeInfo TypeInfo

	// VariadicTypeInfo configures the number of input parameters.
	// If this field is nil, then the input parameters match InputTypeInfos.
	// Otherwise, the scalar function's input parameters are set to variadic, allowing any number of input parameters.
	// The Type of the first len(InputTypeInfos) parameters is configured by InputTypeInfos, and all
	// remaining parameters must match the variadic Type. To configure different variadic parameter types,
	// you must set the VariadicTypeInfo's Type to TYPE_ANY.
	VariadicTypeInfo TypeInfo
	// Volatile sets the stability of the scalar function to volatile, if true.
	// Volatile scalar functions might create a different result per row.
	// E.g., random() is a volatile scalar function.
	Volatile bool
	// SpecialNullHandling disables the default NULL handling of scalar functions, if true.
	// The default NULL handling is: NULL in, NULL out. I.e., if any input parameter is NULL, then the result is NULL.
	SpecialNullHandling bool
}

// ScalarFuncExecutor contains the callback function to execute a user-defined scalar function.
// Currently, its only field is a row-based executor.
type ScalarFuncExecutor struct {
	// RowExecutor accepts a row-based execution function.
	// []driver.Value contains the row values, and it returns the row execution result, or error.
	RowExecutor func(values []driver.Value) (any, error)
}

// ScalarFunc is the user-defined scalar function interface.
// Any scalar function must implement a Config function, and an Executor function.
type ScalarFunc interface {
	// Config returns ScalarFuncConfig to configure the scalar function.
	Config() ScalarFuncConfig
	// Executor returns ScalarFuncExecutor to execute the scalar function.
	Executor() ScalarFuncExecutor
}

// RegisterScalarUDF registers a user-defined scalar function.
// *sql.Conn is the SQL connection on which to register the scalar function.
// name is the function name, and f is the scalar function's interface ScalarFunc.
// RegisterScalarUDF takes ownership of f, so you must pass it as a pointer.
func RegisterScalarUDF(c *sql.Conn, name string, f ScalarFunc) error {
	function, err := createScalarFunc(name, f)
	if err != nil {
		return getError(errAPI, err)
	}

	// Register the function on the underlying driver connection exposed by c.Raw.
	err = c.Raw(func(driverConn any) error {
		con := driverConn.(*conn)
		state := func() _Ctype_duckdb_state{ _cgo0 := /*line :74:46*/con.duckdbCon; _cgo1 := /*line :74:61*/function; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :74:70*/_Cfunc_duckdb_register_scalar_function(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :75:36*/&function; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :75:46*/_Cfunc_duckdb_destroy_scalar_function(_cgo0); }()
		if state == ( /*line :76:15*/_Ciconst_DuckDBError /*line :76:27*/) {
			return getError(errAPI, errScalarUDFCreate)
		}
		return nil
	})
	return err
}

// RegisterScalarUDFSet registers a set of user-defined scalar functions with the same name.
// This enables overloading of scalar functions.
// E.g., the function my_length() can have implementations like my_length(LIST(ANY)) and my_length(VARCHAR).
// *sql.Conn is the SQL connection on which to register the scalar function set.
// name is the function name of each function in the set.
// functions contains all ScalarFunc functions of the scalar function set.
func RegisterScalarUDFSet(c *sql.Conn, name string, functions ...ScalarFunc) error {
	cName := ( /*line :91:11*/_Cfunc_CString /*line :91:19*/)(name)
	defer func() func() { _cgo0 := /*line :92:22*/unsafe.Pointer(cName); return func() { _cgoCheckPointer(_cgo0, nil); /*line :92:44*/_Cfunc_duckdb_free(_cgo0); }}()()
	set := ( /*line :93:9*/_Cfunc_duckdb_create_scalar_function_set /*line :93:43*/)(cName)

	// Create each function and add it to the set.
	for i, f := range functions {
		function, err := createScalarFunc(name, f)
		if err != nil {
			func() { _cgoBase0 := /*line :99:37*/&function; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :99:47*/_Cfunc_duckdb_destroy_scalar_function(_cgo0); }()
			func() { _cgoBase0 := /*line :100:41*/&set; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :100:46*/_Cfunc_duckdb_destroy_scalar_function_set(_cgo0); }()
			return getError(errAPI, err)
		}

		state := func() _Ctype_duckdb_state{ _cgo0 := /*line :104:48*/set; _cgo1 := /*line :104:53*/function; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :104:62*/_Cfunc_duckdb_add_scalar_function_to_set(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :105:36*/&function; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :105:46*/_Cfunc_duckdb_destroy_scalar_function(_cgo0); }()
		if state == ( /*line :106:15*/_Ciconst_DuckDBError /*line :106:27*/) {
			func() { _cgoBase0 := /*line :107:41*/&set; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :107:46*/_Cfunc_duckdb_destroy_scalar_function_set(_cgo0); }()
			return getError(errAPI, addIndexToError(errScalarUDFAddToSet, i))
		}
	}

	// Register the function set on the underlying driver connection exposed by c.Raw.
	err := c.Raw(func(driverConn any) error {
		con := driverConn.(*conn)
		state := func() _Ctype_duckdb_state{ _cgo0 := /*line :115:50*/con.duckdbCon; _cgo1 := /*line :115:65*/set; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :115:69*/_Cfunc_duckdb_register_scalar_function_set(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :116:40*/&set; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :116:45*/_Cfunc_duckdb_destroy_scalar_function_set(_cgo0); }()
		if state == ( /*line :117:15*/_Ciconst_DuckDBError /*line :117:27*/) {
			return getError(errAPI, errScalarUDFCreateSet)
		}
		return nil
	})
	return err
}

//export scalar_udf_callback
func scalar_udf_callback(function_info  /*line :126:40*/_Ctype_duckdb_function_info /*line :126:62*/, input  /*line :126:70*/_Ctype_duckdb_data_chunk /*line :126:89*/, output  /*line :126:98*/_Ctype_duckdb_vector /*line :126:113*/) {
	extraInfo := func() _cgo_unsafe.Pointer{ _cgo0 := /*line :127:55*/function_info; _cgoCheckPointer(_cgo0, nil); return /*line :127:69*/_Cfunc_duckdb_scalar_function_get_extra_info(_cgo0); }()
	function := getPinned[ScalarFunc](extraInfo)

	// Initialize the input chunk.
	var inputChunk DataChunk
	if err := inputChunk.initFromDuckDataChunk(input, false); err != nil {
		setFuncError(function_info, getError(errAPI, err).Error())
		return
	}

	// Initialize the output chunk.
	var outputChunk DataChunk
	if err := outputChunk.initFromDuckVector(output, true); err != nil {
		setFuncError(function_info, getError(errAPI, err).Error())
		return
	}

	executor := function.Executor()
	nullInNullOut := !function.Config().SpecialNullHandling
	values := make([]driver.Value, len(inputChunk.columns))
	columnCount := len(values)
	rowCount := inputChunk.GetSize()

	// Execute the user-defined scalar function for each row.
	var err error
	for rowIdx := 0; rowIdx < rowCount; rowIdx++ {
		nullRow := false

		// Get each column value.
		for colIdx := 0; colIdx < columnCount; colIdx++ {
			if values[colIdx], err = inputChunk.GetValue(colIdx, rowIdx); err != nil {
				setFuncError(function_info, getError(errAPI, err).Error())
				return
			}

			// NULL handling.
			if nullInNullOut && values[colIdx] == nil {
				if err = outputChunk.SetValue(0, rowIdx, nil); err != nil {
					setFuncError(function_info, getError(errAPI, err).Error())
					return
				}
				nullRow = true
				break
			}
		}
		if nullRow {
			continue
		}

		// Execute the function.
		var val any
		if val, err = executor.RowExecutor(values); err != nil {
			setFuncError(function_info, getError(errAPI, err).Error())
			return
		}

		// Write the result to the output chunk.
		if err = outputChunk.SetValue(0, rowIdx, val); err != nil {
			setFuncError(function_info, getError(errAPI, err).Error())
			return
		}
	}
}

func registerInputParams(config ScalarFuncConfig, f  /*line :191:53*/_Ctype_duckdb_scalar_function /*line :191:77*/) error {
	// Set variadic input parameters.
	if config.VariadicTypeInfo != nil {
		t := config.VariadicTypeInfo.logicalType()
		func() { _cgo0 := /*line :195:40*/f; _cgo1 := /*line :195:43*/t; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :195:45*/_Cfunc_duckdb_scalar_function_set_varargs(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :196:33*/&t; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :196:36*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	}

	// Early-out, if the function does not take any (non-variadic) parameters.
	if config.InputTypeInfos == nil {
		return nil
	}
	if len(config.InputTypeInfos) == 0 {
		return nil
	}

	// Set non-variadic input parameters.
	for i, info := range config.InputTypeInfos {
		if info == nil {
			return addIndexToError(errScalarUDFInputTypeIsNil, i)
		}
		t := info.logicalType()
		func() { _cgo0 := /*line :213:42*/f; _cgo1 := /*line :213:45*/t; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :213:47*/_Cfunc_duckdb_scalar_function_add_parameter(_cgo0, _cgo1); }()
		func() { _cgoBase0 := /*line :214:33*/&t; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :214:36*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	}
	return nil
}

func registerResultParams(config ScalarFuncConfig, f  /*line :219:54*/_Ctype_duckdb_scalar_function /*line :219:78*/) error {
	if config.ResultTypeInfo == nil {
		return errScalarUDFResultTypeIsNil
	}
	if config.ResultTypeInfo.InternalType() == TYPE_ANY {
		return errScalarUDFResultTypeIsANY
	}
	t := config.ResultTypeInfo.logicalType()
	func() { _cgo0 := /*line :227:43*/f; _cgo1 := /*line :227:46*/t; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); /*line :227:48*/_Cfunc_duckdb_scalar_function_set_return_type(_cgo0, _cgo1); }()
	func() { _cgoBase0 := /*line :228:32*/&t; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :228:35*/_Cfunc_duckdb_destroy_logical_type(_cgo0); }()
	return nil
}

func createScalarFunc(name string, f ScalarFunc) ( /*line :232:51*/_Ctype_duckdb_scalar_function /*line :232:75*/, error) {
	if name == "" {
		return nil, errScalarUDFNoName
	}
	if f == nil {
		return nil, errScalarUDFIsNil
	}
	if f.Executor().RowExecutor == nil {
		return nil, errScalarUDFNoExecutor
	}

	function := ( /*line :243:14*/_Cfunc_duckdb_create_scalar_function /*line :243:44*/)()

	// Set the name.
	cName := ( /*line :246:11*/_Cfunc_CString /*line :246:19*/)(name)
	defer func() func() { _cgo0 := /*line :247:22*/unsafe.Pointer(cName); return func() { _cgoCheckPointer(_cgo0, nil); /*line :247:44*/_Cfunc_duckdb_free(_cgo0); }}()()
	func() { _cgo0 := /*line :248:36*/function; var _cgo1 *_Ctype_char = /*line :248:46*/cName; _cgoCheckPointer(_cgo0, nil); /*line :248:52*/_Cfunc_duckdb_scalar_function_set_name(_cgo0, _cgo1); }()

	// Configure the scalar function.
	config := f.Config()
	if err := registerInputParams(config, function); err != nil {
		return nil, err
	}
	if err := registerResultParams(config, function); err != nil {
		return nil, err
	}
	if config.SpecialNullHandling {
		func() { _cgo0 := /*line :259:49*/function; _cgoCheckPointer(_cgo0, nil); /*line :259:58*/_Cfunc_duckdb_scalar_function_set_special_handling(_cgo0); }()
	}
	if config.Volatile {
		func() { _cgo0 := /*line :262:41*/function; _cgoCheckPointer(_cgo0, nil); /*line :262:50*/_Cfunc_duckdb_scalar_function_set_volatile(_cgo0); }()
	}

	// Set the function callback.
	func() { _cgo0 := /*line :266:40*/function; var _cgo1 *[0]byte = _Ctype_scalar_udf_callback_t /*line :266:73*/(_Cgo_ptr(_Cfpvar_fp_scalar_udf_callback /*line :266:95*/)); _cgoCheckPointer(_cgo0, nil); /*line :266:97*/_Cfunc_duckdb_scalar_function_set_function(_cgo0, _cgo1); }()

	// Pin the ScalarFunc f.
	value := pinnedValue[ScalarFunc]{
		pinner: &runtime.Pinner{},
		value:  f,
	}
	h := cgo.NewHandle(value)
	value.pinner.Pin(&h)

	// Set the execution data, which is the ScalarFunc f.
	func() { _cgo0 := /*line :278:3*/function; _cgoBase1 := /*line :279:18*/&h; _cgo1 := /*line :279:3*/unsafe.Pointer(_cgoBase1); var _cgo2 *[0]byte = _Ctype_duckdb_delete_callback_t /*line :280:29*/(_Cgo_ptr(_Cfpvar_fp_udf_delete_callback /*line :280:51*/)); _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); /*line :280:53*/_Cfunc_duckdb_scalar_function_set_extra_info(_cgo0, _cgo1, _cgo2); }()

	return function, nil
}
