// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/type.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

// Type wraps the corresponding DuckDB type enum.
type Type  /*line :9:11*/_Ctype_duckdb_type /*line :9:24*/

const (
	TYPE_INVALID      Type = ( /*line :12:27*/_Ciconst_DUCKDB_TYPE_INVALID /*line :12:47*/)
	TYPE_BOOLEAN      Type = ( /*line :13:27*/_Ciconst_DUCKDB_TYPE_BOOLEAN /*line :13:47*/)
	TYPE_TINYINT      Type = ( /*line :14:27*/_Ciconst_DUCKDB_TYPE_TINYINT /*line :14:47*/)
	TYPE_SMALLINT     Type = ( /*line :15:27*/_Ciconst_DUCKDB_TYPE_SMALLINT /*line :15:48*/)
	TYPE_INTEGER      Type = ( /*line :16:27*/_Ciconst_DUCKDB_TYPE_INTEGER /*line :16:47*/)
	TYPE_BIGINT       Type = ( /*line :17:27*/_Ciconst_DUCKDB_TYPE_BIGINT /*line :17:46*/)
	TYPE_UTINYINT     Type = ( /*line :18:27*/_Ciconst_DUCKDB_TYPE_UTINYINT /*line :18:48*/)
	TYPE_USMALLINT    Type = ( /*line :19:27*/_Ciconst_DUCKDB_TYPE_USMALLINT /*line :19:49*/)
	TYPE_UINTEGER     Type = ( /*line :20:27*/_Ciconst_DUCKDB_TYPE_UINTEGER /*line :20:48*/)
	TYPE_UBIGINT      Type = ( /*line :21:27*/_Ciconst_DUCKDB_TYPE_UBIGINT /*line :21:47*/)
	TYPE_FLOAT        Type = ( /*line :22:27*/_Ciconst_DUCKDB_TYPE_FLOAT /*line :22:45*/)
	TYPE_DOUBLE       Type = ( /*line :23:27*/_Ciconst_DUCKDB_TYPE_DOUBLE /*line :23:46*/)
	TYPE_TIMESTAMP    Type = ( /*line :24:27*/_Ciconst_DUCKDB_TYPE_TIMESTAMP /*line :24:49*/)
	TYPE_DATE         Type = ( /*line :25:27*/_Ciconst_DUCKDB_TYPE_DATE /*line :25:44*/)
	TYPE_TIME         Type = ( /*line :26:27*/_Ciconst_DUCKDB_TYPE_TIME /*line :26:44*/)
	TYPE_INTERVAL     Type = ( /*line :27:27*/_Ciconst_DUCKDB_TYPE_INTERVAL /*line :27:48*/)
	TYPE_HUGEINT      Type = ( /*line :28:27*/_Ciconst_DUCKDB_TYPE_HUGEINT /*line :28:47*/)
	TYPE_UHUGEINT     Type = ( /*line :29:27*/_Ciconst_DUCKDB_TYPE_UHUGEINT /*line :29:48*/)
	TYPE_VARCHAR      Type = ( /*line :30:27*/_Ciconst_DUCKDB_TYPE_VARCHAR /*line :30:47*/)
	TYPE_BLOB         Type = ( /*line :31:27*/_Ciconst_DUCKDB_TYPE_BLOB /*line :31:44*/)
	TYPE_DECIMAL      Type = ( /*line :32:27*/_Ciconst_DUCKDB_TYPE_DECIMAL /*line :32:47*/)
	TYPE_TIMESTAMP_S  Type = ( /*line :33:27*/_Ciconst_DUCKDB_TYPE_TIMESTAMP_S /*line :33:51*/)
	TYPE_TIMESTAMP_MS Type = ( /*line :34:27*/_Ciconst_DUCKDB_TYPE_TIMESTAMP_MS /*line :34:52*/)
	TYPE_TIMESTAMP_NS Type = ( /*line :35:27*/_Ciconst_DUCKDB_TYPE_TIMESTAMP_NS /*line :35:52*/)
	TYPE_ENUM         Type = ( /*line :36:27*/_Ciconst_DUCKDB_TYPE_ENUM /*line :36:44*/)
	TYPE_LIST         Type = ( /*line :37:27*/_Ciconst_DUCKDB_TYPE_LIST /*line :37:44*/)
	TYPE_STRUCT       Type = ( /*line :38:27*/_Ciconst_DUCKDB_TYPE_STRUCT /*line :38:46*/)
	TYPE_MAP          Type = ( /*line :39:27*/_Ciconst_DUCKDB_TYPE_MAP /*line :39:43*/)
	TYPE_ARRAY        Type = ( /*line :40:27*/_Ciconst_DUCKDB_TYPE_ARRAY /*line :40:45*/)
	TYPE_UUID         Type = ( /*line :41:27*/_Ciconst_DUCKDB_TYPE_UUID /*line :41:44*/)
	TYPE_UNION        Type = ( /*line :42:27*/_Ciconst_DUCKDB_TYPE_UNION /*line :42:45*/)
	TYPE_BIT          Type = ( /*line :43:27*/_Ciconst_DUCKDB_TYPE_BIT /*line :43:43*/)
	TYPE_TIME_TZ      Type = ( /*line :44:27*/_Ciconst_DUCKDB_TYPE_TIME_TZ /*line :44:47*/)
	TYPE_TIMESTAMP_TZ Type = ( /*line :45:27*/_Ciconst_DUCKDB_TYPE_TIMESTAMP_TZ /*line :45:52*/)
	TYPE_ANY          Type = ( /*line :46:27*/_Ciconst_DUCKDB_TYPE_ANY /*line :46:43*/)
	TYPE_VARINT       Type = ( /*line :47:27*/_Ciconst_DUCKDB_TYPE_VARINT /*line :47:46*/)
	TYPE_SQLNULL      Type = ( /*line :48:27*/_Ciconst_DUCKDB_TYPE_SQLNULL /*line :48:47*/)
)

// FIXME: Implement support for these types.
var unsupportedTypeToStringMap = map[Type]string{
	TYPE_INVALID:  "INVALID",
	TYPE_UHUGEINT: "UHUGEINT",
	TYPE_ARRAY:    "ARRAY",
	TYPE_UNION:    "UNION",
	TYPE_BIT:      "BIT",
	TYPE_ANY:      "ANY",
	TYPE_VARINT:   "VARINT",
}

var typeToStringMap = map[Type]string{
	TYPE_INVALID:      "INVALID",
	TYPE_BOOLEAN:      "BOOLEAN",
	TYPE_TINYINT:      "TINYINT",
	TYPE_SMALLINT:     "SMALLINT",
	TYPE_INTEGER:      "INTEGER",
	TYPE_BIGINT:       "BIGINT",
	TYPE_UTINYINT:     "UTINYINT",
	TYPE_USMALLINT:    "USMALLINT",
	TYPE_UINTEGER:     "UINTEGER",
	TYPE_UBIGINT:      "UBIGINT",
	TYPE_FLOAT:        "FLOAT",
	TYPE_DOUBLE:       "DOUBLE",
	TYPE_TIMESTAMP:    "TIMESTAMP",
	TYPE_DATE:         "DATE",
	TYPE_TIME:         "TIME",
	TYPE_INTERVAL:     "INTERVAL",
	TYPE_HUGEINT:      "HUGEINT",
	TYPE_UHUGEINT:     "UHUGEINT",
	TYPE_VARCHAR:      "VARCHAR",
	TYPE_BLOB:         "BLOB",
	TYPE_DECIMAL:      "DECIMAL",
	TYPE_TIMESTAMP_S:  "TIMESTAMP_S",
	TYPE_TIMESTAMP_MS: "TIMESTAMP_MS",
	TYPE_TIMESTAMP_NS: "TIMESTAMP_NS",
	TYPE_ENUM:         "ENUM",
	TYPE_LIST:         "LIST",
	TYPE_STRUCT:       "STRUCT",
	TYPE_MAP:          "MAP",
	TYPE_ARRAY:        "ARRAY",
	TYPE_UUID:         "UUID",
	TYPE_UNION:        "UNION",
	TYPE_BIT:          "BIT",
	TYPE_TIME_TZ:      "TIMETZ",
	TYPE_TIMESTAMP_TZ: "TIMESTAMPTZ",
	TYPE_ANY:          "ANY",
	TYPE_VARINT:       "VARINT",
	TYPE_SQLNULL:      "SQLNULL",
}
