// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.3/value.go:1:1
package duckdb

/*
#include <duckdb.h>
*/
import _ "unsafe"

import (
	"unsafe"
)

func getValue(info TypeInfo, v  /*line :12:32*/_Ctype_duckdb_value /*line :12:46*/) (any, error) {
	t := info.InternalType()
	switch t {
	case TYPE_BOOLEAN:
		return bool(func() _Ctype__Bool{ _cgo0 := /*line :16:33*/v; _cgoCheckPointer(_cgo0, nil); return /*line :16:35*/_Cfunc_duckdb_get_bool(_cgo0); }()), nil
	case TYPE_TINYINT:
		return int8(func() _Ctype_int8_t{ _cgo0 := /*line :18:33*/v; _cgoCheckPointer(_cgo0, nil); return /*line :18:35*/_Cfunc_duckdb_get_int8(_cgo0); }()), nil
	case TYPE_SMALLINT:
		return int16(func() _Ctype_int16_t{ _cgo0 := /*line :20:35*/v; _cgoCheckPointer(_cgo0, nil); return /*line :20:37*/_Cfunc_duckdb_get_int16(_cgo0); }()), nil
	case TYPE_INTEGER:
		return int32(func() _Ctype_int32_t{ _cgo0 := /*line :22:35*/v; _cgoCheckPointer(_cgo0, nil); return /*line :22:37*/_Cfunc_duckdb_get_int32(_cgo0); }()), nil
	case TYPE_BIGINT:
		return int64(func() _Ctype_int64_t{ _cgo0 := /*line :24:35*/v; _cgoCheckPointer(_cgo0, nil); return /*line :24:37*/_Cfunc_duckdb_get_int64(_cgo0); }()), nil
	case TYPE_UTINYINT:
		return uint8(func() _Ctype_uint8_t{ _cgo0 := /*line :26:35*/v; _cgoCheckPointer(_cgo0, nil); return /*line :26:37*/_Cfunc_duckdb_get_uint8(_cgo0); }()), nil
	case TYPE_USMALLINT:
		return uint16(func() _Ctype_uint16_t{ _cgo0 := /*line :28:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :28:39*/_Cfunc_duckdb_get_uint16(_cgo0); }()), nil
	case TYPE_UINTEGER:
		return uint32(func() _Ctype_uint32_t{ _cgo0 := /*line :30:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :30:39*/_Cfunc_duckdb_get_uint32(_cgo0); }()), nil
	case TYPE_UBIGINT:
		return uint64(func() _Ctype_uint64_t{ _cgo0 := /*line :32:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :32:39*/_Cfunc_duckdb_get_uint64(_cgo0); }()), nil
	case TYPE_FLOAT:
		return float32(func() _Ctype_float{ _cgo0 := /*line :34:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :34:39*/_Cfunc_duckdb_get_float(_cgo0); }()), nil
	case TYPE_DOUBLE:
		return float64(func() _Ctype_double{ _cgo0 := /*line :36:38*/v; _cgoCheckPointer(_cgo0, nil); return /*line :36:40*/_Cfunc_duckdb_get_double(_cgo0); }()), nil
	case TYPE_TIMESTAMP_S, TYPE_TIMESTAMP_MS, TYPE_TIMESTAMP_NS:
		// DuckDB's C API does not yet support get_timestamp_s|ms|ns.
		return nil, unsupportedTypeError(typeToStringMap[t])
	case TYPE_TIMESTAMP, TYPE_TIMESTAMP_TZ:
		ts := func() _Ctype_struct___4{ _cgo0 := /*line :41:32*/v; _cgoCheckPointer(_cgo0, nil); return /*line :41:34*/_Cfunc_duckdb_get_timestamp(_cgo0); }()
		return getTS(t, ts), nil
	case TYPE_DATE:
		date := func() _Ctype_struct___8{ _cgo0 := /*line :44:29*/v; _cgoCheckPointer(_cgo0, nil); return /*line :44:31*/_Cfunc_duckdb_get_date(_cgo0); }()
		return getDate(date), nil
	case TYPE_TIME:
		ti := func() _Ctype_struct___11{ _cgo0 := /*line :47:27*/v; _cgoCheckPointer(_cgo0, nil); return /*line :47:29*/_Cfunc_duckdb_get_time(_cgo0); }()
		return getTime(ti), nil
	case TYPE_TIME_TZ:
		ti := func() _Ctype_struct___12{ _cgo0 := /*line :50:30*/v; _cgoCheckPointer(_cgo0, nil); return /*line :50:32*/_Cfunc_duckdb_get_time_tz(_cgo0); }()
		return getTimeTZ(ti), nil
	case TYPE_INTERVAL:
		interval := func() _Ctype_struct___3{ _cgo0 := /*line :53:37*/v; _cgoCheckPointer(_cgo0, nil); return /*line :53:39*/_Cfunc_duckdb_get_interval(_cgo0); }()
		return getInterval(interval), nil
	case TYPE_HUGEINT:
		hugeint := func() _Ctype_struct___2{ _cgo0 := /*line :56:35*/v; _cgoCheckPointer(_cgo0, nil); return /*line :56:37*/_Cfunc_duckdb_get_hugeint(_cgo0); }()
		return hugeIntToNative(hugeint), nil
	case TYPE_VARCHAR:
		str := func() *_Ctype_char{ _cgo0 := /*line :59:31*/v; _cgoCheckPointer(_cgo0, nil); return /*line :59:33*/_Cfunc_duckdb_get_varchar(_cgo0); }()
		ret := ( /*line :60:10*/_Cfunc_GoString /*line :60:19*/)(str)
		func() { _cgo0 := /*line :61:17*/unsafe.Pointer(str); _cgoCheckPointer(_cgo0, nil); /*line :61:37*/_Cfunc_duckdb_free(_cgo0); }()
		return ret, nil
	default:
		return nil, unsupportedTypeError(typeToStringMap[t])
	}
}
