// Code generated by cmd/cgo; DO NOT EDIT.

//line /sessions/great-funny-faraday/go/pkg/mod/github.com/apache/arrow-go/v18@v18.0.0/arrow/cdata/import_allocator.go:1:1
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cdata

import (
	"sync/atomic"
	"unsafe"

	"github.com/apache/arrow-go/v18/arrow/internal/debug"
)

// #include "arrow/c/helpers.h"
// #include <stdlib.h>
import _ "unsafe"

type importAllocator struct {
	bufCount int64

	arr *CArrowArray
}

func (i *importAllocator) addBuffer() {
	atomic.AddInt64(&i.bufCount, 1)
}

func (*importAllocator) Allocate(int) []byte {
	panic("cannot allocate from importAllocator")
}

func (*importAllocator) Reallocate(int, []byte) []byte {
	panic("cannot reallocate from importAllocator")
}

func (i *importAllocator) Free([]byte) {
	debug.Assert(atomic.LoadInt64(&i.bufCount) > 0, "too many releases")

	if atomic.AddInt64(&i.bufCount, -1) == 0 {
		defer func() func() { _cgo0 := /*line :52:16*/unsafe.Pointer(i.arr); return func() { _cgoCheckPointer(_cgo0, nil); /*line :52:38*/_Cfunc_free(_cgo0); }}()()
		func() { _cgo0 := /*line :53:23*/i.arr; _cgoCheckPointer(_cgo0, nil); /*line :53:29*/_Cfunc_ArrowArrayRelease(_cgo0); }()
		if func() _Ctype_int{ _cgo0 := /*line :54:29*/i.arr; _cgoCheckPointer(_cgo0, nil); return /*line :54:35*/_Cfunc_ArrowArrayIsReleased(_cgo0); }() != 1 {
			panic("did not release C mem")
		}
	}
}
